### PR TITLE
The Block Power

### PR DESCRIPTION
**Pull request by vibern0**
The Block Power
=========================

* Speaker   : Bernardo Vieira
* Available : Any day, All day
* Length    : workshop - 50 min
* Language  : English (Portuguese if there's no foreigners)

Description
-----------

Yeah yeah, you heard about it, blockchain. But we are in 2019 and blockchain is 'still' around (some thought it would disappear). 
With [ethereum blockchain](https://www.ethereum.org/) and the help of the [truffle framework](https://truffleframework.com/) we will build a decentralized application.
We will use [solidity language](solidity.readthedocs.io) and [nodejs](nodejs.org) (javascript) although it does not require any previous knowledge. Please join, bring questions, a laptop or at least attention.

Speaker Bio
-----------

Hi, my name is Bernardo, I'm currently in Lisbon working for a blockchain company. I work mostly with ethereum blockchain and the tools around it, but I've also worked with hyperledger fabric and stellar.
I'm very passionate about this field and what it can bring to us. Reach me during the event, it will be a pleasure to meet you.

Links
-----

* Blog: https://medium.com/@obernardovieira
* Company: https://techhq.io
* GitHub: https://github.com/obernardovieira

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi. Can you please sort out some of the english in the proposal? Thank you.

Also, since you marked this as a workshop, how long would it be?

**Comment by vibern0** [comment]
Hi @carlosefr you mean, make the presentation smaller or put links in words like "truffle"?
Hmm, maybe 1h. More than that, nobody is paying attention.

Thanks

**Comment by carlosefr** [comment]
I mean, we need to know how long would this be (i.e. one calendar slot — ~50 minutes, two slots, half a slot). If you're proposing 1h (one slot), please make it explicit in the proposal.

Also, I've identified (fixed) some typos in the PR description, can you please fix them in the proposal itself? Thanks.

**Comment by vibern0** [comment]
Is it better now?
As soon as you say the comment is ok I will fix the PR file.

**Comment by carlosefr** [comment]
Can you complete the "We will be using ethereum and truffle framework." with some indication of what would be the purpose? (i.e. folks should have a rough idea of what those things are without having to follow links — which may not be available on the medium where the calendar is being displayed).

Thanks.

**Comment by vibern0** [comment]
I'm sorry, I understand you. I just don't know how to get more generic. Does it look better? Sorry for being so annoying.

**Comment by carlosefr** [comment]
No problem, but you need to update the proposal in the PR as well. Also, I took the liberty to fix some typos in the PR description, which (if you agree) should also be updated in the proposal itself. Thanks.

**Comment by vibern0** [comment]
Yeah, sure. Thank you so much. There you have it :slightly_smiling_face:

**Pull request merged**
