### PR TITLE
Embedded software/firmware for Chinese ebikes motor controllers and displays

### PR DESCRIPTION
**Pull request by casainho**
Embedded software/firmware for Chinese ebikes motor controllers and displays
=========================

* Speaker   : Jorge Pinto
* Available : any day
* Length    : 30 mins
* Language  : Portuguese

Description
-----------

I will share my experience about developing firmware for chinese ebikes displays and motor controllers. While I do the same as my day job working for a german company, over the years, I started OpenSource projects to develop knowledge and firmware for chinese ebike motor controllers and displays.

I will share the tricks I did learn, like: how to put working the dirty cheap and resources limited hardware/firmware; why and how OEMs are loocking the final users; how I manage this OpenSource projects.

Speaker Bio
-----------

Over the years I am being developing OpenSource knowledge and technology for electric vehicules: motor controllers, battery controllers and displays. I believe this is my contribuiton for a better greener world.

Links
-----

* Company: https://www.brakeforceone.de
* GitHub: https://github.com/casainho

Extra Information
-----------------

I will mainly focus my presentation on my last year project (https://github.com/OpenSource-EBike-firmware/TSDZ2_wiki/wiki), were I developed knowledge and firmware for a popular and cheap ebike motor. I also developed the firmware for a segments LCD and for another 320x480 color LCD (both of them work with motor). This projects are mostly ended and here is feedback from users:

* this motor now feels more like the Bosch motor
* the motor is more efficient, stronger, it's feel like I have a new motor
* the info which is shown on LCD makes the total package way better
* this is GOLD. I still have a smile on my face

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi. Can you give an overview of how this talk will be different from the one you gave in 2017?

https://github.com/PixelsCamp/talks/pull/161

**Comment by casainho** [comment]
The content will be different because last year I developed for the first time to EBike LCDs. There are no other projects like this worldwide (I am using EBikes since 10 years ago).

**Comment by carlosefr** [comment]
I don't doubt that the subject may allow for talks with different content, and embedded development is a subject that we would lke to see at Pixels Camp. However, by comparing this proposal with the last year's, it's very hard to figure out where they'll be different. Or, at least, not the same talk with a subtly different spin:

>  Since some years, I am being developing OpenSource firmware for the chinese electric motor controllers that are used on small electric vehicules: hoverboards, skates, unicycles and bicycles. This chinese controllers are dirty cheap, capable and with ok quality. Since they optimize their products for price, they have very limited resources - developing firmware for their controllers means learning how to make "the thing" in a unique and creative ways, optimizing all the processing power and memory used. Why I decided strategically to develop firmware for the cheap chinese controllers? Because the market is flooded with them: they work well and are easy to get. This OpenSource firmware is the first in the world and I hope it will be used by many users as possible, shapping the future like Arduino did. I would like to present my experience, from developing the firmware and up to try gather a community and contact with people all over the world (using a lot Google translator for german, chinese, etc).

To consider this submission, we would need a rewording of the proposal in a way that clearly makes it different. Not just clear for us, but for the audience.

**Comment by casainho** [comment]
So I will u6odate the proposal with focus only ebike segment and color LCDs, that were the new developments this last year comparing to the developments of previous year proposal.

**Comment by carlosefr** [comment]
I'm sorry but our calendar is now full, which means your talk didn't make the cut this year.

**Comment by casainho** [comment]
Thanks. I had things happening on last weeks that required my full focus so I had to let this opportunity go.

**Pull request closed without merging**
