### PR TITLE
GraphQL to the rescue!

### PR DESCRIPTION
**Pull request by jcmfernandes**
# GraphQL to the rescue!
- Speaker   : João Fernandes
- Available : October 6th, 7th and 8th
- Length    : 30 mins
- Language  : English
## Description

Does your web API look like an octopus, featuring more endpoints than Linux has system calls? Feeling like madness by now? Or are you constantly overfetching data from your backend and/or making your clients go through a gazillion roundtrips to get all the data they need? Then lets talk about GraphQL, Facebook's new data query language and gift to the world.

I'm proposing a 70-30% theoretical/practical talk about how GraphQL is shaping web development, and for that we will cover (WIP agenda!)
- Basics of GraphQL (why it was born and what is it)
- The impact on frontend development (e.g., queries, mutations, caching, tooling)
- The impact on backend development (e.g., schemas, scaling, tooling)
- Should you use it? (e.g., maturity, future plans for the language)
## Speaker Bio

I'm a software engineer, experienced in the embedded and web worlds, passionate about technology and entrepreneurship. IST alumni.

Currently working at meta-icg, Portugal, as a Lead Developer, creating a new crazy product. Shhhh, it's still a bit of a secret! :)

Previously worked at
- Talkdesk, Portugal, as a Software Engineer and Team Lead of the Call Routing Team
- Coriant, Portugal, as an Embedded R&D Engineer in the Base Software Group
- Honeywell Aerospace, Czech Republic, as an R&D Scientist and Principal Investigator in the Platform Systems Group
## Links
- Github: http://github.com/jcmfernandes
- email: jfernandes _be_smart_ meta-icg.com

### CODE REVIEW

**Comment by ivoanjo** [comment]
:+1:

**Comment by dnlserrano** [comment]
:+1:

**Comment by celso** [comment]
Hi João, we need you to apply here so we can get your email etc to give you feedback on the talk review process: https://pixels.camp/apply/

Thanks!

**Comment by jcmfernandes** [comment]
Oh, thanks for the notice @celso, I will take care of that today! 😉

**Comment by jcmfernandes** [comment]
And it's done @celso!

**Comment by celso** [comment]
@jcmfernandes check your email please

**Pull request merged**
