### PR TITLE
Developing Applications for Smart TVs

### PR DESCRIPTION
**Pull request by dmpasilva**
Developing Applications for Smart TVs
=================================================

* Speaker   : David Silva
* Available : Any day
* Length    : 45 minutes
* Language  : English

Description
-----------

Smart TVs invaded our homes and are currently part of our lives, but the number of applications available in their stores is reduced and not very diverse. 

This can be justified because people are actually not interested in developing apps for them for several reasons (JavaScript being a strong one) or because the documentation may appear outdated or difficult to understand for newcomers.

In this talk I am going to present the state of the art of Smart TV development and some techniques that any one can use to get started and develop their own.

I will be mostly focused on using Angular as the starting framework for app development and I intend to showcase some of my homebrew applications made for these devices as a starting point for others to do the same.

Some of the instructions given in this talk will be targeted at LG TVs but they should work with minor changes for other Smart TVs as well.

Speaker Bio
-----------

I am a full-stack developer at Satcom International AG and I am passionate for almost everything tech related as long as I find it challenging.

I began playing with web technologies when I was 16, exploring the world of WordPress and creating custom plugins and Multisite installations, and I haven't stopped learning new things ever since.

I started my professional carreer as Junior Researcher at IEETA where I developed a web-based solution for evaluation the compliance of PACS applications with the DICOM standard. After that, I joined Satcom as a front-end engineer working with Angular and I'm still working in that same company, now as a full stack developer.

During my free time I like to develop some side projects and to read about web development, mobile, security and devops.

Links
-----

* Blog: https://www.davidsilva.pt/
* Company: [Satcom International AG](https://www.satcom-int.com/)
* GitHub: https://github.com/dmpasilva
* Photo: https://avatars0.githubusercontent.com/u/11501709

### CODE REVIEW

**Comment by carlosefr** [comment]
Would you consider extending your talk to 45 minutes + QA to minimize stage downtime (all slots are 1 hour long)?

Please update both the PR description above and the `.md` file if you do.

**Comment by dmpasilva** [comment]
Description updated!
One question: I specified the company where I am working at, but this talk is about a personal hobby.
Should I remove the company name and URL or shoud I keep it like it is?

**Comment by carlosefr** [comment]
We don't mind either way. If you keep it, we may include it as part of your speaker bio.

**Comment by carlosefr** [comment]
Congratulations @dmpasilva, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
