### PR TITLE
Ubuntu Touch the mobile Linux OS

### PR DESCRIPTION
**Pull request by DiogoConstantino**
Ubuntu Touch, the mobile Linux OS
=================================================

* Speaker   : **Diogo Constantino**
* Available : **second day, third day**
* Length    : **45**
* Language  : **Portuguese**

Description
-----------

Ubuntu Touch was initially created by Canonical, with the aim to offer a revolutionary
convergence experience, therefore combining the best of the mobile and desktop user
experience from Ubuntu Linux.
Ubuntu Touch is capable to provide an adaptable but consistent and friendly experiences
to the users, using the same device and the same exact software based on the same source
code.
At the moment Ubuntu Touch is developed and maintained by the UBports Community, and is
the main hope for real GNU/Linux and privacy on the mobile arena, on this I will let you
know why and how you should join our revolution.

Speaker Bio
-----------

IT Consultant with specialization on GNU/Linux and Free Software, very active
Free Software and Digitai Rights advocate currently, very active within the
Ubuntu Community in Portugal and Europe, member of the UBports project, tech
rellated themes podcaster.

Links
-----

* Company: https://ubports.com
* Photo: https://pbs.twimg.com/profile_images/550988430025310208/g_lHlcn7_400x400.jpeg

Extra Information
-----------------
I'll be presenting the UBports project work on Ubuntu Touch, the importance of this OS
for user freedom and privacy, and how can people like the typical PixelsCamp audinece
join in and help Ubuntu Touch, the mobile Free Software app ecossystem and even the
broader mobile GNU/Linux operating systems through the joint efforts between those and
the UBports Community.

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, thanks for your proposal.

Would you consider extending your talk to 45 minutes + QA to minimize stage downtime (all slots are 1 hour long)?

Please update both the PR description above and the `.md` file if you do.

Also, you should consider breaking up the talk description into several sentences. I lost my (mind) breath trying to read it all in one go. ;)

**Comment by DiogoConstantino** [comment]
Yes I can extend the talk. I'll do the changees latter today.

**Comment by DiogoConstantino** [comment]
Updated.

**Comment by carlosefr** [comment]
You proposal is still under review but, due to logistics constraints, we cannot guarantee any more stage slots at this moment. Until the **beginning of March** more slots are likely to become available and we will approve a few more proposals as we can, so this isn't a rejection notification.

We understand that delaying a decision reduces the time you have to prepare, shall your proposal turn out to be approved. So, if you need a decision from us until a particular date, please tell us by commenting here in this PR thread.

**Comment by carlosefr** [comment]
@DiogoConstantino There are a couple of minor typos in your speaker bio.

**Pull request closed without merging**
