### PR TITLE
Agile and  Marketing, climbing the Tower of Babel

### PR DESCRIPTION
**Pull request by brunoamaral**
Agile and  Marketing, climbing the Tower of Babel
=================================================

* Speaker   : Bruno Amaral
* Available : every day
* Length    : 30 minutes + 15 minutes for questions
* Language  : English

Description
-----------

Scrum and the Agile mindset have become the _de facto_ way of work in companies who require software development, and this sometimes clashes with the Communication and Marketing Departments way of work.

This talk is a description of the friction that can arise between these two stakeholders, and how to bridge the gap between the developers and the marketeers. 

Speaker Bio
-----------

I am a Digital Strategist, divided between tech and creativity. Currently working for the EDP Group, as a Product Owner, and teaching in the Masters Course of Communication and Digital Strategy, at the Lisbon University.

Over the past two years I have helped launch 10 corporate websites for EDP, across 3 countries. 

My experience also includes work as a Content Strategist; Social Media Manager for brands like McDonald's, and Siemens; and UX Consultancy.

My current project around creativity can be seen at https://cryptonovel.net/

Links
-----

* Blog: https://brunoamaral.eu/
* Company: 
* GitHub: https://github.com/brunoamaral
* Photo: https://brunoamaral.eu/page/the-author/images/brunoamaral.jpg

Extra Information
-----------------

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi. Your talk is a bit too short to be considered. All slots are 1 hour long and, although we prefer to avoid stage downtime with 45 minutes + QA talks, the bare minimum is 30 minutes (+ QA).

Would you extend it?

**Comment by brunoamaral** [comment]
@carlosefr sure, it should be easy to fill 30 mns + QA for 15 mns.

**Comment by carlosefr** [comment]
Can you please update the PR description and the `.md` file with that information?

**Comment by brunoamaral** [comment]
@carlosefr done! 🙂

**Comment by carlosefr** [comment]
Congratulations @brunoamaral, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by brunoamaral** [comment]
Awesome, thank you @carlosefr !

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
