### PR TITLE
Agile Kamasutra

### PR DESCRIPTION
**Pull request by davidscordeiro**
Agile Kamasutra
========================

* Speaker   : David Silva Cordeiro and Nuno Silva Pereira
* Available : Anytime 
* Length    : 30 mins
* Language  : English

Description
-----------

The cradle of Agile Methodologies started in the beginning of the 1990’s, still to these days and although they have spread through a lot of companies, the mentalities are still from the industrial era.

As programmers, product owners, project managers…whatever is your role in the IT industry, one of the main issues is to grow a true team - as a group of people is not a team.

Using Kamasutra metaphors, Nuno and David will make a parallelism between how you should engage with your team like you should do with your sexual partner. Create a healthy, trustful and lost lasting relationship and you reach agile nirvana.

“Sex is part of human nature. Agile is part of teams nature.”

The goal of this talk is for everyone to get back to their teams and help them excel in delivering more value for the clients, the team members and yourself!

---------------

Speaker Bio
-----------

 David Silva Cordeiro is a Delivery Lead @ Equal Experts helping teams and clients achieve awesomeness. With 11 years experience, he has worked in IT for Banking, Oil&Gas and Telco's in both Portugal and Norway. 
 Nuno Silva Pereira is a Delivery Lead @ Equal Experts working in projects in different geographies and sectors. He has worked for more that 10 years within IT and Telco's (Sapo, Portugal Telecom, Nos). 
 Both are members of Agile Connect and co-organizers of the Agile Connect Lisbon Meetup.

### CODE REVIEW

**Comment by davidscordeiro** [comment]
Agile Kamasutra
========================

* Speaker   : David Silva Cordeiro and Nuno Silva Pereira
* Available : Anytime 
* Length    : 30 mins
* Language  : English

Description
-----------

“Sex is part of human nature. Agile is part of teams nature.”
With the talk "Agile Kamasutra", Nuno and David will make a parallelism between how you should engage with your team like you should do with your sexual partner. Create a healthy, trustful and lost lasting relationship and you reach agile nirvana. 

---------------

Speaker Bio
-----------

 David Silva Cordeiro is a Delivery Lead @ Equal Experts helping teams and clients achieve awesomeness. With 11 years experience, he has worked in IT for Banking, Oil&Gas and Telco's in both Portugal and Norway. 
 Nuno Silva Pereira is a Delivery Lead @ Equal Experts working in projects in different geographies and sectors. He has worked for more that 10 years within IT and Telco's (Sapo, Portugal Telecom, Nos). 
 Both are members of Agile Connect and co-organizers of the Agile Connect Lisbon Meetup.

**Comment by carlosefr** [comment]
The talk description needs to be in the first comment for our backoffice to pick it up. Can you please edit it?

Also, both speakers need to register (and apply) for the event. I couldn't find either of you in our user listings.

**Comment by davidscordeiro** [comment]
thanks @carlosefr we edited the comment and applied for the event!

**Comment by celso** [comment]
Hi @davidscordeiro  , thanks for your proposal. We're going to need slightly better description for your talk. Can you read "Make makes a good proposal?" and reevaluate your pitch?

https://github.com/PixelsCamp/talks

**Comment by davidscordeiro** [comment]
Hi @celso thank you for the heads-up. We updated the comment and also the description on the file. Hope you consider our talk!

**Comment by celso** [comment]
@davidscordeiro thanks. @nunoaspereira has a another talk lined up. Can you do both?

**Comment by davidscordeiro** [comment]
@celso he edited the comment on the PR, but I noticed now he hasn't updated the actual file. I'll ping him, but he's away on vacation so I think that change can only be done next week. Can you use what's in the first comment of his PR for now?

**Comment by davidscordeiro** [comment]
@celso he's good with this, and so am I! Let's go 💪

**Pull request merged**
