### PR TITLE
Deployment pipeline for databases

### PR DESCRIPTION
**Pull request by eduardopiairo**
Deployment pipeline for databases
=================================================

* Speaker   : Eduardo Piairo
* Available : first day, second day, third day
* Length    : 60 minutes
* Language  : English

Description
-----------

Database development should not live in a different galaxy from application development.There aren't many reasons (or uses cases) preventing us from applying the concepts and practices like source control, continuous integration and continuous delivery and narrow down the gap between applications and databases. Yes, I know databases have data!

In this talk will explore the different ways how to set up a deployment pipeline (using automation) and the different challenges in each stage: source control, continuous integration, continuous delivery, and how the decisions (migrations vs state approach for example) in each step influences the next steps.

Speaker Bio
-----------

Operations engineer @ Skim Technologies that enjoys build software, pipelines and communities. Always ready to learn the path to production using source control, continuous integration and continuous delivery for applications, databases and infrastructure. The deployment pipeline is my favourite technical and cultural tool. 

Links
-----

* Blog: https://www.eduardopiairo.com/
* Company: [Skim Technologies](https://www.skimtechnologies.com/) 
* GitHub: https://github.com/eduardopiairo
* Photo: https://www.eduardopiairo.com/about/

Extra Information
-----------------

* https://www.youtube.com/watch?v=0YihV2kfb24
* https://www.youtube.com/watch?v=Txjf3nsKxVk&t=8s

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, you are submitting to proposals in the same pull request. They need to be in separate pull requests for either of them to be considered. Thanks.

**Comment by eduardopiairo** [comment]
@carlosefr I splitted the proposals in the following PRs:
https://github.com/PixelsCamp/talks/pull/409
https://github.com/PixelsCamp/talks/pull/410

**Comment by carlosefr** [comment]
You could have left the databases proposal on this one, by removing the other file, which would be better.

**Comment by eduardopiairo** [comment]
Ok. I will do that.

**Comment by eduardopiairo** [comment]
Because I deleted my original fork (and created a new one after making this PR) I cannot edit this PR (or at least I do not know) in order to remove the extra file. Any thoughts?

**Comment by carlosefr** [comment]
Ok. Please close this PR and we'll review the other two.

**Comment by carlosefr** [comment]
Nevermind, I closed it myself. :)

**Pull request closed without merging**
