### PR TITLE
So you want to be a manager

### PR DESCRIPTION
**Pull request by LuRsT**
So you want to be a manager
===========================

* Speaker   : Gil Gonçalves
* Available : Any day
* Length    : 60min
* Language  : English

Description
-----------

This talk will be about helping people understand what the job of a manager is, make a decision on whether they should be managers, and that there are more ways to advance than just to become a manager.
This talk is aimed at developers of all levels, but this will be more interesting to those who are considering making a career change/are being promoted into a manager role or those who may look into becoming a manager in the future.

Many developers will eventually make the choice of becoming a manager, the goal of this talk to help them make that decision.

Outline:
- What is a manager?
- What are some drawbacks from becoming a manager
- What are some good things about becoming a manager
- Should you be a manager?

Speaker Bio
-----------

Backend Lead living in London. Lives in the terminal, doesn't know anyone called GUI.

- Developer for 10 years
- Manager for almost 3 years

Links
-----

* Blog: [http://gil.codes](http://gil.codes)
* Company: [Unmade](https://unmade.com)
* GitHub: [lurst](https://github.com/lurst)
* Photo: https://avatars3.githubusercontent.com/u/263583

Extra Information
-----------------

I've given this talk at the [Python London Meetup](https://www.meetup.com/LondonPython/) and at last year's [PyconUK](https://www.youtube.com/watch?v=5SyZSvSpax8). Although this talk changes as my I grow in my role.

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, thanks for the proposal.

The PR description says the length of the talk is 60 minutes, but the `.md` says 30 minutes. Can you update one of them? (We prefer 60 minutes to avoid stage downtime, but the choice is yours.)

**Comment by LuRsT** [comment]
@carlosefr sure, I forgot to push, the talk is a 60min talk :). It's now updated.

**Comment by carlosefr** [comment]
Didn't notice earlier, but can you fix the `.md` file name? It's lacking proper separation between the talk title and speaker name.

**Comment by carlosefr** [comment]
Nevermind, we removed the file name requirement on our side.

**Comment by LuRsT** [comment]
I'll rename the file anyway @carlosefr 

`git mv So-you-want-to-be-a-manager_Gil{_,-}Goncalves.md`

**Comment by carlosefr** [comment]
Congratulations @LuRsT, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by LuRsT** [comment]
Yey! Thanks @carlosefr !

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
