### PR TITLE
Reactive React - The Observable Way

### PR DESCRIPTION
**Pull request by jpinho**
Reactive React - The Observable Way
=========================

* Speaker   : **João Pinho**
* Available : **All days, 10:30am-5:30pm**
* Length    : **45 minutes**
* Language  : **English**

Description
-----------

State Management libraries are like rabbits these days, there is one for every taste. But state management it's not a really hard problem to solve, so, why there are so many solutions for such easy problem.

This talk it's not only about a real world application that is mainly React, but it's also about a real world application that is entirely written in javascript, with pure functional code and no state management frameworks.

In this application we leverage the use of Observables (RxJS) and it's operators to support our functional code, and we end up using Observables as well for state management.

Although, there were some caveats when passing Observables to our React components, reason being that, Observable objects don't change, therefore our components don't refresh/redraw as expected.

This talk is about explaining this approach, it's architecture, how we tackled the issues with Observables and React components update, and ultimately showing that this can be a viable solution, currently used in production in one of our clients.

Speaker Bio
-----------

João is a Software Engineer with 10+ years of experience working on the field. He has always worked very closely with clients, doing analysis and requirements elicitation, and over time he has gained an inept skill to solve business needs using software.

Since the beginning of his career João has specialised mainly on server side solutions, but his curiosity and eagerness to learn, quickly pushed him to explore all the angles of an application. This has enabled him to be as proficient on the frontend, as he is on the backend. He is also experienced on DevOps work using technologies such as Kubernetes, Docker, Shell Script and Jenkins Pipelines.

He holds a MSc in Computer Science Engineering with a Major in Embedded Systems from the University of Lisbon.

More informally, by _he_ I mean _me_, and I'm also a husband, dad of a 2yr old babygirl, a pet owner of 2 dogs & a cat, and a Blue Belt Athlete/Competitor for Gracie Barra, a Brazilian Jiu Jitsu team.

Links
-----

* Blog: http://pinho.icodebox.net
* Company: https://www.equalexperts.com
* GitHub: https://github.com/jpinho

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi. Your proposal arrived past the deadline. This doesn't mean it's rejected, just that (when in doubt) other talks will get priority. It also means its approval (if it indeed happens) may happen much closer to the event.

The exception to this rule are talks that were already known to us by means other than GitHub.

In addition, we're asking everyone that proposes a 30 minute talk if they'd consider extending it to 45 minutes + QA to make it easier to fit the schedule. Would you?

**Comment by jpinho** [comment]
Hey Carlos,

No worries, thanks for your consideration!
I’ve no problem extending this talk for 45m, that way maybe I can also show with more time some snippets of code.

Thanks,

João Pinho

**Comment by carlosefr** [comment]
Ok. Can you update the proposal accordingly?

**Comment by jpinho** [comment]
> Ok. Can you update the proposal accordingly?

@carlosefr just did that, sorry for the delay! Thank you.

**Pull request merged**
