### PR TITLE
Unbabel API: Enabling Multilingual Conversations

### PR DESCRIPTION
**Pull request by pdimas**
# Unbabel API: Enabling Multilingual Conversations
- Speaker: Paulo Dimas
- Available: October 6,7,8
- Length: 30 mins
- Language: English
## Description

The wave of messaging apps as interfaces for all kinds of services started in China with WeChat and has rapidly become a new global reality. You can now order a pizza, buy products or book a flight chatting on Facebook Messenger. The conversation may happen with a bot, a real human or a mix of both. The challenge is that no matter what language is spoken by the user the conversation is seamless.

The Unbabel API makes this reality possible giving access to a crowd of human translators, distributed worldwide, empowered with Artificial Intelligence technology. The result is human quality translations that make chat conversations flow naturally in more than 20 languages. This session will show how you can make this possible with a few lines of code.
## Speaker Bio

Speaker Image

Paulo Dimas is the Head of Product at Unbabel, building the world’s translation layer by empowering with AI technology a worldwide community of bilinguals. Paulo has a passion for products, having developed his first commercial one at 14 years of age. After joining INESC at 16 to do research on interactive systems, Paulo has founded 3 startups, the last one Wizi, a VC funded geo-social startup that partnered with mobile carriers in 3 continents, taking geo-social discovery to any mobile subscribers. Paulo has created patents in geo-location technology and developed award-winning projects for major companies in the Media and Telecom industries.
## Links
- Blog: https://blog.unbabel.com/
- Company: http://www.unbabel.com

### CODE REVIEW

**Comment by celso** [comment]
Hi @pdimas :)

Two things so we can move on:
1. You need to register here: https://pixels.camp/apply
2. You need to post the talk markdown text in the pull request.

Thanks.

**Comment by pdimas** [comment]
Unbabel API: Enabling Multilingual Conversations
========================

* Speaker: Paulo Dimas
* Available: October 6,7,8
* Length: 30 mins
* Language: English

Description
-----------
The wave of messaging apps as interfaces for all kinds of services started in China with WeChat and has rapidly become a new global reality. You can now order a pizza, buy products or book a flight chatting on Facebook Messenger. The conversation may happen with a bot, a real human or a mix of both. The challenge is that no matter what language is spoken by the user the conversation is seamless.

The Unbabel API makes this reality possible giving access to a crowd of human translators, distributed worldwide, empowered with Artificial Intelligence technology. The result is human quality translations that make chat conversations flow naturally in more than 20 languages. This session will show how you can make this possible with a few lines of code.

Speaker Bio
-----------

Speaker Image

Paulo Dimas is the Head of Product at Unbabel, building the world’s translation layer by empowering with AI technology a worldwide community of bilinguals. Paulo has a passion for products, having developed his first commercial one at 14 years of age. After joining INESC at 16 to do research on interactive systems, Paulo has founded 3 startups, the last one Wizi, a VC funded geo-social startup that partnered with mobile carriers in 3 continents, taking geo-social discovery to any mobile subscribers. Paulo has created patents in geo-location technology and developed award-winning projects for major companies in the Media and Telecom industries.

Links
-----
* Blog: https://blog.unbabel.com/
* Company: http://www.unbabel.com

**Comment by pdimas** [comment]
Hi @celso, is everything ok now? Thanks -- Paulo

**Comment by celso** [comment]
Did you close the pull request? Reopen it please :)

**Comment by pdimas** [comment]
Reopened -- Paulo

**Pull request merged**
