### PR TITLE
Puppeteer can automate that!

### PR DESCRIPTION
**Pull request by onderceylan**
Puppeteer can automate that!
=================================================

* Speaker   : Önder Ceylan
* Available : first day, second day, third day
* Length    : 45 minutes
* Language  : English

Description
-----------

Puppeteer is a node library which provides a high-level API to control Chrome over the DevTools Protocol. It is mostly used and considered for scraping content, UI testing and automated form submissions. This talk aims to change this mindset by inspiring you on observing your daily routines and common patterns on your development and testing workflows. It will help you automate them in a creative way!

We’ll explore capabilities of Puppeteer with combination of DevTools protocol and cloud functions (FaaS) across a showcase of real life use cases demonstrated over 21 demos on stage. Finally, we’ll go through existing Puppeteer based SaaS solutions to inspire everyone in the room to build next SaaS solution or open source project with Puppeteer.

Speaker Bio
-----------

Önder is a Google Developer Expert in Web Technologies and he has been working on building web and mobile apps in various development ecosystems since late 90s. JavaScript and web has always been his passion and nowadays he enjoys it at its full while working as a Tech Lead at LINKIT. He believes in team work and he shares his knowledge on ITNEXT and GDG-NL communities as a co-organiser and speaker. He's also interested in photography, capturing night photos specifically.

Links
-----

* Blog: https://medium.com/@onderceylan
* Company: https://www.linkit.nl
* GitHub: https://github.com/onderceylan
* Twitter: https://twitter.com/onderceylan
* LinkedIn: https://www.linkedin.com/in/onderceylan
* Photo: https://ibb.co/RYs2V6L

Extra Information
-----------------

### Technologies

My talk will touch on the grounds of web standards, graphics / css filters, performance and server side JS, cloud functions (FaaS) topics. 

Following tags summarizes the tech referenced in the talk:
**chromium** **devtools** **chrome-devtools-protocol** **javascript** **nodejs** **puppeteer** **css** **test-tooling** **jest** **performance**

### Purpose of the talk

Puppeteer is most of the times used and considered by developers for scraping content or automated form submission. This is what people think about when the idea of browser automation is pitched. My goal is to change this mindset and to inspire people for the things that can be automated with a powerful browser & tooling pair. Especially, when Chrome DevTools Protocol and protocol monitor on Chrome is introduced to the audience, there's no limit on the automation possibilities.

### Target audience

Any software or QA engineer who uses Chrome / DevTools.

### Audience takeaway

I expect people to be inspired and excited by the capabilities of Puppeteer and the automation possibilities out there when I demonstrate 21 examples on stage. One of the demos can be seen here: [https://twitter.com/onderceylan/status/1197083395769208832](https://twitter.com/onderceylan/status/1197083395769208832)

I believe this talk will inspire everyone in the room to build next SaaS solution or open source project with Puppeteer to automate their daily routines and common problems.

### Remarks from the community

It got great feedback so far. I heard so many good things about it on offline and online channels. Some online feedbacks are like;

* [Thanks for your amazing talk Önder! You inspire us to build perf tools to our own needs.](https://twitter.com/devoorhoede/status/1197461713580363776)
* [Definitely one of the best talks !! It really inspired me to give puppeteer a try!](https://twitter.com/piyukore06/status/1197465015575547904)
* [Mind being absolutely blown at @onderceylan's talk about Puppeteer. Getting a few ideas on how I want to use it. #frontmania](https://twitter.com/rvdleun/status/1195319313265246208)
* [@onderceylan‘s talk on Puppeteer is like an easy-to-digest documentation on all the things Puppeteer can do. Will be my go to talk for anything Puppeteer for a while. @FrontMania #frontmania](https://twitter.com/PrashantPalikhe/status/1195315874921623552)

### Source

Source of the demos and references mentioned on slides: [https://github.com/onderceylan/puppeteer-demos](https://github.com/onderceylan/puppeteer-demos)

### Slides of previous versions of the talk

* [Puppeteer can automate that!](https://www.slideshare.net/nderCeylan/puppeteer-can-automate-that)
* [Intrducing perf budgets on CI with Puppeteer](https://www.slideshare.net/nderCeylan/introducing-perf-budgets-on-ci-with-puppeteer)

### Talk outline

* Introduction to headless Chrome
* Introduction to Puppeteer
* First set of demos to show some of the interesting capabilities of Puppeteer
* Introduction to Protocol Monitor and explaining how browser is being instrumented
* Introduction to Chrome DevTools Protocol
* Using CDP with Puppeteer
* Explaining how Puppeteer launches a browser instance and how one can connect to a remote instance over WS debuggable interface
* Introduction to the idea of Puppeteer Light =&gt; chrome launcher + puppeteer-core to avoid installation of a chromium bundle of over ~100mb
* More demos on utilizing CDP with Puppeteer
* Using puppeteer on cloud functions
* SaaS solutions based on Puppeteer
* Main takeaways

### Technical requirements

One of the demos I have requires sound output. 

### Why me talking abut Puppeteer?

I've spent fair amount of time on the subject on my journey of developing and maintaining my recent open source project: [pwa-asset-generator](https://github.com/onderceylan/pwa-asset-generator). I presented this topic in front of various communities like Frontmania, AmsterdamJS, perf.now(), C'T and more to come.

### CODE REVIEW

**Comment by onderceylan** [comment]
Video of the talk from Frontmania Conf is live on Youtube: https://www.youtube.com/watch?v=d2WSO3w5E94

**Comment by carlosefr** [comment]
Congratulations @onderceylan, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by onderceylan** [comment]
Hi @carlosefr, thank you very much for the confirmation! It's too bad that the conf dates conflict with another conference that was confirmed 2 weeks ago. I really wanted to come to Lisbon and engage with PixelsCamp community. I won't be able to do so now, and hopefully, I can join in the future.

**Comment by carlosefr** [comment]
We're sorry to hear that. We've released your slot to another proposal, and your attendee seat as well.

**Comment by onderceylan** [comment]
Thank you for your understanding and I'm sorry if it created any trouble with the planning. I'd be all in to make it up to you another time.

**Comment by onderceylan** [comment]
Hi @carlosefr, I've got an email stating that PixelsCamp is postponed to November. Would it be possible for me to be part of the event still?

**Comment by carlosefr** [comment]
In due time we will contact all approved speakers and (most likely) canceled speakers as well to confirm their submissions for the new dates.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request closed without merging**
