### PR TITLE
The Craft of TDD

### PR DESCRIPTION
**Pull request by rfelix**
# The Craft of TDD
- Speaker   : Raoul Felix
- Available : October 6th,  7th, or 8th
- Length    : ~ 30min
- Language  : English
## Description

While some might have mentioned a while back that [TDD is dead](http://martinfowler.com/articles/is-tdd-dead/), fortunately it's not the case because it's actually a practice that's quite useful in helping increase the quality of code, as well as aid in maintaining it.

I've been trying to follow the ideas behind TDD the past couple of years and, at Talkdesk, we use those ideas on a daily basis as they're a part of the way we work. I'd like to share some that knowledge that we've gained by practicing TDD up until now even though we still continue to learn more about it and get better at it.

Most of my experience with TDD has been with Ruby, a dynamic language, using RSpec, however the ideas behind this are the same and can be applied to any language. Some of the things I expect to cover are:
- Why do TDD/BDD?
- The various types of tests you have at your disposal (unit tests, integration
  tests, acceptance tests, smoke tests, contract tests)
- Techniques to help making writing tests easier
- The difference between stubs and mocks and when you should use them (while
  avoiding making your tests very brittle)
- Things to watch out for while writing your tests (e.g. should we really follow
  the DRY principle in tests?)

This talk isn't aimed for the complete novice, it's not really a "how-to", instead it's aimed at those that have heard and looked into TDD and that might have tried it out but gave up because it takes time or didn't initially find it valuable. There will also be things for those that do TDD and are continuing to learn about it.

At the end of the talk I hope to convince you that TDD is actually quite useful, and that you leave with some awareness on how to make writing these tests a bit easier while avoiding some common traps as you continue on this path.

---
## Speaker Bio

Hi! My name is Raoul and I have the privilege of working with many talented, bright, and curious software engineers at Talkdesk over the past few years where I currently serve as the CTO as well as Team Lead of our Routing Team. I'm really passionate about software as a craft, on how to solve real problems with elegant code, using the right technologies that enable us be more productive
while delivering more value. I also try, and fail miserably, at keeping my Pocket article count low.
## Links
- Github: http://github.com/rfelix
- Company: http://talkdesk.com
## Contact Info
- Email: hi AT rfelix.com
- Twitter: [@rfelix_com](https://twitter.com/rfelix_com) (open DMs)

### CODE REVIEW

**Comment by celso** [comment]
Hi Raoul, we need you to apply here so we can get your email etc to give you feedback on the talk review process: https://pixels.camp/apply/

Thanks!

**Comment by celso** [comment]
@rfelix check your email please

**Comment by celso** [comment]
Closed due to lack of feedback from author. Can reopen if he emerges from the dead.

**Comment by jcmfernandes** [comment]
@celso I believe he is on vacation. I'll try to reach him.

**Comment by rfelix** [comment]
Hey there @celso! I am very much alive, or so I think 😄, but I'm currently on vacation and have been neglecting my email so sorry for the delay here (and thanks @jcmfernandes for the manual ping).

As requested, I've now just officially applied to Pixels Camp so now I believe you should have everything to be able to contact me. I arrive back from vacation on Sunday so I'll be sure to keep a look out for further communication from you/Pixels Camp org. Thanks again and apologies for the radio silence.

**Comment by rfelix** [comment]
Hey there @celso - is there any news on this? Thanks

**Pull request closed without merging**
