### PR TITLE
Remote Control

### PR DESCRIPTION
**Pull request by Shemahmforash**
# Remote Control

## The art of doing everything from the middle of nowhere

* Speaker   : **Carlos Rosão and Nuno Silva Pereira**
* Available : **21st and 22nd of March from 9am-6pm**
* Length    : **30m**
* Language  : **English**

## Description

Ever wanted to be able to work fully remote but never had the time to understand what needs to happen for that to work seamlessly?
In this talk we are going to share our experience of working in an agile environment with remote teams for the past 3 years (different projects in several countries), explaining the steps that need to be done in order to have a fully functional team, pitfalls to avoid and tips and tricks in order for you to be able to try it in your team.

**Learning Outcomes:**

* How to have a team work remote [tools and meetings (SUs, Retros, …)];
* Understand Remote vs WFH;
* Understand Remote Friendly vs Distributed Teams;
* Tips and tricks on how to engage with remote teams and people;
* Tips and tricks on how to work remotely;
* How to deal with people working in different time zones.

## Speakers Bio

* **Carlos Rosão** - [Linkedin](https://www.linkedin.com/in/carlos-ros%C3%A3o-72a22116/) - is a Senior Software Engineer @ Equal Experts with more than 10 years experience in the field. He has been working in different areas and geographies, from telco to music startups, from the travel industry to e-commerce businesses. His big passion is open source so he has collaborated in some well known projects.
* **Nuno Silva Pereira** - [Linkedin](https://www.linkedin.com/in/nunosilvapereira/) is a Delivery Lead @ Equal Experts working on projects in different geographies and industries. He has worked for more than 14 years within IT and Telco's (Sapo, Portugal Telecom, Nos). He is a member of Agile Connect and co-organizer of the Agile Connect Lisbon Meetup. Speaker at Pixels Camp on the last 2 editions.

## Links

* Blog: Agile Connect Meetup Organizers - https://www.meetup.com/Agile-Connect-Lisbon/
* Company: www.equalexperts.com
* GitHub: https://github.com/nunoaspereira | https://github.com/Shemahmforash
* Linkedin: https://www.linkedin.com/in/nunosilvapereira/ | https://www.linkedin.com/in/carlos-ros%C3%A3o-72a22116/
* Twitter: https://twitter.com/nunoaspereira | https://twitter.com/shemahmforash

## Extra Information

Nuno Pereira was a Speaker in 2 previous Pixels Camp (eager to be with you guys for the 3rd time):

### 2016

Talk - **"Rocking Agile - How to do Agile in a Rock Band"**

Agile is common sense redefined, so want to know more about how a group of individuals that never have heard about Agile Methodologies adapt to them in a Rock Band, if they are able to adapt, Agile can be adapted to a lot of different realities and situations.

### 2017
Talk - **"Agile Roadtrip" with David Cordeiro**

Want to know how your backlog can define the "why" and the "what", but leave the "how" for the development team?
Join us in this roadtrip where you'll also learn how to incorporate feedback and effectively drive your team using the backlog through a very simple analogy.

Co-authored-by: Nuno Silva Pereira <nunosilvapereira@gmail.com>

### CODE REVIEW

**Comment by carlosefr** [comment]
You you mind shortening the title a bit, if you can?

**Comment by Shemahmforash** [comment]
@carlosefr - Just added a new commit shortening the title and moving the subtitle to an h2.

**Comment by carlosefr** [comment]
@nunoaspereira Both speakers need to apply as participants at https://pixels.camp.

**Comment by Shemahmforash** [comment]
@carlosefr We both applied: https://pixels.camp/Shemahmforash and https://pixels.camp/nunoaspereira

**Pull request merged**
