### PR TITLE
Reverse-engineering Mega Drive games 25 years after the fact

### PR DESCRIPTION
**Pull request by liliambean**
Reverse-engineering Mega Drive games 25 years after the fact
=========================

* Speaker   : Fred Bronze
* Available : Every day, all day
* Length    : 45 minutes + Q&A
* Language  : English

Description
-----------

Visualshock! Speedshock! Soundshock! A look at the world of ROM hacking, one of its most prolific communities, and an everyday developer's foray into forbidden territory.

Speaker Bio
-----------

Fred is a .NET developer at agap2IT Portugal. In his free time, he writes 68k assembly code for the Sega Mega Drive. He is also author of the Sonic 3 Unlocked blog, which has barely been updated in the past year.

Links
-----

* Blog: https://s3unlocked.blogspot.com
* Company: http://www.agap2-it.pt
* GitHub: https://github.com/fredbronze

Extra Information
-----------------

This talk would be an extension of the content on my blog, with an added focus on the history of the Sonic hacking scene for context, and structured into a personal narrative that would hopefully be equal parts captivating and entertaining. James Mickens is my spirit animal.

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, thanks for your talk proposal.

Would you consider extending the talk to 45 minutes + QA, or do you prefer to stick with 30 minutes?

Also, can you shorten the title a bit, so that it fits the calendar? (If its longer than one line in the PR description, it would probably end up truncated.)

**Comment by liliambean** [comment]
Thank you for the feedback!

I am fine with either 30 or 45 minutes + Q&A, so I've updated the proposal as suggested.

I have also shortened the title slightly. It is still on the longer side but no longer the longest; please let me know if it needs to be trimmed down further.

**Comment by carlosefr** [comment]
If you can shorten it further, it would be better. Otherwise if could appear as "Afraid of assembly: reverse..." in places such as the event's digital signage. Longer titles are no problem, as long as the first few words convey the contents (enough).

**Comment by liliambean** [comment]
Alright, I've pushed the important bits up to the front. Though next time might I recommend just making the title a scrolling marquee? :)

**Pull request merged**
