### PR TITLE
Trello in agile teams: best practices

### PR DESCRIPTION
**Pull request by jpgcc**
# Trello in agile teams: best practices
- Speaker   : João Craveiro
- Available : 6th and 7th afternoon, 8th all-day
- Length    : 30 mins
- Language  : English
## Description

Trello is a very flexible productivity tool, with a wide range of application scenarios. In agile software development, small to medium projects can surely benefit from its simplicity (compared to more fully-featured --- and expensive --- tools). This talk is about the three main building blocks of a Trello board: labels, lists, and checklists. They're so simple, and yet so easy to get wrong in ways you may regret halfway through --- if you don't know some details about how these three elements work in Trello. I do not intend to prescribe a given way to organize your backlog/sprints/Kanban/whatever in a Trello board: in the end, you'll have my personal recipe for Trello-supported agile development with a good balance between the typical project management needs and not imposing too much overhead on development team members.
## Speaker Bio

Although there are titles attached to the things I do at a given moment, I have a hard time attributing one short designation to me as a professional. I love solving real problems of real people using computer technology as a means to it — be it by coding, by gathering requirements, by managing a project, by helping other people be more efficient, or by simply spreading knowledge.

I'm currently (since 2014) with Premium Minds, where I've been through the duties of developer, pro[du|je]ct manager, and agile coach. I'm also a professor at Universidade Lusófona (since 2013), where I lecture on computer architectures and on computer networks.

Before that? Well, a lot. From old to new, I've worked at a computer store, done web development, written tech pieces for a newspaper supplement, researched on embedded and real-time systems, wrote two theses and over a dozen papers, and been a teaching assistant at U. Lisbon for embedded systems, operating systems, computer architecture, and object-oriented programming courses.
## Links
- About me: http://about.me/jcraveiro
- Github: http://github.com/jpgcc
- Company: http://www.premium-minds.com

### CODE REVIEW

**Comment by pmlbrito** [comment]
Sounds cool! Will you be talking about pros and cons comparison to other tools like Jira or the likes?

**Comment by jpgcc** [comment]
@pmlbrito The focus is on how to get the most out of Trello, provided that you already made a conscious decision to use it for the time being—instead of something else. For this talk, I would not like to enter to deep into that debate, although I'll have a thing or two to say about having an exit strategy from Trello (and when to execute it).

**Comment by pmlbrito** [comment]
@jpgcc Oh, i see your point... but if you find the time, i think it could be a good topic for some Q&A and discussion after the talk

**Comment by celso** [comment]
@jpgcc check your email please

**Comment by jpgcc** [comment]
Already did. What's needed from my part?

**Pull request merged**
