### PR TITLE
a11y, who?

### PR DESCRIPTION
**Pull request by cristianocorreia**
a11y, who?
=========================

* Speaker   : [Cristiano Correia](https://avatars0.githubusercontent.com/u/4750068?s=460&v=4)
* Available : Both days, any time
* Length    : 45 minutes + QA
* Language  : English

Description
-----------

It's not a lie that the vast majority of web projects start without having Accessibility (a11y, for friends) in mind and it becomes daunting to go back and fix it.

Whit this in mind, let's change that.

I'm going to guide you through all the loops by: explaining the different accessibility categories; showing how to test your applications; and demonstrating how to fix the un-fixable: making a non-accessible product, accessible.

Web Accessibility is essentially a way of making your product reachable by all of your potential users and I want to show you how.

Speaker Bio
-----------

Cristiano Correia

With a background in engineering and design, my focus has always been building great products and great experiences.

I've been working continuously as a Frontend Engineer and UX Designer since 2012 across Portugal, Belgium, The Netherlands and Germany on a multitude of roles ranging from design, development and management. Currently I'm a Frontend Engineer at the Digital Experience Hub of Zalando, here in Lisbon.

Having contributed to and used multiple Design Systems, that's my favorite way of mixing both of my backgrounds on a project. I also have a soft spot for Accessibility and I'm always focused on trying to deliver in the most Agile way.

Links
-----

* Company: [Zalando SE](https://github.com/zalando)
* GitHub: [github.com/cristianocorreia](https://github.com/cristianocorreia)

Extra Information
-----------------

Published articles:
* [A Day in the Life of a Frontend Engineer at Zalando](https://jobs.zalando.com/tech/blog/frontend-engineer-zalando/) (Jan 2019 - [Zalando Tech Blog](https://jobs.zalando.com/tech/blog/))
* [How to Style Accessibility: a Web Components Approach](https://medium.freecodecamp.org/styling-accessibility-a-web-components-approach-dc2aa8123eb2) (Dec 2018 - [freeCodeCamp]())

Previous speaking and training appearances:
* Speaker: [All Paths Lead to UX](https://www.meetup.com/ironhack-lisbon/events/258125917/) (Jan 2019 - Ironhack)
* Speaker: [Styling Accessibility: A Web Components Approach](https://www.meetup.com/landing_jobs/events/256720438/) (Dec 2018 - Landing.jobs Meetup)
* Trainer: [Principles of User Experience](http://academy.findmore.pt/learning-areas/development/principles-of-user-experience-ux) (Jul 2017 - Findmore Academy)
* Trainer: [Introduction to AngularJs](http://academy.findmore.pt/learning-areas/development/introduction-to-angularjs) (May 2017 - Findmore Academy)
* Speaker: [E2E Testing](https://www.meetup.com/de-DE/Angular-Belgium/events/235752358/) (Nov 2016 - Angular Belgium Meetup)
* Trainer: [Thinking In AngularJS With A JQuery Background](http://academy.findmore.pt/learning-areas/development/thinking-in-angularjs-with-a-jquery-background) (Apr 2016 - Findmore Academy)
* Trainer: [HTML5 Overview](http://academy.findmore.pt/learning-areas/development/html5-overview
) (May 2015 - Findmore Academy)
* Trainer: [AngularJS Fundamentals](http://academy.findmore.pt/learning-areas/development/angularjs-fundamentals-new-session) (Apr 2015 - Findmore Academy)
* Trainer: [AngularJS Fundamentals](http://academy.findmore.pt/learning-areas/development/angularjs-fundamentals
) (Mar 2015 - Findmore Academy)

### CODE REVIEW

**Comment by carlosefr** [comment]
Would you care to extend the talk to 45 minutes + QA, or do you rather stick with 30 minutes?

Also, your proposal arrived past the deadline. This doesn't mean it's rejected, just that (when in doubt) other talks will get priority. It also means its approval (if it indeed happens) may happen much closer to the event.

The exception to this rule are talks that were already known to us by means other than GitHub.

**Comment by carlosefr** [comment]
Reviewers note: The contents of this proposal seem very similar to PR #261.

**Comment by cristianocorreia** [comment]
@carlosefr length of the talk corrected.

**Comment by brunoribeiro** [comment]
:+1:

**Pull request merged**
