### PR TITLE
v2.0: Monoliths, Microservices and Startups' horrible code

### PR DESCRIPTION
**Pull request by msf**
v2.0: Monoliths, Microservices and Startups' horrible code
=================================================

* Speaker   : Miguel Mascarenhas Filipe
* Available : any of the days
* Length    : 50
* Language  : English

Description
-----------

When I joined Unbabel in March 2019. Its core, the translation pipeline was at cross-roads of refactoring and re-designing a Monolith into Microservices. In this talk I'll tell a story on how we leapfrogged our old v1.0 distributed architecture (and what were its problems) and built a much simpler, easier to maintain and operate system. Be warned, unsurprisingly, the solution isn't a micro-service based architecture. :-)

To provide a bit more detail and "juice":  It was an evolving codebase whose first commit was made by the current CEO in 2013. It is safe to say it has its fair share of shortcomings and failings. =) Complexity is our enemy. Architectures with complex tightly-coupled distributed systems have complex failure scenarios and are by definition hard to debug and operate. If you had a problematic monolith and break it into 10 pieces, it is probable that you got yourself 100 problems now.

Speaker Bio
-----------

I’m a Software Engineer with 15 years of experience including start-ups and leading software corporations in three countries. I dive deep and take an end-to-end perspective. I'm always looking for hard problems to crack and high quality solutions. I currently work on the new architecture of Unbabel's translation services. Previously I worked on diverse problems such as backends for Citymapper's mobile apps, large scale distributed systems for Microsoft and Amazon Web Services where I helped launch DynamoDB, the world leading NoSQL Cloud Database, which led to co-authoring 13 US patents. Problems are waiting to be solved. =)

Links
-----

* Blog: https://twitter.com/m3thos
* Company: https://unbabel.com
* GitHub: https://github.com/msf
* Photo: https://s3.amazonaws.com/keybase_processed_uploads/b3b92f1a8ef25629ad5f18163278c605_360_360_square_360.png

Extra Information
-----------------

I once maintained a linux kernel rootkit that was very hard to detect because didn't use the syscall table...

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, thanks for the talk proposal.

A couple of edit suggestions:

* There is a typo in the tiltle (in the `.md`, which I fixed in the PR description above).
* I would suggest a title which focuses on the _what_ instead of the _where_ so it isn't confused for a (somewhat) commercial pitch at first glance. In my mind, I'm left wondering if I'm going to learn about just this company's specific challenges.

**Comment by carlosefr** [comment]
Hi. Can you please move your `.md` file to the repo's root please (next to `talk-title_presenter_name.md`)?

**Comment by msf** [comment]
@carlosefr thanks for your feedback. It helped create what I think is much better (and appealing) description of the talk.

I've changed the talk's title and re-worked the description.
The contents of the talk are still the same.

Please review again.

**Comment by carlosefr** [comment]
Thanks.

The title is a bit long and will be severely truncated in a few places (eg. the schedule, signage). However, the first few words convey enough meaning so I don't see it as much of a problem.

There is a typo in "monoliths", though. :)

**Comment by carlosefr** [comment]
Congratulations @msf, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
