### PR TITLE
GitOps for kubernetes with ArgoCD

### PR DESCRIPTION
**Pull request by eduardopiairo**
GitOps For Kubernetes with ArgoCD
=================================================

* Speaker   : Eduardo Piairo
* Available : second day, third day
* Length    : 60 minutes
* Language  : English

Description
-----------

This talk is about how I added the missing piece on my company deployment pipeline - the deliver step - using ArgoCD. ArgoCD is delivery tool for Kubernetes that allow a declarative approach by comparing the definition of the resource in the source control repository with the current state of the same resource in the kubernetes cluster. I will describe how ArgoCD allowed to automate a "simple" decision: to deploy or not to deploy. 

Speaker Bio
-----------

Operations engineer @ Skim Technologies that enjoys build software, pipelines and communities. Always ready to learn the path to production using source control, continuous integration and continuous delivery for applications, databases and infrastructure. The deployment pipeline is my favourite technical and cultural tool. 

Links
-----

* Blog: https://www.eduardopiairo.com/
* Company: [Skim Technologies](https://www.skimtechnologies.com/) 
* GitHub: https://github.com/eduardopiairo
* Photo: https://www.eduardopiairo.com/about/

Extra Information
-----------------

When I joined my company there was a missing step in the deployment pipeline: the delivery step. The delivery process was manual - meaning that someone (me) would need to create/upgrade the applications on the Kubernetes cluster. The urgent goal was to automate this process and for that we introduced ArgoCD in our pipeline.
ArgoCD allows a declarative approach by comparing the definition of the resource in the source control repository with the definition of the same resource in the kubernetes cluster. In simple words, it compares the definition in the git repository with the current state in the kubernetes cluster and give the diff.
Whit this "simple" capability it was possible to integrate in the pipeline (in a automated way) an important decision: deploy or not to deploy a specific definition in a target environment.

* https://www.youtube.com/watch?v=0YihV2kfb24
* https://www.youtube.com/watch?v=Txjf3nsKxVk&t=8s

### CODE REVIEW

**Comment by carlosefr** [comment]
For the record, this PR was created after the deadline but it's the result of splitting PR #399, which was created within the call-for-talks period.

**Comment by carlosefr** [comment]
Would you consider extending your talk to 45 minutes + QA to minimize stage downtime (all slots are 1 hour long)?

Please update both the PR description above and the `.md` file if you do.

Also, there are a few typos in the talk description.

**Comment by eduardopiairo** [comment]
Yes, I can extend the talk to 60 minutes. Updated the PR.

**Comment by carlosefr** [comment]
We usually avoid approving multiple submissions from the same person to allow others to get their chance to go on stage. Due to your talk proposal in PR #409 having been accepted, this proposal has a very low (but not zero) chance of getting accepted.

**Pull request closed without merging**
