### PR TITLE
Load Test All the Things

### PR DESCRIPTION
**Pull request by nmcc**
Load Test all the things
========================

* Speaker   : Nuno Caneco
* Available : September 28th or 29th - no time restrictions
* Length    : 60 mins
* Language  : English

Description
-----------

Not all applications are born the same: some are subject to high load, others will be hit with a couple of requests every once in a while; some will be fed with loads and loads of data, others will deal with a couple of MBytes from time to time; some are built with performance as a non-functional requirement, other are "just made to work".

Either way, it's important to be able to assess how the application will behave under heavy load in terms of high number of requests and/or high data load.

This will be a hands-on session where we will explore some load testing tools, learn how to build a simple yet effective Load Test Plan and analyse a bit through the results.

---------------
[*All things below are optional*]

Speaker Bio
-----------

Nuno Caneco is an Engineering Manager and Cluster Lead at Farfetch.

Nuno is passionate about building good, reliable and performant software. Beside building software, Agile is also a big part of Nuno's professional career, as he has been making his way as Scrum Master and coaching Teams.

Links
-----

* Blog: https://medium.com/@nuno.caneco
* Company: https://www.farfetch.com/
* Github: https://github.com/nmcc/

### CODE REVIEW

**Comment by carlosefr** [comment]
"When you're ready, submit a pull request and comment using your markdown file contents."

Can you please add the proposal markdown to the first comment? Thanks.

**Comment by nmcc** [comment]
Done! Thanks 😄

**Comment by carlosefr** [comment]
You don't appear to have applied to Pixels Camp, this is required for the talk proposal to be valid.

**Comment by nmcc** [comment]
Yes, I missed the application 😞 Sorry
I've already submitted my application.

**Comment by celso** [comment]
Hi @nmcc  , thanks for your proposal. We're going to need slightly better description for your talk with more detail. Can you read "Make makes a good proposal?" and reevaluate your pitch?

https://github.com/PixelsCamp/talks

**Comment by nmcc** [comment]
Hi @celso. Just updated the proposal. Can you please re-check it and provide feedback?
Thanks!

**Pull request merged**
