### PR TITLE
PWAs and Fighting Against App Stores

### PR DESCRIPTION
**Pull request by gabrielpoca**
PWAs and Fighting Against App Stores
====================================

* Speaker : Gabriel Poça
* Available : first day, second day
* Length : 60 minutes
* Language : English

Description
-----------

This talk is about what we can do with the open web. There are two parts to it.

The first part is smaller and philosophical. I'll talk about the open web and
its importance. My purpose is to show how broken the mobile world is, and how
dangerous the play store and app store are. How we've been in this situation
before, and what we should be doing to avoid getting into it again. These
stores are not open platforms, but most people cannot choose not
to use them. There have been plenty of antitrust lawsuits filed against Apple
and Google but nothing seems to change. Shouldn't we stop feeding the giant
before it gets too big?

The second part of this talk is more technical. I'll show what's available on
the web right now, and why it's probably enough for most of your apps. We'll
talk about deploys, notifications, offline support, media access, file system
access, etc. There's a lot in there. We will go over the good and the bad,
clarifying the limitations of each technology. I'll talk about what's to come
and to which platform. I also show what you can do right now to leverage both
web and native technology while you wait for support on the web.

The information in this talk is based on real life experience building PWAs for
many years now.

Speaker Bio
-----------

I don't have a fancy title to show of. I'm a developer and my work goes from
hiring to cloud infrastructure. For the past two years I've been focused on
building the infrastructure for UTRUST (https://utrust.com/), which is a
payment gateway for blockchains. I write a lot of Elixir and JavaScript. I care
about the social impact software has, and how the choices we make today impact
other people and the next generation.

Links
-----

* Blog: https://gabrielpoca.com/
* Company: https://subvisual.co/
* GitHub: https://github.com/gabrielpoca

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, thanks for the proposal.

From the description it seems a lot of topics for just 30 minutes, don't you agree?

**Comment by carlosefr** [comment]
Also, can you please modify your `.md` file to follow the same format as the provided template? The markdown style in your file is different, and that may not agree with some of our ad-hoc scripts.

**Comment by gabrielpoca** [comment]
@carlosefr I'm sorry about the formatting, between the copy paste from last year's talk, and my editor formatting it automatically, I didn't notice. I think 30 minutes are good, but is this 30 minutes with questions? In that case it may be not enough.

**Comment by carlosefr** [comment]
Talk slots are *always* 1 hour long, so it would be 30 minutes + QA.

If you can, we would prefer you'd extend the talk to 45 minutes + QA to reduce stage downtime. This is not mandatory, though.

If you decide to extend it, please update the `.md` file as well as the PR description above.

**Comment by gabrielpoca** [comment]
@carlosefr updated for 60 minutes 👍

**Comment by meddulla** [comment]
Congratulations @gabrielpoca, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
