### PR TITLE
Blockchain in your project — you don't need it, unless you don't have a choice

### PR DESCRIPTION
**Pull request by kirushik**
Blockchain in your project — you don't need it, unless you don't have a choice
=================================================

* Speaker   : Kirill Pimenov
* Available : Any day, no preference
* Length    : 60 minutes (including Q&A)
* Language  : English

Description
-----------

Blockchains are terrible, slow, fragile distributed databases.
If you have a project in front of you, and one of your options is to try blockchain there somehow — please stop.
No, really, don't; you'll regret it.
Even that Long Blockchain iced tea company didn't make it ;-).

Blockchains are exciting, groundbreaking, empowering socio-technical constructs.
This means that they allow you to solve a whole novel class of problems, problems for which you didn't have any solution before.
Problems you probably used to ignore, thinking they are "just the way things are".
Trust problems; social scalability and coordination problems; privacy and data control and ownership problems.

If you learn to identify those in your business, and match them with our newly discovered toolkit of distributed, (almost) trustless computer systems — then and only then blockchain technology might actually help you to get ahead and achieve a thing unachievable for your competition.

In this talk I'll try to cast away all technical lingo and all zealotry usually associated with the blockchain scene, and focus on honestly identifying the possibilities and applications.
I will never mention solutions of my company nor our competitors in the space while doing so, keeping the conversation high-level, non-promotional and intellectually fair.

Speaker Bio
-----------

I'm Head of Security at Parity Technologies — a company which develops opensource technology for decentralized systems and helps customers (proudly including United Nations) to build on top of it.
Before Parity I developed nontrivial application backends as a CTO of my own startup, and worked on continuously delivering web-facing services for SUSE Linux.

Links
-----

* Company: https://parity.io
* GitHub: https://github.com/kirushik
* Photo: https://ipfs.io/ipfs/QmNeqT9wi8hFgj9DTyEsoEDkPLmoze41ENR7RNPtrcFp67

Extra Information
-----------------

Throughout the recent years I presented at multiple high-profile conferences, including Devcon 4 (https://www.youtube.com/watch?v=sEt1t_29DLw) and Web3 Summit 2018 (https://www.youtube.com/watch?v=J2lnjFqi-No).

### CODE REVIEW

**Comment by carlosefr** [comment]
Thanks for the proposal.

Can you shorten the title a little, or rearrange words to make it more truncation-resistant? It will be heavily truncated in places such as the event schedule, signage, etc.

**Comment by kirushik** [comment]
@carlosefr OK, I've truncated the header. The playfulness went away, but I hope this solves the technical issues; please let me know what the limit is if that is not enough.

**Comment by carlosefr** [comment]
The title can be longer than it is right now. The issue is being truncation-resistant.

For example, in the event signage it may appear as "Why your project doesn't...", which is not very informative, so removing words at the end is less important than moving important bits to the start.

Suggestion: "Blockchain: Why your project doesn't need it (unless you don't have a choice)"

**Comment by kirushik** [comment]
@carlosefr that makes sense; what do you think about it now?
The punchline is _concentrated_ in the beginning of the sentence, and even if it would be truncated to the first couple of words, it would still give at least relative idea of what's this all about

**Comment by carlosefr** [comment]
Congratulations @kirushik, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
