### PR TITLE
How to defeat imposter syndrome: confessions of a developer

### PR DESCRIPTION
**Pull request by satboy78**
How to defeat imposter syndrome: confessions of a developer
=================================================

* Speaker   : **Matteo Bruno**
* Available : **any day**
* Length    : **60**
* Language  : **English**

Description
-----------

Do you feel like you don't belong, you don't deserve what you achieved, everyone in your office is more talented than you? Do you have imposter syndrome... too?

Imposter syndrome is common across all industries, but the increasing pressure to be successful in IT is taking its toll on employees, affecting more than half workers, me included :)

After many years working in tech for a lot of companies (from startups to big corporations) in many business fields, I found a way to overcome self-doubt and turn this weird feeling in a booster for greater achievements... and I want to share it with you!

Speaker Bio
-----------

Señor software engineer, pizza lover, traveller, runner, blockchain & crypto enthusiast (sometimes not in this order :) ).

I’ve started programming @ 12yo, and since then I aimed to develop software, fostering my ability to lead complex projects within a multi-cultural environment, always continuing learning and improving my skills.

After 4 years in Milan, working for Viacom as Senior Software Engineer, taking care of their international sites and APIs, on January 2019 I decided to move to Barcelona and face a new challenge, working for Europcar Mobility Group on the Connected Cars Platform. 

Currently working as Senior Software Engineer & Golang chapter co-captain @ Europcar Mobility Group (BCN)

Links
-----

* Blog: https://www.linkedin.com/in/brunomatteo
* Company: https://global.ubeeqo.com/
* GitHub: https://github.com/satboy78
* Photo: <a href="https://www.linkedin.com/in/brunomatteo" target="_new">profile</a>

Extra Information
-----------------

I already presented this talk to many meetups in Italy and Spain, such as https://www.meetup.com/it-IT/GDG-Milano/events/261594679/ and https://www.meetup.com/it-IT/Meetup-de-InnoIT-Consulting-en-Barcelona/events/265191557/
Also, my talk was chosen for the opening keynote of GDG DevFest Tyumen 2019 - https://devfest.gdgtmn.ru/schedule/

Click [here][1] to see the full calendar and pick your favorite talks

[1]: https://pixels.camp/schedule/

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi Matteo, thanks for your proposal.

Can you make these two changes to the title in both the `.md` and the PR description?

* Remove the extra markup (italic);
* Shorten it (perhaps by a third).

Long titles will get truncated on the schedule, signage, and other media.

**Comment by satboy78** [comment]
Hi Carlos,
I just shortened the title and removed the extra italic.
Please let me know if there is anything else I should do.
Thanks a lot.
Cheers!

**Comment by carlosefr** [comment]
That's better and OK by us.

But may I suggest reversing the sentence for extra credit? 😉
> How to defeat imposter syndrome: confessions of a developer

If the title gets truncated, and that's surely going to happen when it's longer than 4 or 5 words, then the remaining part still conveys what the talk is about.

No need to change if you don't want to.

**Comment by satboy78** [comment]
let's go for the extra credit!  😉
thanks

**Comment by carlosefr** [comment]
Congratulations, your talk proposal has been **pre-accepted**.

This means it's actually approved for Pixels Camp just not yet in our scheduling worflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
Hi. Can you please move your `.md` file out of the `2019/` directory into the root of the repo (next to `talk-title_presenter_name.md`)?

**Comment by satboy78** [comment]
Hi Carlos! Sure, I just did it.
Have a great day!
Best,
Matteo

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
