### PR TITLE
vue-cli custom plugins

### PR DESCRIPTION
**Pull request by jcostasilva**
vue-cli custom plugins
=========================

* Speaker   : Jorge Costa da Silva
* Available : Second and third days, any time
* Length    : 60 minutes
* Language  : English

Description
-----------

The new version of the vue-cli is one of the best news in the Vue ecosystem of the last few months! In this talk we will cover the main features of vue-cli, namely custom plugins, one of the most exciting ones. The plugin system is at the core of vue-cli and with custom plugins we take full control of the development experience.

Speaker Bio
-----------

Founder and CEO of Openbox Software. Writer of Vue Handbook (https://leanpub.com/manual-vuejs). Co-organizer of Vue.js Lisbon Meetup. 

Links
-----

* Company: https://openbox.pt
* GitHub: https://github.com/jcostasilva

### CODE REVIEW

**Comment by carlosefr** [comment]
Would you mind extending the talk to 45 minutes + QA, or do you prefer to stick with 30 minutes?

**Comment by jcostasilva** [comment]
Hi,
No problema with that format. It is probably more suitable.

De: Carlos Rodrigues
Enviado: 21 de janeiro de 2019 12:59
Para: PixelsCamp/talks
Cc: jcostasilva; Author
Assunto: Re: [PixelsCamp/talks] vue-cli custom plugins (#266)

Would you mind extending the talk to 45 minutes + QA, or do you prefer to stick with 30 minutes?

**Comment by carlosefr** [comment]
You need to update the PR description and the proposal.

**Comment by carlosefr** [comment]
I'm sorry but our calendar is now full, which means your talk didn't make the cut this year.

**Pull request closed without merging**
