### PR TITLE
Let’s get lazy with React

### PR DESCRIPTION
**Pull request by ricardani**
Let’s get lazy with React
=================================================

* Speaker   : **Ricardo Soares Silva**
* Available : **first day, second day**
* Length    : **90 minutes** (workshop)
* Language  : **English**

Description
-----------

Do you like how your application gets bundled into a single file? 

Do you like that the user has to download the full code only to find out they never left the home page? 
And then you add features, new pages, experiments and the bundle gets bigger and bigger and bigger. 

Fortunately, React allows you to split your main code bundle into several chunks that can be lazy loaded by the users only when needed. 

And how is this done? 
By using one of the future features of ECMAScript: dynamic imports.

Do you hate it when you need to write code like this in every component

    if (isLoading) {
        return <LoadingSpinner />;
    }
    return (
        <>
            <ActualComponent />
        </>
    );

just to handle the loading state? React is trying to solve this in their experimental branch by using Suspense

    return (
        <Suspense fallback={<LoadingSpinner />}>
            <ActualComponent />
        <Suspense />
    );

Join us and learn how to be lazy and write less code with React. 

Speaker Bio
-----------

<div>

Ricardo is a software developer at Blip. He is not intimidated in switching between frontend and backend technologies, without forgetting to test everything to assure the quality of his code. He believes that with an amazing team the sky is the limit.
</div>

Links
-----

* Company: [Blip](https://blip.pt/)
* GitHub: [Ricardani](https://github.com/ricardani)
* Photo: [Photo](https://raw.githubusercontent.com/PixelsCamp/talks/master/img/ricardo_soares.jpg)

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi,

Can you please remove the italic markup from the talk title?

Also, there are a few missing words in the description, and I would suggest breaking up the first paragraph into multiple paragraphs as well.

**Comment by ricardani** [comment]
Hi

Removed the italic markup from the title and updated the description

**Comment by carlosefr** [comment]
Congratulations @ricardani, your workshop proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
