### PR TITLE
On the edge of the real world. An introduction.

### PR DESCRIPTION
**Pull request by gounthar**
On the edge of the real world. An introduction
=========================

* Speaker   : Bruno Verachten
* Available : Any time
* Length    : 45 minutes
* Language  : English

Description
-----------

`Raspberry Pis` have been there like forever, and have sold like hot cakes for 16 years now. Lots of people have done very ambitious projects ([self driving robot](https://github.com/bdjukic/selfdriving-robot-car), anyone?), and new ideas and projects surface *everyday*. Be it building a supercomputer by stacking lots of SBCs, a [bitcoin miner](https://hub.packtpub.com/how-mine-bitcoin-your-raspberry-pi/), a [brewery system](https://www.brewpi.com/), home [automation](https://www.home-assistant.io/), a [weather station](http://airpi.es/whatisthis.php) or any [crazy idea](https://www.bestvpn.com/guides/raspberry-pi-projects/), the only limit seems to be your imagination.

Of course, these little beasts can also be used as `servers`. For years, Docker has been used only on big `servers`, but after  [resin.io](https://resin.io/blog/why-port-docker-to-the-raspberry-pi/) ported Docker to the Arm processor, everything changed.

Pretty cool to be able to run Docker on that kind of mini machines,  but what kind of service could you run on Docker with so little memory? Lots of things in fact…

And what if you could get the best of both worlds? What could you do  with a machine able to interact with hardware (🌡️, 📹 , 🚦) thanks to  Docker? Could you transform your Raspberry Pi into an edge computing node, an  IoT on steroids 💪 or anything in between?

Speaker Bio
-----------

Father of *two*, husband of *one*, geek in denial, fond of handheld devices since 1989, beekeepeer and [permie].
`#Linux #Android #Docker #ARMV8 #IOT`

* Joined [Worldline] in 1999.
* Currently works as a continuous integration for mobile development specialist in a transversal unit. 
* Fond of Linux and open source, hand-held devices ([SBC]...).
* Also interested in new techniques in gardening, woodworking by hand, bike commuting and tons of other subjects.
* Disguised as taciturn, but a chatterbox.

Trying to push the use of ARM Socs in his [job] and everywhere [else]...

[permie]: https://www.credential.net/5ufvm4zp
[Worldline]: https://worldline.com/
[SBC]: https://www.armbian.com/download/
[else]: https://github.com/gounthar
[job]: https://github.com/WorksOnArm/cluster/issues/81

Links
-----

* Blog: https://medium.com/@poddingue
* Company: https://fr.worldline.com/
* GitHub: https://github.com/gounthar/

Extra Information
-----------------

The subject I address is not new but  not mainstream either (yet). I’ve been working on this subject for quite  a while now, and have lead a few workshops on this very subject in the [company](https://worldline.com/)  I work for. I have also written a few articles on ARM/Linux/Docker/Gitlab in my  company, and I am in the process of rewriting them to publish on [medium](https://medium.com/@poddingue) and on [Worldline Tech](https://blog.worldline.tech/).

> This is a feedback on experience, but there are quite a few technical takeaways.

You will find previous [slides] of my talks and twitter references [there].

[there]:https://twitter.com/i/moments/1050320228901707776
[slides]:https://speakerdeck.com/gounthar
[talk]: https://twitter.com/i/moments/1014591620841340929
[company]: https://worldline.com/
[medium]: https://medium.com/@poddingue
[Worldline Tech]: https://blog.worldline.tech/
[there]:https://twitter.com/i/moments/1050320228901707776
[slides]:https://speakerdeck.com/gounthar
[talk]: https://twitter.com/i/moments/1014591620841340929
[Docker]: https://www.docker.com/

### CODE REVIEW

**Comment by carlosefr** [comment]
I've updated the PR description with the contents of your proposal as per the submission rules. Here's your previous description:

> `Raspberry Pis` have been there like forever, and have sold like hot cakes for 16 years now. Lots of people have done very ambitious projects ([self driving robot](https://github.com/bdjukic/selfdriving-robot-car), anyone?), and new ideas and projects surface _everyday_. Be it building a supercomputer by stacking lots of SBCs, a [bitcoin miner](https://hub.packtpub.com/how-mine-bitcoin-your-raspberry-pi/), a [brewery system](https://www.brewpi.com/), home [automation](https://www.home-assistant.io/), a [weather station](http://airpi.es/whatisthis.php) or any [crazy idea](https://www.bestvpn.com/guides/raspberry-pi-projects/), the only limit seems to be your imagination.
> 
> Of course, these little beasts can also be used as `servers`. For years, Docker has been used only on big `servers`, but after [resin.io](https://resin.io/blog/why-port-docker-to-the-raspberry-pi/) ported Docker to the Arm processor, everything changed.
> 
> Pretty cool to be able to run Docker on that kind of mini machines, but what kind of service could you run on Docker with so little memory? Lots of things in fact…
> 
> And what if you could get the best of both worlds? What could you do with a machine able to interact with hardware (🌡️, 📹 , 🚦) thanks to Docker? Could you transform your Raspberry Pi into an edge computing node, an IoT on steroids 💪 or anything in between?

**Comment by carlosefr** [comment]
Can you please update your proposal to remove images from the talk description? Emoji is fine, though.

Also, would you consider extending this talk to 45 minutes + QA?

**Comment by gounthar** [comment]
I removed the image, thanks for the feedback.
Yes, I can extend this talk to 45 minutes.

**Comment by carlosefr** [comment]
Thanks, but can you update the length in the proposal and PR description, please?

**Comment by gounthar** [comment]
Sorry about that, I just corrected the length.

**Comment by carlosefr** [comment]
This talk has been pre-approved, which makes your other proposals in PR #257 and PR #256 unlikely (but not impossible) to be approved.

**Pull request merged**
