### PR TITLE
Writing Code That Writes a Book

### PR DESCRIPTION
**Pull request by LuRsT**
Writing Code That Writes a Book
===============================

* Speaker   : Gil Goncalves
* Available : Everyday
* Length    : 45min
* Language  : English

Description
-----------

In 2018 I participated on my first [NanoGenMo](https://github.com/NaNoGenMo/2018) which is an event where programmers write
code that writes a book during the month of November.

This talk will be all about generative art, more specifically about generating text with code, I will teach you how to make you own,
best practices, how other people did it, and how to prepare yourself for next year's NanoGenMo.

There will be live coding where I will build a book with 50,000 words on stage.

I will be using Python for examples, but the talk will be language agnostic.

Speaker Bio
-----------

Gil leads the backend team at Unmade which is 80% Python, he loves code and people.

Links
-----

* Company: Unmade.com
* GitHub: https://github.com/lurst

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, can you please elaborate a bit more? The talk description alone should provide enough context without having to follow links.

**Comment by LuRsT** [comment]
@carlosefr I added a bit more information and a link, let me know if it's enough :+1: . Also, would you like me to update the PR description?

**Comment by carlosefr** [comment]
Yes, please.

**Comment by LuRsT** [comment]
Done @carlosefr

**Comment by carlosefr** [comment]
I'm sorry but our calendar is now full, which means your talk didn't make the cut this year.

**Comment by LuRsT** [comment]
That's a shame, I'll give a lighting talk instead if you'll have them @carlosefr.

**Comment by carlosefr** [comment]
We'll surely have.

**Pull request closed without merging**
