### PR TITLE
AWS API Gateway with Terraform

### PR DESCRIPTION
**Pull request by RicardoBrazao**
AWS API Gateway with Terraform
=========================

Or how a backend developer coded some infrastructure with zero DevOps knowledge.

* Speaker   : **Ricardo Brazão**
* Available : **21 and 22 March, 10am--6pm**
* Length    : **45 minutes + 15 of QA**
* Language  : **English**

Description
-----------

Ever wanted to create something in AWS? Feel over amazed with the AWS interface? Do you cry a little bit inside every time you look at the AWS dashboard? Then stay tuned for something that can ease your life, more than sliced bread did 🍞. In this talk we'll create a API Gateway in AWS without ever needing to go their dashboard, we'll just do what software developers love the most...code!!

Speaker Bio
-----------

**Ricardo Brazão**

image

I work as a software developer @Onfido, working mainly in Ruby (being it with Rails, Sinatra or Grape) but currently also looking a bit into the realm of Elixir. Although I'm mostly a backend developer, from time to time I like the frustration of stepping out of my confort zone and dwelve in the front end world or a bit of DevOps stuff as I think a software developer should know a bit of the surrounding universes.

Links
-----

* Blog: https://medium.com/@ricardobrazao
* Company: https://www.onfido.com
* GitHub: https://github.com/RicardoBrazao
* Twitter: [@RicBrazao](https://twitter.com/RicBrazao)

Extra Information
-----------------

This talk will be a presentation version of a blog post that [I wrote a while back](https://medium.com/onfido-tech/aws-api-gateway-with-terraform-7a2bebe8b68f). As this blog post was well received by the community and teached me the basics of Terraform and AWS API Gateway, I wanted to share my learning with the community as well.

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi. Can you please shorten the talk title? For example, by matching the title you gave to this PR?

**Comment by RicardoBrazao** [comment]
Hi @carlosefr! I've updated the title to match the one in the PR, I've pushed the second part of it to before my speaker bio just to maintain the scope of the talk.

**Comment by carlosefr** [comment]
Would you consider extending the talk to 45/50 minutes + QA or do you prefer to stick with 30 minutes?

**Comment by RicardoBrazao** [comment]
Yes, no problem with that. Want me to change the PR description to reflect that?

**Comment by edevil** [comment]
Yes, please.

**Pull request merged**
