### PR TITLE
Blockchain + Portuguese Justice = JusticeChain

### PR DESCRIPTION
**Pull request by RafaelAPB**
Blockchain + Portuguese Justice = JusticeChain
=================================================

* Speaker   : Rafael Belchior
* Available : All days
* Length    : 60 minutes
* Language  : English

Description
-----------

I would like to talk about how 1) Blockchains and 2) how can we reduce corruption in governments using distributed ledger technologies, in particular blockchain.
JusticeChain comes from a need of the Portuguese government to assure compliance from different parties, towards securing an important part of information system: applicational logs.

The talk includes:
1. The social (and technological) aspects of the corruption problem
1. What is blockchain and why do we need it at governments (and also the problems of blockchains)
1. Introducing one of the most popular permissioned blockhains: Hyperledger Fabric
1. JusticeChain: protecting justice data - uniting the stakeholders!
1. JusticeChain v2.0: Automatic, distributed, trusted audits
1. Future work and persepective about the evolution of blockchain

Speaker Bio
-----------
Trying to see the big picture, by applying technology to meaningfull problems.

* PhD student @Técnico Lisboa
* Teaching Assistant @Técnico Lisboa (It Infrastructure Management and Administration, Software Engineering, User Centered Design)
* Researcher @ INESC-ID. Interested in Blockchain and Data Science 
* Blockchain Developer at the Portuguese Government

I am fascinated with blockchain. Focusing on Hyperledger Fabric, Libra, and Ethereum.
More interestingly, working on how can we interoperate blockchains in order to provide the foundations to the mass adoption of this technology.

Links
-----

* LinkedIn: https://www.linkedin.com/in/rafaelpbelchior/
* Blog: https://medium.com/@rafaelbelchior and https://hackernoon.com/@rafaelbelchior
* Personal website: https://rafaelapb.github.io/

Extra Information
-----------------

Open source projects:
1. Hyperledger Fabric Based Access Control Project. Collaborated with the Linux Foundation and the Hyperledger Foundation as a mentor for this project.
2. GCE-Thesis, GCE-Inside View, Mr.Thesis (chatbot). A set of services for helping students choosing their thesis @Técnico Lisboa   

Previous talks
1. GCE - An Information System for Students, (50 attendees, Lisbon, Portugal)
2. JusticeChain: Using Blockchain to Protect Justice Data (20 attendees, Rhodes, Greece)

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi. Thanks for the proposal.

Can you please rename the `.md` file name to follow the name specified by the template (no spaces, no non-alphanumeric characters)?

**Comment by carlosefr** [comment]
Nevermind the file name, we fixed the restriction on our side.

**Comment by carlosefr** [comment]
I see you submitted two files, one of them being a workshop.

These need to be submitted in separate pull requests, to be reviewed (and accepted) independently.

If you submit the other one soon, we can ignore that it entered after the deadline. But we also need to know which one you'd prefer, since we rather not approve two proposals from the same person unless there are still free slots.

**Comment by carlosefr** [comment]
Oh, you already submitted it in PR #401. But you still need to remove the extra file from this PR.

**Comment by RafaelAPB** [comment]
Thanks, @carlosefr. My preferences are #402 , #401 and #365.
I do not have access to the forked repo with which I've submitted the PR. I can open a new one if needed.

**Comment by carlosefr** [comment]
Ok, please close this PR and reopen a new one so we can consider your proposal. Mention the closed PR in the new one so that we can keep track of the previous discussion.

**Comment by carlosefr** [comment]
Ignore the "closing the PR" bit, I closed it myself. :)

**Pull request closed without merging**
