### PR TITLE
Quantum Supremacy

### PR DESCRIPTION
**Pull request by msramalho**
Quantum Supremacy
=========================

* Speaker   : Miguel Sozinho Ramalho
* Available : first and second days
* Length    : workshop
* Language  : English

Description
-----------

In this workshop, participants will gain basic knowledge of what Quantum Computing is all about and how it has the potential to become the most disruptive breakthrough of the 21st century. Afterwards, we will have a hands-on experience by programming quantum circuits in Python (using IBM's Qiskit framework). Finally, we will try to run some of our circuits on real quantum computers (provided by IBM Q Experience, a cloud service for quantum computing). Participants will leave with some useful materials for continuing their quantum education.

Speaker Bio
-----------

MSc Student of [Computer|Software][Engineering|Science] @FEUP and research assistant @INESCTEC.  On a crusade to prove imagination is the only limitation - learning, teaching and programming help with that. I enjoy my personal projects, hackathons of all sorts, programming competitions and to have more to do than I have time for. My areas of focus range from Machine Learning to Quantum Computing, Infosec, Algorithms and Proper Software.

Links
-----

* Blog: https://msramalho.github.io
* GitHub: https://github.com/msramalho

Extra Information
-----------------

You can check [this course](https://github.com/msramalho/Teach-Me-Quantum) I developed on the topic of Quantum Computing 😉

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi. Thank you for your proposal, but (and maybe I'm being an old geezer on this) can you drop the emoji from the title?

**Comment by msramalho** [comment]
Hey @carlosefr, emoji dropped!

**Comment by carlosefr** [comment]
It's still in the proposal. ;)

**Comment by msramalho** [comment]
This is noob from my part, but I deleted my fork after the PR not knowing that I would not be able to push to it again, are you able to change the file? If not, I will simply open another PR. Sorry!

**Comment by carlosefr** [comment]
You can ask GitHub to ressuscitate your fork, maybe. Otherwise, you'll need to open another PR.

**Comment by msramalho** [comment]
Done, please check #247

**Pull request closed without merging**
