### PR TITLE
Unlocking ultimate productivity between engineers and designers

### PR DESCRIPTION
**Pull request by mariamargarida**
Unlocking ultimate productivity between engineers and designers
=========================

* Speaker   : Maria Margarida Silva
* Available : All days
* Length    : 40min + QA
* Language  : English

Description
-----------
In this talk, I'm going to go into processes, methodologies and tips to create an efficient working environment between designers and engineers. I will start by explaining how to successfully include engineers in the design phase of every project. Then, I'll go over how to deliver and prepare assets for the hand off to engineers. And finally, I'll talk about how to work with the engineers during and after the implementation phase. I'll present and justify several solutions that both design and engineering teams should implement to achieve maximum productivity.

Speaker Bio
-----------
Multimedia designer who graduated from the University of Coimbra and studied Arts in High School. Focused on creating experiences that people can easily understand and use.

Links
-----
* Blog: http://mariamargarida.me
* Company: https://www.joindrover.com/
* GitHub: https://github.com/mariamargarida

Extra Information
-----------------

### CODE REVIEW

**Comment by carlosefr** [comment]
Would you consider extending the talk to 45/50 minutes + QA or do you prefer to stick with 30 minutes?

**Comment by mariamargarida** [comment]
Hi @carlosefr! 40min + QA, is that okay?

**Comment by carlosefr** [comment]
Ok. Can you update the proposal with the new length? Thanks.

**Comment by mariamargarida** [comment]
Done! :)

**Pull request merged**
