### PR TITLE
Automating your Way to Confidence

### PR DESCRIPTION
**Pull request by naps62**
Automating your Way to Confidence
=================================================

* Speaker   : Miguel Palhas
* Available : first day, second day
* Length    : 60 minutes
* Language  : English

Description
-----------

We recently re-thinked the way we handle releases within our product team. The goal was to make everything more agile, automated, and a lot more transparent towards the rest of our company.
Around the same time, Github Actions went to public beta, and it ended up fitting our needs nicely. It also turned out that this CI has a lot more to offer than I was previously used to.

This talk is about our journey to make better and faster releases, about how I'm trying to deprecate our project managers, and about how awesome Github Actions can be.

Along the way, I'll show examples of how we, at [Utrust](https://utrust.com) are handling this process nowadays, as well as some other automations we built for our product team, which ended up saving us tens of hours of headaches during 2019.

Speaker Bio
-----------

I have a history of being both lazy and an over-engineer. I'll spend hours
tweaking that one vim config that will save me seconds later on.
For the past two years I've been focused on building the infrastructure for UTRUST (https://utrust.com/), which is a payment platform for cryptocurrencies.
I mostly use Elixir and Rust nowadays, and I have a passion for writing not just
code that works, but code that is meaningful and maintainable, as well as
teaching other on how to do the same.

Links
-----

* Blog: https://medium.com/@naps62
* Company: https://subvisual.com
* GitHub: https://github.com/naps62
* Photo: https://avatars1.githubusercontent.com/u/283819

Extra Information
-----------------

Previous talks:

* Pixels Camp 2016 - Mastering your Tools
* Pixels Camp 2017 - Hacking your IDEtor
* Pixels Camp 2019 - Smart Contracts: A Beginner’s Guide
* ScaleConf Colombia 2018 - An Introduction to Smart Contracts
* DevFest Siberia 2018 - An Introduction to Smart Contracts (https://www.youtube.com/watch?v=bYUrCHv9ewI)

### CODE REVIEW

**Comment by carlosefr** [comment]
Thanks for the proposal.

Would you consider extending the talk to 45 minutes + QA to better fill an 1 hour slot?

I think the markdown for the link in the description is the wrong way around. ;)

**Comment by naps62** [comment]
@carlosefr sure. link fixed, and changed to 60 minutes

**Comment by carlosefr** [comment]
Congratulations @naps62, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
