### PR TITLE
Accounting data in P2P-blockchain

### PR DESCRIPTION
**Pull request by saraivan**
Accounting data in P2P-blockchain
=================================================

* Speaker   : Nuno Saraiva
* Available : All days
* Length    : 30 to 45 minutes
* Language  : Portuguese (slides will be in english)

Description
-----------

Artificial intelligence will kill accounting. Blockchain will make it reborn.

In this talk I will show how AI and machine learning will replace 90% of the current work of accountants, very soon.
In addition I will talk about my vision of the future of corporate financial reporting and accounting records that will be stored in peer-to-peer networks using blockchain and ensuring error-free accounting.

Speaker Bio
-----------

Nuno Saraiva is an accountant since 2005, passionate about technology, geekiness, cryptocurrency and others.

Links
-----

* Blog: https://medium.com/@nsaraiva
* Company: https://seedaccounting.com — static website, need an upgrade
* GitHub:  https://github.com/saraivan
* Photo: http://seedaccounting.com/imgs/me.jpg

Extra Information
-----------------

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi Nuno,

Thanks for your talk proposal, it looks offbeat in a way that could be interesting. However, we have a requirement and a suggestion:

Please edit your `.md` file and remove the bits at the top, they make the file unpalatable to our backoffice.

The description section will be the summary of your talk in the event's schedule, and it needs to be catchy for geeks who probably aren't that much interested in accounting, but are interested in the other bits you mention. Think of ways to make it more appealing and if some of those bits can be part of the talk's title in some way. This is the suggestion part, it's up to you. :)

**Comment by saraivan** [comment]
Thank you. The thecnical issue is solved. I will commit a reformulated description and title in the next few days.

**Comment by carlosefr** [comment]
Ok. Please make sure you also update the PR title and description as well.

**Comment by carlosefr** [comment]
This looks much better. :)

But shortening the title a bit would be even better, to avoid getting cropped in the schedule (if it breaks into multiple lines in the PR title, then it will probably be ellipsed in the schedule). I think it can be done without loss of information.

But it's OK if you wish to keep it as it is.

**Comment by carlosefr** [comment]
Congratulations @saraivan, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
