### PR TITLE
VR Design : Designing Aplications for motion

### PR DESCRIPTION
**Pull request by Sckir**
VR Design : Designing Aplications for motion
=========================

* Speaker   : **Ricardo Francisco Vilelas de Almeida**
* Available : **First day, 9am - 7 pm, Second Day 9am-6pm, third day 9am-7pm**
* Length    : **45 minutes**
* Language  : **English**

Description
-----------

In this presentation we will be discussing what changes when we need to consider user body and space rather than computer periferals during VR development.

How do you plan for motion, how do you start thinking about motion? What problems can there be? 

Developing VR can be tricky but after this talk hopefully you will learn from my mistakes so you avoid yours.

Speaker Bio
-----------

Hello there! So for a brief introduction, I work at Collide as a Game Designer and Software Engineer!

VR is our main area and we are proud to have worked on several challenging projects some of which you may have heard!

I'm really passionate about Videogames, to me they are an art form like no other. 

I've worked on several team projects, some of which are, an educational game for the hearing impaired, with the aim of teaching sign language, this was done with the support from Associação Portuguesa de Surdos, from which we published a Scientific Paper, VR4NeuroPain which you can check out at our Website www.Collide.rocks, our very own Project Chatrooms and several others!

Right now I aim to become one of the, if not the, best Game Designers in the world.

I've still got a ways to go but I'm working on getting there!

If you've read this far, well thank you and have an awesome day!

Links
-----

* Company: www.collide.rocks
* GitHub: https://github.com/Sckir/
* Linkedin: www.linkedin.com/in/ricardo-almeida-3b7326a7

Extra Information
-----------------

* Publication about Gestual Life - http://epcg2014.estg.ipleiria.pt/downloads/Atas_EPCG2014.pdf
* Master Thesis regarding serious game design - https://repositorio.iscte-iul.pt/handle/10071/10951
* Video Game Event I created and presented on stage - https://lisbongameconf.iscte-iul.pt/

### CODE REVIEW

**Comment by carlosefr** [comment]
Your proposal arrived past the deadline. This doesn't mean it's rejected, just that (when in doubt) other talks will get priority. It also means its approval (if it indeed happens) may happen much closer to the event.

The exception to this rule are talks that were already known to us by means other than GitHub.

**Comment by carlosefr** [comment]
Hi, can you please reformat/rewrite your proposal? It must follow the template that we provided.
When you do that, please update the PR description as well. Thanks.

**Comment by Sckir** [comment]
Hello!

Thank you for pointing out the format, hopefuly everything will be fine now!

Also thank you for your time!

**Comment by carlosefr** [comment]
Just one more thing, can you please remove the formatting (italic) from the title?

**Comment by Sckir** [comment]
Hello!

No problem! Done!

**Pull request merged**
