### PR TITLE
It's Rocket Science - The Physics Behind Going to Space

### PR DESCRIPTION
**Pull request by lollolindblad**
It's Rocket Science - The Physics Behind Going to Space
=========================

* Speaker   : **Louise Lindblad**
* Available : **Any time**
* Length    : **45 minutes + QA**
* Language  : **English**

Description
-----------

With the rise of NewSpace and private space flight companies we've seen a steep rise in launch opportunities and hopefully we'll see humans heading for Mars soon. But how do we get to space? What's the physics behind launching a rocket? Come to this talk and learn about Rocket Science.

Speaker Bio
-----------

Louise has a degree in Engineering Physics from the Royal Institute of Technology in Stockholm and has also attended the International Space University. She has worked as a satellite systems engineer for several years before starting her own company, Valispace, where she is developing a browser-based modelling and collaboration software which helps engineers build better rockets and satellites.

Links
-----

* Company: https://www.valispace.com/
* GitHub: https://github.com/lollolindblad

### CODE REVIEW

**Comment by carlosefr** [comment]
Would you mind extending the talk to 45 minutes + QA, or do you prefer to stick with 30 minutes?

**Comment by lollolindblad** [comment]
Sure, 45 min + QA would be fine also!

**Comment by carlosefr** [comment]
Great. Can you please update the talk proposal? Thanks.

**Comment by lollolindblad** [comment]
Done!

**Pull request merged**
