### PR TITLE
Monads for the whole family

### PR DESCRIPTION
**Pull request by HugoDaniel**
Monads for the whole family
===========================

* Speaker   : Hugo Gomes
* Available : All the time
* Length    : 45mins
* Language  : Portuguese

Description
-----------

Monads are an advanced programming concept that can be used in any computer language by beginners. 

They are also known to be very hard to explain and to lead those who venture into confusion and frustration.

In this talk I don't intend to explain what they are or how they work (way smarter people than me have tried this without success).
Instead I decided to center the subject on the usual canonical programming examples that are used to explain your typical programming paradigms, that way I hope to enable the audacious to decompose any problem with monads.

I will lead the audience through a set of carefully collided examples so that they can see past the magical mythical golden aura that Monads have and realize the true trash cans that they really are.

---------------

Speaker Bio
-----------

I have been coding in Haskell for many years and since the day that i started that i absolutely hate it. In spite of that someone recently told me that i have a [pt git award for it](http://git-awards.com/users?country=portugal&language=haskell), which is a highly sophisticated way of saying that if i was a dog i would be a chihuahua

Tás a olhar ? Levas uma lambdidela.

Links
-----

* Blog: http://www.hugodaniel.pt
* Company: http://www.pixnit.com
* Github: http://github.com/HugoDaniel

### CODE REVIEW

**Comment by carlosefr** [comment]
Even tough you're proposing to do the talk in portuguese, the event's communication language is english, so both the title and description (and speaker bio) should be in english.

**Comment by HugoDaniel** [comment]
Everything then... I'll rewrite it in a few days. Thanks.

**Comment by HugoDaniel** [comment]
Done. I hope it meets the criteria :1st_place_medal:

**Comment by carlosefr** [comment]
You have to create a separate pull request for that second talk. Create another branch for it in your fork, and open the new pull request from there.

**Pull request merged**
