### PR TITLE
Your tech skills can help reduce e-waste

### PR DESCRIPTION
**Pull request by williamrjribeiro**
# Your tech skills can help reduce e-waste

- Speaker : William R. J. Ribeiro
- Available : first, second and third days
- Length : 60m
- Language : English

## Description

In this talk, William tells a story of how after a bad experience with a recent bought TV, he started questioning what was going wrong in the consumer electronics world. The answers he found, and shares with his audience, reveals the dramatic state of the current e-waste problem and the precarious working conditions of the mining industry.

Motivated by his findings and skillset as a software developer, he decides to roll up his sleeves and do a little experiment: a web app for his TV! With his app, William proves a point that great software performance increases gadget longevity thus reducing e-waste.

The presentation contains some slides for technically discussing fast 2D rendering techniques and some HTML 5 and JavaScript code.

## Speaker Bio

William is a full-stack software engineer at Volkswagen SDC: LX, Lisbon. In his career, he has worked with multiple technologies but his passion lies in the front-end implementing fast UIs in products with great UX. He has published a few mobile apps and used to have a crush on BlackBerry 10 and Flash. He has recently started the greatest role in his life: becoming a father.

## Links

- Blog: http://www.williamrjribeiro.com
- Company: http://vwds.pt
- GitHub: https://github.com/williamrjribeiro
- Photo: Speaker Image

## Extra Information

Hello! I've done this presentation once for a Landing.jobs Meetup in 2019 and got some really good feedback and response from the audience. I would love to share it with a bigger audience because I believe e-waste is a serious problem and that we developers can actually help reduce it by doing our job right. Since Pixels Camp will be full of geeks, I'll adjust my presentation to focus more on the geeky technical parts.

- https://www.meetup.com/landing_jobs/events/264495542/

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, thanks for the proposal.

Can you please fix the name of the `.md` file to follow the template? It's lacking proper separation between talk title and speaker name.

**Comment by carlosefr** [comment]
Nevermind, we removed the file name requirement on our side.

**Comment by carlosefr** [comment]
You proposal is still under review but, due to logistics constraints, we cannot guarantee any more stage slots at this moment. Until the **beginning of March** more slots are likely to become available and we will approve a few more proposals as we can, so this isn't a rejection notification.

We understand that delaying a decision reduces the time you have to prepare, shall your proposal turn out to be approved. So, if you need a decision from us until a particular date, please tell us by commenting here in this PR thread.

**Comment by williamrjribeiro** [comment]
Thanks for the update. Looking forward to the final decision 🤞

**Pull request closed without merging**
