### PR TITLE
Managing Dynamic Application State with react-applications

### PR DESCRIPTION
**Pull request by fabiosantoscode**
Managing Dynamic Application State with react-applications
=========================

* Speaker   : Fábio Santos
* Available : Any day
* Length    : 10-15 minutes
* Language  : English

Description
-----------

In this talk I go in-depth about how I built react-applications, and how you can use it for application state in dynamic or one-run apps.

Speaker Bio
-----------

I like building compilers. I'm also the main maintainer of Terser, a package that gets 1.6M downloads per week (and counting!). I love coding!

Links
-----

* Blog: http://frutal.pt
* Company: (Freelancer)
* GitHub: https://github.com/fabiosantoscode

Extra Information
-----------------

Nothing

### CODE REVIEW

**Comment by fabiosantoscode** [comment]
You haven't heard about this library. It's available here: https://github.com/fabiosantoscode/react-applications/

**Comment by edevil** [comment]
Hello @fabiosantoscode! Talks need to be 30 or 60 minutes long. Can you add more content to the talk to make it use one of these time slots?

Thank you.

**Comment by fabiosantoscode** [comment]
Yes I Can



:)

**Comment by fabiosantoscode** [comment]
Hello there. I'm retracting this talk as I've had negative feedback on the library in hacker news and r/programming. Maybe I'm just writing useless crap again

**Comment by fabiosantoscode** [comment]
Hello there. I'm retracting this talk as I've had negative feedback on the library in hacker news and r/programming. Maybe I'm just writing useless crap again

**Pull request closed without merging**
