### PR TITLE
Living on the Edge — Cloudflare Workers

### PR DESCRIPTION
**Pull request by adaptive**
Living on the Edge — Cloudflare Workers
=========================

* Speaker   : Hugo Romano
* Available : Anytime
* Length    : 45 minutes
* Language  : English

Description
-----------

Deploying serverless applications at the Edge (~165 [Cloudflare datacenters](https://www.cloudflare.com/network/)), that efficiently scale and are geographic agnostic, at little cost.

Introduction to [Cloudflare Workers](https://www.cloudflare.com/products/cloudflare-workers/) and architecture. Cloudflare Workers are modelled on the Service Workers API, internally they use V8 JavaScript engine. Also, the use of Workers KV, a global, low-latency, key-value data store.
Demonstration of in-production Workers for SMEs with lean business logic (payment processing, caching, user auth/sessions, logging, management bots, asset tracking IoT, web security).
Clear workflow with Terraform, providing a fast way to configure Cloudflare worker scripts and routes. 

Speaker Bio
-----------

Software developer since 1999, working for travel, health and defence industries. Contributor to Cloudflare Community. Also, the revenue manager of companies in travel and lodging, leveraged by machine learning. 

Links
-----
* GitHub: https://github.com/adaptive
* Twitter: [@adaptive](https://twitter.com/adaptive)
* Company: https://windbirds.co

Extra Information
-----------------
The demonstration comprises various use cases that are in production on diverse SMEs, but readily applicable to Corporate:
* payment processing
* cache control and management
* offloading origin server load with workers KV
* user auth/sessions with JWT
* unobtrusive logging at scale
* management bots for business automation
* asset tracking IoT
* web security with clientTrustScore

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi. Thanks for your proposal, but can you elaborate a bit on the talk description?

**Comment by carlosefr** [comment]
Would you consider extending the talk to 45/50 minutes + QA or do you prefer to stick with 30 minutes?

Also, can you please remove the formatting (italic) from the title?

**Comment by adaptive** [comment]
@carlosefr 45min + QA is possible. I shall edit accordingly and complete more info.

**Comment by adaptive** [comment]
`Moved to top comment`

**Comment by adaptive** [comment]
@carlosefr @edevil should I add 45min + 15 QA to the commit following my earlier comment.

**Pull request merged**
