### PR TITLE
From apple mvc to mvvm

### PR DESCRIPTION
**Pull request by jsaguiar**
# From Apple MVC to MVVM
- Speaker   : _João Aguiar_
- Available : _No restriction_
- Length    : _30 mins_
- Language  : _English_
## Description

Apple encourages every programmer to follow MVC pattern. When you do so, it's easy to end up with ViewController with more than 2000 lines, a lot of coupled and non-reusable code and also a lot of bugs. But:
- Is this best pattern that you should follow in your IOS applications?  
- Can you properly test an application that follows MVC?  
- Do you use dependency injection? What are the benefits of using it?  

In this presentation I will talk about the advantages of moving from MVC to MVVM pattern. I will compare both architectures and show how you can improve your code doing it, showing some  practical examples.

I will also talk about how you can improve your core using Reactive Programming and dependency injection.  

---
## Speaker Bio

Hi, my name is João Aguiar. I am a Software Engineer focused on mobile applications.  
Born in the mobile era and impressed by the capabilities of smartphones, I start learning how to develop applications for it, doing it for the last 5 years.  
## Links
- Company: https://uniplaces.com
- Github: https://github.com/jsaguiar

### CODE REVIEW

**Comment by LuRsT** [comment]
Hey @jsaguiar, could you please copy paste your commit into the PR description to make it easier for us to see it? Thanks!

**Comment by jsaguiar** [comment]
sorry @LuRsT. Its done.

**Comment by LuRsT** [comment]
No worries @jsaguiar, thanks!

**Comment by celso** [comment]
@jsaguiar check your email please

**Pull request merged**
