### PR TITLE
Ready, Set, Flutter

### PR DESCRIPTION
**Pull request by OldMetalmind**
Ready, Set, Flutter
=========================

* Speaker   : Filipe Barroso
* Available : Anytime
* Length    : 50 minutes
* Language  : English

Description
-----------

Flutter, the new Open Source mobile application SDK to create native applications with one codebase.

What is Flutter and why should you care about it? At the end of the talk, you will understand the decisions behind Flutter (looking at you Dart), why it is so different from others mobile development tools and platforms, and why is so many developers already are addicted.

It will be a talk from the heart, about the personal experience, and honest about pain and gain of working with Flutter.

Speaker Bio
-----------

Not an usual software developer, he loves getting out of the zone of comfort, if you don't see him at a tech event, his probably organizing the next tech event for Google Developer Group Lisbon, reading about psychology or supporting a community grow or start. Has a strong opinion about social impact, inclusivity and the importance of communities.

As a developer, he worked in android applications for companies such as Altice, Brisa, Federação Portuguesa Futebol, TAP, Bayer among many others and currently is working remotely as an Android Developer and Machine Learning Engineer.

His latest project is starting Flutter Portugal community.

Links
-----

* Company: https://www.acceptto.com/
* GitHub: https://github.com/OldMetalmind/

Extra Information
-----------------

I gave the first version of this talk at the event BarcampLx #1, (April 28, 2018) for 10 minutes long. However this talk was acceptted for TugaIt 2018 Summer Edition (July 19, 2018), and it was 45 minutes long. I have now adapted it for version 1.0 of Flutter and can give it in 30 minutes. 
[update 3Jan] I will give this talk and workshop at DevFest Porto 2018, (Jan 26, 2018)

Workshop - I also can give a Workshop about Flutter, if that is of your interest.

### CODE REVIEW

**Comment by carlosefr** [comment]
Would you consider extending the talk to 45/50 minutes + QA or do you prefer to stick with 30 minutes?

**Comment by OldMetalmind** [comment]
I can extend it to 50min + QA, there is a lot to talk about so this way I can into more details.

**Comment by carlosefr** [comment]
Can you please update the talk proposal with the new length? Thanks.

**Comment by OldMetalmind** [comment]
I have updated the talk proposal.

**Comment by OldMetalmind** [comment]
Made some corrections of English.

**Pull request merged**
