### PR TITLE
Machine Learning in the Wild - What they don't teach you in books

### PR DESCRIPTION
**Pull request by jaimerferreira**
Machine Learning in the Wild - What they don't teach you in books
========================

* Speaker   : [*Jaime Ferreira*]
* Available : [*Any Date*]
* Length    : [*30-45 minutes*]
* Language  : [*English*]

Description
-----------

In this talk you will learn why Machine Learning and Data Science are much more than algorithms. Out there, in real world industrial applications, it is a complex and intertwined mix of technology, domain constraints, intuition and team-work. Using real stories from Feedzai's experience fighting fraud in payments, we will illustrate why applying machine learning to live systems goes beyond using a dataset to train a predictive model. Technological issues such as scale, class balancing, concept drift, and data cleaning are a challenge to any data scientist, but they are only part of the story. In this talk, we will also show how non-technological issues can be so hard, and why good practices can have a tremendous impact on results.

---------------

Speaker Bio
-----------

Jaime Ferreira graduated in Information Systems and Computer Engineering in 2012 from Instituto Superior Técnico (IST), Lisbon. He finished his Masters Degree in Information Systems and Computer Engineering (IST) in 2015, with a thesis named "Incremental Learning of Probabilistic Models in High-Dimensional Space". During his education he has been associated with INESC-ID's Spoken Language Systems Lab (L²F), first as a trainee, and later as scholarship holder. From this association, he participated in some internal, national and European projects.

Currently, he is part of Feedzai's Research team, where he aims to develop new algorithms and adapt existing ones to the domain of fraud detection, keeping Feedzai the state-of-the-art leader in fraud detection.

Links
-----

* Company: https://feedzai.com

### CODE REVIEW

**Comment by carlosefr** [comment]
Please fill in the "Speaker Bio" section. Also, the "speaker" must be filled also.

**Comment by carlosefr** [comment]
You haven't updated the first comment, but I see that you updated the proposal markup file with a speaker that's not yourself.

Talks must be proposed by the speaker itself (which must also apply to the event). If the talk has two speakers, the second one must be identified by his/her GitHub username (and must also apply to the event).

If you're not the actual speaker for this talk, then he/she must do the proposal.

**Comment by carlosefr** [comment]
Now the only thing missing is editing the first comment. Otherwise our backoffice doesn't pick up your data.

**Comment by jaimerferreira** [comment]
Like this?

**Pull request merged**
