### PR TITLE
Redis Streams Messaging System

### PR DESCRIPTION
**Pull request by pedrofrazao**
Redis Streams Messaging System
========================

* Speaker   : Pedro Frazão
* Available : all event
* Length    : 45 minutes
* Language  : English

Description
-----------

Redis is an in-memory DB used in many production systems. Now, with version 5, it has a new data type - Streams.

This can be used as a message broker or as a job queue system. It isn't a replacement for mature solutions for these problems, but an easy and simple alternative.

This talk will include:
- brief description of the Redis
- some relevant data types in Redis (like pub/sub)
- streams data type
- consumer group
- my use case
- some performance considerations 

Speaker Bio
-----------

I'm using Redis since 2014 in production systems, with as an IPC, log aggregator, jobs system, cache to minimize disk I/O, etc.
Now, I'm redesigning the back office of a southbound interface (SBI) for network equipments using Redis Streams. :-)

Links
-----

* Redis Streams: https://redis.io/topics/streams-intro

* Blog: https://fuzzyrecall.wordpress.com/
* Github: http://github.com/pedrofrazao

Extra Information
-----------------

### CODE REVIEW

**Comment by carlosefr** [comment]
I've made some editing suggestions for typos and stuff directly in the PR description. Can you review and (if you agree) update the proposal?

**Review by pedrofrazao — COMMENTED** [review]
thanks

**Comment by carlosefr** [comment]
Please look at you PR, it's bringing in more changes than it should...

**Comment by pedrofrazao** [comment]
now it's fixed (too many remotes... sorry).

**Comment by carlosefr** [comment]
Ok, but the bits of broken english are still there. 😉

**Comment by pedrofrazao** [comment]
Write. But not anymore, I hope.

**Comment by carlosefr** [comment]
I'm sorry but our calendar is now full, which means your talk didn't make the cut this year.

**Pull request closed without merging**
