### PR TITLE
How to tell your friends that privacy is important

### PR DESCRIPTION
**Pull request by ruicruzpt**
How to tell your friends that privacy is important
========================

* Speaker   : Rui Cruz
* Available : all dates, all hours
* Length    : 30 minutos
* Language  : Portuguese

Description
-----------

Our friends, especially non-geeks, in most cases do not want to know about security in the digital age.
If we are going to talk about AES, Linux, data retention laws, VoIP, WebRTC and things like that, they just don't care. 

So it is best to speak things in simple terms and speak "normal Portuguese" with them: we talk about the same products, but with an interesting and different approach.

This talk aims to show some essential tools to your privacy and that of your friends. No complicated facilities. Out-of-the-box.
Maybe you know some products for it's tech specs, but you will learn to talk about this products in a more human way. :) 

Speaker Bio
-----------

I am the Director of Information of Tugaleaks, a media organization based in Portugal and inspired in Wikileaks. We are the only media organization that are in the CIA Factbook for Portugal. 
I am also an enthusiast of computer security and the only journalist in Portugal who stayed 299 days without Internet by court order in 2015.
Creator of Hackers Portugal.  

Links
-----

* Blog: https://www.ruicruz.pt
* Tugaleaks: https://www.tugaleaks.com
* Hackers Portugal: https://www.hackersportugal.com
* Social links: https://about.me/ruicruz

### CODE REVIEW

**Comment by carlosefr** [comment]
Even though it's OK for the talk to be in portuguese, the talk description should be in english, to match the communication language of the event and be universally readable in the event's schedule.

**Comment by ruicruzpt** [comment]
Edited @carlosefr  :)

**Comment by carlosefr** [comment]
👍, but the `.md` needs to be updated also.

**Comment by ruicruzpt** [comment]
I believe it's *all* done now :)

**Comment by carlosefr** [comment]
Almost... 😄

Check the name of the `.md` file.

**Comment by ruicruzpt** [comment]
It dhows up edited correctly for me: 
image

Do you want me to close/delete this pull and send a new one?

**Comment by ruicruzpt** [comment]
Renamed to how-to-tell-your-friends-that-privacy-is-important_rui-cruz.md 

Finaly ok? :)

**Comment by celso** [comment]
Rui, we'll turn this into a lightning talk ok? More info in the next days.

**Comment by ruicruzpt** [comment]
Sure. Thanks!

**Comment by ruicruzpt** [comment]
Hi @celso 
I've been thinking about this, and there is no way I can cover all the (I think) important information in 5 minutes.

I will submit another one in the next year.

Thanks for the opportunity anyway, I prefer to just be a "passive observer" on other talks. :) 

R.

**Pull request closed without merging**
