### PR TITLE
Women in DevOps

### PR DESCRIPTION
**Pull request by Crismr71**
Women in DevOps
=========================

* Speaker   : Cristina Moura Rebelo
* Available : DevOps Lisbon slot
* Length    : 30 minutes
* Language  : English

Description
-----------

DevOps is all about collaboration and collaboration is all about diversity. Empathy, attention to detail, and other tipically feminine characteristics are essential to accelerate progress and remove roadblocks, getting more innovative, productive teams.
DevOps has always embraced a diversity of thought and contribution. How to help bring alignment to teams, expanding into other functional teams across the organization.

Speaker Bio
-----------

With more than 10 years of experience in complex project management, Cristina is passionate for project management, especially using agile approaches as a means to optimize time and resources.Currently she manages a team of 20+ developing Meo TV. With a degree in Management, a graduation at Universidade Católica Portuguesa and two project management certifications, blogger and writer (including a book of poems and several professional articles), married and mother of two, she often participates as speaker/host in public interest events.

Links
-----

* GitHub: https://github.com/Crismr71

Extra Information
-----------------

Talk proposed by DevOps Lisbon. Delivered in DevOps Lisbon meetup (https://www.youtube.com/watch?v=0IJdJ5j3wHw) and AgilePT 2018.

### CODE REVIEW

**Comment by carlosefr** [comment]
Your proposal arrived past the deadline. This doesn't mean it's rejected, just that (when in doubt) other talks will get priority. It also means its approval (if it indeed happens) may happen much closer to the event.

The exception to this rule are talks that were already known to us by means other than GitHub.

Also, can you please reformat/rewrite your proposal? It must follow the template that we provided.
When you do that, please update the PR description as well. Thanks.

**Comment by Crismr71** [comment]
Done! thx (this is a DevOps Lisbon talk)

**Comment by saamorim** [comment]
Hi @carlosefr this is one of the three talks of DevOps Lisbon talk.

**Comment by carlosefr** [comment]
Hi, can you provide your LinkedIn profile address for the event calendar, or do you prefer we use your Pixels Camp profile?

**Comment by Crismr71** [comment]
Hi,
please use my linkedin profile: https://www.linkedin.com/in/crismr/
thanks!!

Carlos Rodrigues <notifications@github.com> escreveu no dia terça,
12/02/2019 à(s) 19:51:

**Pull request merged**
