### PR TITLE
How Programming Can Save A Biologist's Life

### PR DESCRIPTION
**Pull request by mooniean**
How Programming can save a Biologist's life
=========================

* Speaker   : Beatriz Costa Gomes
* Available : Anytime
* Length    : 45 mins + QA
* Language  : English

Description
-----------
One small script from a programmer can be a giant experiment for a biologist. In this talk, I'll try to convince you how bioinformatics, from the mostly theoretical mathematical models to the all-in-one software packages solutions, is the future.

Join me in this journey to expand the intersection between these fields and, who knows, maybe one day a programmer might be able to add “cure cancer” to their CV. 

Speaker Bio
-----------

After a Biomedical Engineering degree, with a specialisation in Bioinformatics and Clinical Informatics, I've continued my journey on the line between biology and computer science by pursuing a PhD in Computational Biology, hosted in a fully biological group. This allowed me to have an insight on the matter and on how life in Biology could be made much easier if each group collaborated with computer scientists and programmers.

Links
-----

* Blog: https://https://beainw0nderland.wordpress.com 
* GitHub: https://github.com/mooniean

Extra Information
-----------------

I've given several talks where I present my software to different types of audiences, from biologists to physicists and microscopists. I've found that everywhere I go, I'm asked whether there's more people like me, willing to go to a group and work with them. This is where I got the idea for this talk: talk to an audience that can actually help create the programmers army to tackle problems in other fields.

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi. Thanks for your proposal.

Can you rewrite/rearrange the talk description a bit, so that the first paragraph describes what you'll be presenting and the detailed context comes afterwards?

Only a few phrases will fit the calendar, and those few should be enough to get an idea of the talk without reading the full description.

**Comment by carlosefr** [comment]
Ok, you really removed a lot... 😄

Just a nitpick: please remove the markdown formatting from the proposal title. Thanks.

**Comment by mooniean** [comment]
Yes! Thought it had too much, so decided to cut down! But I can add it to the extra information bit :) Hope it's okay now!

**Comment by carlosefr** [comment]
The extra newline between the title and the `====` now makes our backoffice think the title is not a title. I've fixed the first comment, but can you fix the proposal? Sorry. :)

**Comment by carlosefr** [comment]
Ok, final question: do you want to stick with a 30 minutes length or would you consider extending it to 45m + QA?

**Comment by mooniean** [comment]
I definitely prefer the 45min+QA length! :) 

(chose 30 mins because I wasn't sure there would be an interest in a longer talk on this subject)

**Comment by carlosefr** [comment]
Ok. Update the proposal with that information and that's it. :)

**Comment by mooniean** [comment]
Hope it's okay now! :) Or this is gonna be the longest comment thread!

**Pull request merged**
