### PR TITLE
Building a mobile decentralised game using JS

### PR DESCRIPTION
**Pull request by pgte**
Building a mobile decentralised game using JS
=================================================

* Speaker   : Pedro Teixeira
* Available : any day
* Length    : 45 minutes + QA
* Language  : English

Description
-----------

In 30 minutes, Pedro will present all the techniques and challenges he had to overcome to build a turn-based decentralised local-first mobile game using little more than JavaScript and some coffee.

Speaker Bio
-----------

A Software Engineer with over 20 years of experience and a rooted curiosity about distributed systems. Loves JavaScript. Author of some open-source, the Node Tuts screencast show and several books and conferences about Node.js.

Links
-----

* Blog: https://metaduck.com
* GitHub: https://github.com/pgte
* Photo: https://avatars2.githubusercontent.com/u/47910?s=460&v=4

Extra Information
-----------------

* I delivered [a talk at the 2016 Pixelscamp](https://avatars2.githubusercontent.com/u/47910?s=460&v=4).
* During 2017 through 2019 I headed research on decentralised data types (CRDTs) while working for Protocol Labs and the IPFS project.

### CODE REVIEW

**Comment by carlosefr** [comment]
Will you consider extending your talk to 45 minutes + QA? Slots are always 1 hour long ans we'd rather minimize stage downtime.

If so, please update your `.md` file and the PR description above.

**Comment by pgte** [comment]
@carlosefr Of course! Done.

**Comment by carlosefr** [comment]
Congratulations @pgte, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
We're considering this talk as sponsored by the **Madeira Tech** meetup.

**Comment by pgte** [comment]
@carlosefr Unfortunately, for professional and personal reasons I'll not be able to do the work required for me to prepare everything I need to be able to deliver this talk properly.
I'd rather say this early so that you have the time to find a replacement.
I'm really sorry for the inconvenience!

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
