### PR TITLE
A Multiplatform triathlon: Kotlin through Android, iOS and Web

### PR DESCRIPTION
**Pull request by cmota**
A Multiplatform triathlon: Kotlin through Android, iOS and Web
=========================

* Speaker   : Carlos Mota
* Available : All days
* Length    : 45 minutes
* Language  : English

Description
-----------

For several years now, that we’ve been trying to find new solutions on how we could develop a single project and run it on all platforms. We’ve been seeing all types of solutions: some are web-based, others require you to learn a new language, and others even may require that you pay a monthly fee to use. It also comes with the drawback that all your UI depends on the framework implementation. So, if there’s a native update you’ll need to wait until someone rewrites the widgets for you to update your app.

Kotlin multiplatform gives us a new solution. It focuses on sharing your business logic across all platforms, leaving the UI to be implemented natively. Since it’s Kotlin, you can take full advantage of its language features - concise, safe, etc. Moreover, if you’re coming from android you might already be familiarised with Kotlin and even if you’re an iOS developer you’ll see that it’s quite similar to Swift.

Join me on this triathlon and let’s go through Android, iOS, and Web in under 45 minutes.

Speaker Bio
-----------

Android tech lead at WIT Software, he can easily be spotted there working on the company RCS solution. An enthusiastic for new technology and always trying to reach those last 20% of all of his side projects that seem to be really far away, he loves to share his knowledge with others either by giving talks, teaching, writing or along with a cold beer in the nearest pub. GDG Coimbra organizer and Kotlin evangelist, he also has a huge passion for travel, photography, space and the occasional run.

Links
-----

* Blog: https://medium.com/@cafonsomota
* Company: https://www.wit-software.com/
* GitHub: https://github.com/cmota/

Extra Information
-----------------

I've had the chance to present some talks before, here you can find:
👉 The slides of some of these talks: https://speakerdeck.com/cmota
👉Perception Of Speed (YouTube): https://www.youtube.com/watch?v=Rc_rXl4C_A0&list=PLTlIsr2wnuwWTG27Ifw9XW7ql41mayA7i
👉Kotlin My Way In (YouTube): https://www.youtube.com/watch?v=TvoDRnwMGYQ&list=PLFZ9q4L_xKcZoOWoOnIpfmPVriz2pZi-e&index=11

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi,

The `.md` file states 30 minutes as the talk length, but the PR description states 30 minutes. Can you please correct one of them?

**Comment by cmota** [comment]
Hello @carlosefr 👋,

Oops, I'd forgot to update the PR description - all done 🙂

**Comment by carlosefr** [comment]
We would have preferred 45 minutes to reduce stage downtime (all slots are 1 hour long), but that's OK.

**Comment by cmota** [comment]
Oh! Since the example was 30 mins and 1 hour I thought that there was no 45 mins slot. 

In that case I'll update everything for 45-50 mins, no worries 🙂

**Comment by carlosefr** [comment]
The slots are 1 hour: 45 minutes + QA. :)

**Comment by carlosefr** [comment]
You proposal is still under review but, due to logistics constraints, we cannot guarantee any more stage slots at this moment. Until the **beginning of March** more slots are likely to become available and we will approve a few more proposals as we can, so this isn't a rejection notification.

We understand that delaying a decision reduces the time you have to prepare, shall your proposal turn out to be approved. So, if you need a decision from us until a particular date, please tell us by commenting here in this PR thread.

**Comment by cmota** [comment]
Thank you for the feedback @carlosefr! I'll wait until the beginning of March 🤞🙂

**Comment by carlosefr** [comment]
Congratulations @cmota, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

We're also considering this talk as sponsored by the **Kotlin Knights** meetup.

**Comment by cmota** [comment]
Awesome!! Thanks @carlosefr 🙂🙌

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request closed without merging**
