### PR TITLE
Redux best practices

### PR DESCRIPTION
**Pull request by sergioramos**
# Redux best practices
- Speaker   : Sérgio Ramos
- Available : October 6th-8th
- Length    : 30m
- Language  : English
## Description

Redux is a simple abstraction, but it can also be overwhelming in the beginning.

There is an infinite amount of ways to structure your code, how to model your state and what plugins to use.

Redux doesn't impose any of those, but having good practices goes a long way to save you in the future.

We're going to go through:
- Ecosystem
- Code Structure
- Data modeling

---
## Speaker Bio

I'm a fullstack developer that loves open-source and is fascinated with distributed systems, databases and tooling. Have worked both in the startup and in the enterprise world, in the social, fashion, travel and retail industries.
## Links
- Company: https://www.yld.io
- Github: https://github.com/ramitos
- Twitter: https://twitter.com/ramitos

### CODE REVIEW

**Comment by celso** [comment]
@ramitos check your email please

**Comment by celso** [comment]
@ramitos your pull request is trying to delete the talk template, can you fix it? thanks

**Comment by sergioramos** [comment]
@celso 

replied to the email, thanks for the alert.

yes, I'll fix that right away ;)

**Comment by sergioramos** [comment]
done

**Pull request merged**
