### PR TITLE
webauthn: a better alternative for securing webapps

### PR DESCRIPTION
**Pull request by pmlopes**
webauthn: a better alternative for securing webapps
=================================================

* Speaker   : Paulo Lopes
* Available : Any
* Length    : 60 min
* Language  : English

Description
-----------

Our online existence relies on an outdated and fragile idea of passwords. The password is what lies between a malicious user and your bank account or social media accounts. Passwords are hard to maintain; it's hard to store them on the server (passwords get stolen). They're hard to memorize, or not tell to others (phishing attacks).

But there's a better way! A passwordless world, and it just became a standard by W3C and FIDO on your browser.

An API that allows servers to register and authenticate users using public-key cryptography instead of a password, an API that uses cryptography in a user-accessible way.

This presentation is the result of the learning experiences done by implementing Webauthn for vert.x, a polyglot reactive toolkit.

In a tutorial format, you will learn what FIDO, FIDO2, U2F, CTAP, CTAP2, Webauthn is, how to create a secure web application that will work on your laptop or mobile device or security tokens. You will learn how to perform the server attestations and make secure phishing free applications. 

Speaker Bio
-----------

I'm Paulo and I've used my 10+ years of software development experience writing, rewriting, banging my head against the wall, editing and re-editing high-performance web application to make Vert.x an even more awesome framework. I am also the author of "ES4X" the fastest JavaScript server runtime and other small open source projects. This is more than a job; I'm on a mission to build fast and faster applications!

Links
-----

* Twitter: https://twitter.com/pml0pes
* Blog: http://www.jetdrone.xyz
* Company: http://redhat.com
* Github: http://github.com/pmlopes
* Photo: https://avatars3.githubusercontent.com/u/849467

Extra Information
-----------------

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, just a quick question: is this proposal intended to be a regular talk or a workshop?

**Comment by pmlopes** [comment]
Hi @carlosefr, the intention is to be a talk. Since the content is not just about an API but about, the browser spec, authenticators and server validations. As such i find it easier to explain how it all works together with lots of examples (which I referred to as tutorial like format).

Let me know if this is clear!

Cheers!

**Comment by carlosefr** [comment]
Congratulations @pmlopes, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling worflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
