### PR TITLE
Quantiles over Percentiles: When and How

### PR DESCRIPTION
**Pull request by jracabado**
Quantiles over Percentiles: When and How
=========================

* Speaker   : João Acabado
* Available : March 23, 9am-7pm
* Length    : 20 minutes
* Language  : English

Description
-----------

When performance matters there should be a clear and easy way of setting service level expectations. The way you measure latency determines how can we define our objectives.
Let's brush up your statistics, Quantiles and Percentiles helps us define performance objectives and indicators and have everyone on the same page whenever our services get too slow.

Speaker Bio
-----------

Resilience Engineering Manager @ Sky Portugal

Always looking for the easiest hard problem that can be solved. Have been looking to bridge the delivery of software solutions with their operation in the past couple years.  

Links
-----

* Company: Sky Technology Centre - Portugal
* GitHub: https://github.com/jracabado

Extra Information
-----------------

This will be an extension to the talk on the Lx DevOps lighting talks at BrightPixel: [LxDevops: Quantiles over Percentiles](https://www.youtube.com/watch?v=zBQtgtCOD3Q)

### CODE REVIEW

**Comment by saamorim** [comment]
Hi @carlosefr this is one of the three talks of DevOps Lisbon slot.

**Comment by carlosefr** [comment]
Hi, can you provide your LinkedIn profile address for the event calendar, or do you prefer we use your Pixels Camp profile?

**Comment by carlosefr** [comment]
Hi, we also need a picture of you for https://pixels.camp/speakers/

**Comment by jracabado** [comment]
Sorry for the late reply @carlosefr, I've got to find a different filter for my Github notifications :), I've added the LinkedIn profile link and the photo.

**Pull request merged**
