### PR TITLE
React Hooks broke my tests, now what?

### PR DESCRIPTION
**Pull request by danieljcafonso**
React Hooks broke my tests, now what?
=================================================

* Speaker   : Daniel Afonso
* Available : Any day
* Length    : 45 minutes + QA
* Language  : English

Description
-----------

Hooks have become a better and cleaner way to write React code. Many are now realizing it and starting to migrate their solutions from class to functional components. When the code looks great, and the migration seems successful, your tests may disagree.
This presentation focuses on the common pitfalls of testing and what we have been doing wrong while also teaching you how to test your brand new hooks, all this while using the React Testing Library.

Speaker Bio
-----------

Daniel is a Software Engineer at Talkdesk. His current interest is in React and JavaScript, and he advocates for better testing principles using the testing library. He has a full-stack background, having worked on different languages and frameworks on various projects from IoT to Fraud Detection. In his free time, when he's not learning new technologies or writing about them, he's probably reading comics or watching superhero movies and shows.

Links
-----

* Blog: https://medium.com/@danieljcafonso
* Company: http://talkdesk.com/
* GitHub: https://github.com/danieljcafonso
* Photo: https://drive.google.com/open?id=1_Ljgj2e_Yrx5ZkrBcALMVI3yLrZCfEOc

Extra Information
-----------------

I’ve been advocating for better testing practices using the Testing Library and am one of its contributors. After spending months of refactoring implementation details focused tests, I’ve grown to understand the main pain points of testing React components and helped my team to build new practices and write better performant and resistant tests.

### CODE REVIEW

**Comment by carlosefr** [comment]
Would you consider extending your talk to 45 minutes + QA to avoid stage downtime? (All slots are 1 hour long).

**Comment by danieljcafonso** [comment]
@carlosefr sure, I can extend it!

**Comment by danieljcafonso** [comment]
Changed the duration on the file and on the description :+1:

**Comment by meddulla** [comment]
Congratulations @danieljcafonso, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
