### PR TITLE
Adaptive Image Loading for Best Performance

### PR DESCRIPTION
**Pull request by tpiros**
Adaptive Image Loading for Best Performance
=========================

* Speaker   : Tamas Piros
* Available : anytime
* Length    : 1 hour
* Language  : English

Description
-----------

The web has seen incredible growth over the past decade - an increase that enabled remarkable technological advancement. There are developer tools and frameworks out there that can do magical things and unfortunately, therein lies the problem. With this explosion of new tools as well as myriad device types, we are faced with another problem - performance.
In the era of JavaScript frameworks, there is an ever increasing number of resources that a website requires. When one stops to think about it, these days we need multiple JavaScript files, CSS files and other resources, as well as media assets such as images and videos.
Creating a website that performs well is a constant challenge as there are many factors to take into consideration such as the connection speed of the user and the capabilities of the device used to access the site.
Asset management is always an important factor in web applications, primarily because recent years have seen an increase in visually appealing websites. More images are added to websites, but this comes with an undesired effect - often leading to slower load times.
There are web applications that could lose profit if images do not load fast enough - think about e-commerce websites. The profitability of such sites depends on garnering a reasonable conversion rate. A few seconds in delay when loading product information could cause a potential buyer to leave the site prematurely.
During the talk we'll discuss how to achieve well performing website without the penalty of loosing a visual experience.

Speaker Bio
-----------

Tamas is a Developer Evangelist and experienced Technical Trainer. He has delivered successful training classes, workshops as well as presentations worldwide at prestigious conferences and workshops.

Links
-----

* Blog: https://fullstack-developer.academy
* Company: [Full Stack Training Ltd](https://www.fullstacktraining.com/)
* GitHub: https://github.com/tpiros

Extra Information
-----------------

During the talk we'll discuss:
- Web Performance in general as well as its relation to media used on websites
- Service Workers
- Network Information API
- The Save-Data header

### CODE REVIEW

**Comment by carlosefr** [comment]
Would you consider extending the talk to 45/50 minutes + QA or do you prefer to stick with 30 minutes?

**Comment by tpiros** [comment]
@carlosefr I'd prefer 30 mins + QA. Can you let me know the driver behind a longer talk please?

**Comment by carlosefr** [comment]
The slots are 60 minutes long (including time to switch speakers). Shorter talks are harder to schedule / may create holes in stage lineups. But it's fine if you prefer to stick with 30 minutes.

**Comment by tpiros** [comment]
At the moment my talk is roughly 30 mins + QA but if required I can extend it with some additional things but I'd like this as a last resort :) when do confirm the acceptance of the talks?

**Comment by tpiros** [comment]
Updated to offer alternative workshop proposal.

**Comment by carlosefr** [comment]
This is being pre-accepted as a workshop.

**Comment by carlosefr** [comment]
Can you please update the workshop length in both the proposal and the PR description?

**Comment by tpiros** [comment]
Sure. What's the max length available?

**Comment by carlosefr** [comment]
1h recommended, 2h if it really needs it.

**Comment by tpiros** [comment]
okay. 1 hour is possible, providing the fact that the workshop attendees have the necessary knowledge. In this case I can just cover the basics at a high level, without having to go into detail.

**Comment by tpiros** [comment]
Do you have a date in mind already for the workshops or will they be mixed with talks?

**Comment by carlosefr** [comment]
The workshops have their own stage (or room) available for the whole three days.

**Comment by tpiros** [comment]
Perfect @carlosefr - once you have the exact day for this workshop please let me know 🙏🏼

**Comment by carlosefr** [comment]
You should be receiving an email soon. Related to your question, the important bit is that the schedule is dynamic, and may change up until very close to the event.

**Comment by celso** [comment]
Hi @tpiros , you need to apply as a participant so that we can move forward with your talk approval process. Link here: https://pixels.camp/apply/

**Comment by tpiros** [comment]
@celso this is now done. thank you.

**Pull request merged**
