### PR TITLE
Twitter Bot Hunting

### PR DESCRIPTION
**Pull request by msramalho**
Twitter Bot Hunting
=================================================

* Speaker   : **Miguel Sozinho Ramalho**
* Available : **first day, second day, third day**
* Length    : **45min**
* Language  : **English, Portuguese**

Description
-----------

_Disclaimer: no guns will be used during the talk._

What are Twitter bots? What are they used for? What techniques can be used to find them? Hopefully, you will be able to answer these and some other questions by the end of the talk.

I will cover techniques for bulk data collection from Twitter and go over the process of building a classifier for detecting bots, with a focus on the immensity of features that can be extracted for this purpose. 

If  buzzwords are your thing, here are some: machine learning, sentiment analysis, word embeddings, social network analysis, Twitter API. 

Speaker Bio
-----------

 

Final year MSc Student of [Computer|Software][Engineering|Science] @FEUP currently working on a thesis entitled:

`Political Interference Detection, Analysis and Impact Measurement on Twitter` 

Links
-----

* Homepage: [msramalho.github.io](https://msramalho.github.io/)
* GitHub: [@msramalho](https://github.com/msramalho)
* Photo: [here](https://avatars1.githubusercontent.com/u/19508417?s=460&v=4)

Extra Information
-----------------

I gave a [talk](https://github.com/PixelsCamp/talks/blob/master/2019/quantum-supremacy_miguel-sozinho_ramalho.md) on PixelsCamp v3.

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, can you please remove the italic markup from the talk title?

Also, would you consider extending your talk to 45 minutes to minimize stage downtime?

**Comment by msramalho** [comment]
Done @carlosefr, 45min is actually better.

**Comment by meddulla** [comment]
Congratulations @msramalho, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
