### PR TITLE
What the Service Mesh?!

### PR DESCRIPTION
**Pull request by mccricardo**
What the Service Mesh?!
=================================================

* Speaker   : Ricardo Castro
* Available : All days
* Length    : 60min
* Language  : English

Description
-----------

Cloud platforms provide a wealth of benefits for the organizations that use them. There’s no denying, however, that adopting the cloud can put strains on DevOps teams. Developers must use microservices to architect for portability, meanwhile operators are managing extremely large hybrid and multi-cloud deployments.

A service mesh is a dedicated infrastructure layer for making service-to-service communication safe, fast, and reliable. If you’re building a cloud native application, you need a service mesh. It can help connect, secure, control, and observe services. At a high level, a service mesh helps reduce the complexity of these deployments, and ease the strain on your development teams.

This talk will start by introducing what a service mesh is and what are it’s main concepts. It will then deep dive into a service mesh implementation, Istio, introducing it’s main concepts, architecture as well as demoing it’s use in conceptual “real” scenario. Concepts like Traffic Control (Canary Deployments, Dark Launches, Egress), Service Resilience (Load Balancing, Timeouts, Retries, Circuit Breaking, Pool Ejection), Chaos Testing (HTTP Errors, Delays), Observability (Tracing, Metrics), and Security (Blacklist, Whitelist) will be explored in this talk.

Speaker Bio
-----------

Senior Engineer at Veniam building highly performance, reliable and scalable systems. Strong believer in culture and teamwork. Open source passionate, taekwondo amateur and metal lover.

Links
-----

* Blog: http://mccricardo.github.io/
* Company: https://veniam.com
* GitHub: https://github.com/mccricardo
* Photo: https://avatars0.githubusercontent.com/u/1016505?s=460&v=4

Extra Information
-----------------

None.

### CODE REVIEW

**Comment by mccricardo** [comment]
This can easily be extended to a longer format (e.g. 45/60min)

**Comment by carlosefr** [comment]
If you intend to extend it for a full-length talk, please modify both the `.md` file as well as the PR description above.

**Comment by mccricardo** [comment]
Done.

**Comment by carlosefr** [comment]
Congratulations @mccricardo, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling worflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by mccricardo** [comment]
Great news. Thank you so much for the feedback @carlosefr .

**Comment by carlosefr** [comment]
We're considering this talk as sponsored by the **DevOps Porto** meetup.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
