### PR TITLE
Testing the Frontend with testing-library

### PR DESCRIPTION
**Pull request by goblindegook**
Testing the Frontend with testing-library
=========================================

* Speaker   : Luís Rodrigues
* Available : Any
* Length    : 45 minutes
* Language  : English

Description
-----------

Frontend test automation seems hard but it’s only as hard as you make it. Are you bogged down by endless component tests and still not sure your application won’t break? I talk about the advantages of testing your frontend from the perspective of the people using it, and bust some myths about unit testing and the supposed convenience of shallow component rendering.

Speaker Bio
-----------

I'm a software engineer at Equal Experts.

Links
-----

* Blog: https://goblindegook.com/
* Company: https://equalexperts.com/
* GitHub: https://github.com/goblindegook
* Photo: https://raw.githubusercontent.com/PixelsCamp/talks/master/img/luis_rodrigues_2.jpg

Extra Information
-----------------

* Previous talks: https://goblindegook.com/talks/

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi. Thanks for the talk proposal.

Can you be a little more descriptive in the talk's title, please? We like short titles, but this one is perhaps a bit too short and doesn't seem to reflect the talk's description. :)

**Comment by carlosefr** [comment]
Would you consider extending your talk to 45 minutes + QA to avoid stage downtime? (All slots are 1 hour long).

**Comment by goblindegook** [comment]
Sure thing.

**Comment by carlosefr** [comment]
You proposal is still under review but, due to logistics constraints, we cannot guarantee any more stage slots at this moment. Until the **beginning of March** more slots are likely to become available and we will approve a few more proposals as we can, so this isn't a rejection notification.

We understand that delaying a decision reduces the time you have to prepare, shall your proposal turn out to be approved. So, if you need a decision from us until a particular date, please tell us by commenting here in this PR thread.

**Comment by goblindegook** [comment]
No rush, I don't need time to prepare for this talk, it's not my first time delivering it.

**Pull request closed without merging**
