### PR TITLE
Testing practices for mobile

### PR DESCRIPTION
**Pull request by dougritter**
Testing Practices for Mobile 
=================================================

* Speaker   : **Douglas Ritter** 
* Available : **second day**
* Length    : **45 minutes**
* Language  : **English**

Description
-----------

Quality is always important, but sometimes we don't know how to start or how to move to the next level. In an agnostic approach, I will share some practices we developed at Talkdesk's Mobile Team in order to effectively ensure the quality of the products we make, enabling us to improve the delivery speed.

The talk will cover what we as a team consider important steps in the software development, since the backlog refinement, passing by technical discussions, the development itself and verification phases. We will discuss how to split work in small units convering all the scenarios needed to deliver a feature. Also, some important guidelines to follow when writing tests in a team and how to better cover the test pyramid with different types of automated tests.

Speaker Bio
-----------

Software engineer.
TDD practitioner working at Talkdesk. 
Almost 9 years writing iOS and Android apps and SDKs.

Links
-----

* Blog: https://medium.com/@dougritter
* Company: https://talkdesk.com
* GitHub: https://github.com/dougritter 
* Photo: https://avatars2.githubusercontent.com/u/6066883?s=460&v=4 

Extra Information
-----------------

The talk will cover topics like:
- How define scenarios with BDD
- Naming tests
- Reduce uncertainty with tech approaches
- Dependency injection in tests
- How to use test doubles
- Tests structure with "Arrange, Act, Assert" approach
- Different kinds of tests to better cover the test pyramid

I've already published an article on this topic: https://engineering.talkdesk.com/mobile-testing-practices-811e46a4b893

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi. Thanks for the talk proposal.

We have a couple of questions/suggestions:

* Can you please remove the formatting markup (italic) from the talk title?
* Also, can you please be more specific about the contents of the talk? The talk description it's a bit too abstract. Since it's the bit that goes into the schedule, it should provide enough information by itself to attract the audience.

**Comment by dougritter** [comment]
Hi, @carlosefr 
Thanks for the feedback. 
I've made the changes. Added some topics to Extra information and to description.
The article I linked (which I wrote) also has many of them more detailed.

**Comment by carlosefr** [comment]
Hi, would you consider extending your talk to 45 minutes + QA or do you prefer to stick with 30 minutes? Slots are 1h long and we prefer to minimize downtime, if possible.

You can choose either way, this is not mandatory.

If so, please update your `.md` file and the PR description above.

**Comment by dougritter** [comment]
Hi, @carlosefr 
I've changed the length from 30min to 45min.
Thanks!

**Comment by carlosefr** [comment]
Congratulations @dougritter , your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
