### PR TITLE
Machine Learning at the Edge

### PR DESCRIPTION
**Pull request by claudiotx**
# Machine Learning at the Edge

- Speaker : Claudio Teixeira
- Available : first day, second day, third day
- Length : 45
- Language : English

## Description

In a lot of situations we can't afford to call an API to interpret our payload on a Machine Learning model due to performance (real-time), connectivity and privacy concerns, so that we need to run ML on the edge devices (IoT, Browser, Smartphones). These constraints open a path to a new way of creating and running ML Models. I will be presenting some present and future use cases followed by a (quick && easy) demo which any developer can follow along an we will be training and running a realtime ML model on our browsers, completly isolated from any service or API.

## Speaker Bio

Claudio Teixeira is a Senior Software Engineer with 7 years of experience in the industry where he has worked as Researcher, Full Stack Developer, Tech Lead, Team Manager and CTO in several companies from 5 up to 50 employees across several industries like Finance, Online Gambling, Online Casinos, Advertisement, Software as a Service (SaaS) tools within others) and IoT between Lisbon and London.

## Links

- Blog: www.coderecipes.org
- Company: Altar.io
- GitHub: github.com/claudiotx
- Photo: https://altar-meetups.s3.us-east-2.amazonaws.com/claudio-profile-pic.png

## Extra Information

Former member of the Standby Task Force
Former member of London JavaScript Community (Meetup.org)
Speaker and Admin of Frontend Lisbon JavaScript Community (Meetup.org)
Blog Writer (coderecipes.org)

### CODE REVIEW

**Comment by carlosefr** [comment]
Would you consider extending your talk to 45 minutes + QA to avoid stage downtime? (All slots are 1 hour long).

**Comment by claudiotx** [comment]
Actually it's prepared to 45min as a big part of it, is a step by step live coding demo. Thanks

**Comment by carlosefr** [comment]
Can you update the PR description and the `.md` file please?

**Comment by claudiotx** [comment]
@carlosefr Updated description and the time windows

**Comment by carlosefr** [comment]
Can you please fix the markup in the `.md` file to match the template? (Your latest changes "broke" it.)

**Comment by claudiotx** [comment]
@carlosefr Apologies, my bad.. prettier was not liking the template :D

**Comment by carlosefr** [comment]
@claudiotx I'm not finding you in the Pixels Camp database. Please note that speakers **must** also apply and be approved as attendees.

**Comment by claudiotx** [comment]
Hello @carlosefr .
I thought I had applied. Sorry for that.
I've applied now. 
PS: I was in the last PixelsCamp and also participated in the hackaton

**Comment by carlosefr** [comment]
I've confirmed it so, congratulations @claudiotx, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
