### PR TITLE
1001 Reasons to use Python

### PR DESCRIPTION
**Pull request by LuRsT**
1001 Reasons to use Python
==========================

* Speaker: Gil Gonçalves
* Available: September 28th or 29th - no time restrictions
* Length: 30min
* Language: English

Description
-----------

In this talk I'll showcase awesome things about the Python programming language
and hopefully convince you on why you should use it.

I will go through the pros and cons of using Python, talk a bit about it's
history, compare it against other languages and talk about it's wonderful
community.

This talk is for every developer looking for a new language to learn, for ways
to convince their boss to use Python, or even for hobbyists looking for easy
ways of solving their problems.

Questions that will be answered in this talk:

- Should I learn Python?
- Should my company use Python for X project?
- What can I use Python for?
- Is Python old and boring?

I will bring stickers!

---------------

Speaker Bio
-----------

Software developer writing services in London. Lives in the terminal, doesn't
know anyone called GUI.

Some bullet points about my commitment to Python:
- ~5 years of professional Python experience
- Europython Board Member
- Contributing member of PSF (Python Software Foundation)
- Creator of Python Users Lisbon Meetup
- Ex-organizer of Oxford Python Meetup

Links
-----

* Company: http://made.com
* Github: http://github.com/lurst

### CODE REVIEW

**Comment by celso** [comment]
Hi @LuRsT, thanks for your proposal. The topic is interesting but we're going to need slightly better description for your talk though. Can you read "Make makes a good proposal?" and reevaluate your pitch?

https://github.com/PixelsCamp/talks

**Comment by celso** [comment]
Ping @LuRsT ?

**Comment by LuRsT** [comment]
@celso Sorry, was on Holiday, will do that!

**Comment by LuRsT** [comment]
@celso Sorry, was on Holiday, will do that!

**Comment by LuRsT** [comment]
@celso, I updated the talk description, let me know if it's enough.

**Pull request merged**
