### PR TITLE
Embracing Elixir: An Adoption Story

### PR DESCRIPTION
**Pull request by dcaixinha**
Embracing Elixir: An Adoption Story
=========================

* Speaker   : Daniel Caixinha
* Available : First and second days, 9am to 7pm
* Length    : 45min + QA
* Language  : English

Description
-----------

Elixir, the language with Ruby-like syntax that runs on the Erlang VM, is known for its ability to build highly scalable and resilient applications. It's rapidly growing and capturing the interest of more and more developers. Yet, most of the people interested in Elixir aren't using it in their jobs.

In this talk, Daniel Caixinha will explore some ways of changing this reality. Merging his experience at Onfido with the knowledge from the "Adopting Elixir" book, he'll go through several aspects for building a business case to adopt Elixir. Most of the lessons learned in this journey are general, so they can be applied on most technology adoptions.

Speaker Bio
-----------

Daniel Caixinha, co-author of the book "Mastering Elixir", is a software engineer at Onfido, where he is using Elixir to build resilient systems that can also handle the high growth of the business. After graduating from Instituto Superior Técnico, he joined the startup world, mainly using Ruby, but he also got the chance to play around with Elixir. Upon joining Onfido, he got the chance to take Elixir more seriously, which made him fall in love with functional programming in general, and Elixir in particular. Besides building Elixir applications, he is fostering the use of Elixir, being a co-organiser of the Lisbon Elixir meetup.

Links
-----

* GitHub: https://github.com/dcaixinha
* Blog: https://medium.com/@dcaixinha
* Book: https://www.packtpub.com/application-development/mastering-elixir

Extra Information
-----------------

[Previous Talk on the Lisbon Elixir meetup](https://www.youtube.com/watch?v=J9KG_XqaVKQ)

### CODE REVIEW

**Comment by carlosefr** [comment]
Like mentioned in the submission rules, the audience at Pixels Camp tends to be very sensitive to talks that may look like sales pitches. From the description, that's not what it looks like, but I'd sugest a subtle change to the title to avoid that connotation if you agree: "Embracing Elixir: An Adoption Story at Onfido".

**Comment by dcaixinha** [comment]
Thanks for the feedback @carlosefr. That wasn't my intention at all. I don't have any strong feelings regarding that – I'll just drop the mention from the title entirely.

**Comment by dcaixinha** [comment]
Done. Let me know what you think @carlosefr.

**Comment by dcaixinha** [comment]
Hey @carlosefr, I've updated the description, as I forgot to mention the book I co-authored :sweat_smile:  Thanks!

**Comment by dcaixinha** [comment]
Hey guys (@carlosefr @celso), one question: should I also apply in the main pixels.camp website?

**Pull request merged**
