### PR TITLE
Do I know you? Identity on the Internet and the Question of Trust

### PR DESCRIPTION
**Pull request by kevingoldsmith**
Do I know you? Identity on the Internet and the Question of Trust
=================================================

* Speaker   : Kevin Goldsmith
* Available : first day
* Length    : 45
* Language  : English

Description
-----------

Identity online continues to evolve; governments, businesses, the open-source community, and grassroots organizations are all evolving how we validate, protect, and secure our identity. Whether your software is targeted towards companies or consumers, how you ethically manage customer identity will be crucial to your product’s success (or existence).

In this talk, I cover the evolution of identity of the internet, from a product development perspective. I talk about the things you should be aware of when building software today, and the things you should pay attention to for the future.

Speaker Bio
-----------

Kevin Goldsmith has been a developer, software architect, technology manager, and senior technology executive for over 27 years. He is currently the Chief Technology Officer at Onfido in London, a machine learning and computer vision company helping users own their identities on the internet. Formerly, Kevin was the Chief Technology Officer at Avvo; the Vice President of Engineering, Consumer at Spotify; a Director of Engineering at Adobe Systems; and, development lead at Microsoft.

Links
-----

* Blog: https://kevingoldsmith.com/writing.html
* Company: https://onfido.com
* GitHub: https://github.com/kevingoldsmith
* Photo: https://www.kevingoldsmith.com/talks/KevinGoldsmithSpeakerPhoto.jpg

Extra Information
-----------------

See https://www.kevingoldsmith.com/talks/ for other talks, talk recordings and slides from all my talks.

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, thanks for your talk proposal.

Can you abbreviate the talk description somewhat? The contextualization is a bit long.

I also suggest moving the last paragraph to the beginning, so that readers can know as quickly as possible what the talk is about (also the schedule has limited space).

**Comment by carlosefr** [comment]
Would you consider extending your talk to 45 minutes + QA to avoid stage downtime? (All slots are 1 hour long).

**Comment by kevingoldsmith** [comment]
No problem, I can totally do that.

**Comment by carlosefr** [comment]
Great. Can you update the PR description above, as well as the `.md` file please?

**Comment by carlosefr** [comment]
Congratulations @kevingoldsmith , your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by kevingoldsmith** [comment]
great news!

**Comment by kevingoldsmith** [comment]
updated days

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
