### PR TITLE
The State of NoSQL in 2020

### PR DESCRIPTION
**Pull request by deniswsrosa**
The State of NoSQL in 2020
=================================================

* Speaker   : **Denis Rosa**
* Available : **first day, second day, third day** 
* Length    : **45**
* Language  : **English or Portuguese** (pt-BR)

Description
-----------

NoSQL is a broad term applied to more than 200 non-relational databases out there according to DBEngine, which makes it impossible for most developers to keep up-to-date with the latest innovations in this area. In this session, you will get a quick review of NoSQL database architectures, which new features that really matters for your daily work, what are the current challenges and what you should expect next.

Some of the topics we will discuss are:

* The multiple flavors of distributed transactions
*	DBaS and Kubernetes
*	Relational and JSON
*	SQL, SQL++ and other query languages
*	Clustering and Sharding 
*	Indexing

Speaker Bio
-----------

Speaker and Developer Advocate at Couchbase, he started programming even before the college and never stopped coding since then. He is a Java & NoSQL specialist, open-source contributor, and an enthusiast of Microservices & DevOps

Links
-----

* Blog: http://denisrosa.com
* Company: https://couchbase.com 
* GitHub: https://github.com/deniswsrosa
* Photo: https://pbs.twimg.com/profile_images/1141676086008451072/7Gmh1dzQ.jpg

Extra Information
-----------------

I'm a frequent speaker in tech conferences, here are some talks of mine https://www.youtube.com/watch?v=PLAwcExtLVw , https://www.youtube.com/watch?v=B9qRJhA1ONs&t=169s

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, thanks for the talk proposal.

The PR must only add the file with your proposal (the `talk-title_presenter_name.md` file must remain unmodified). Can you please correct this?

Also, the `{{` and `}}` markers must be removed when filling out the template (as mentioned on the top of the file).

**Comment by deniswsrosa** [comment]
Oh, my bad, I will update it

**Comment by carlosefr** [comment]
The file contents are still switched. Your proposal is inside the template file.

**Comment by deniswsrosa** [comment]
Dear Carlos, I just updated the PR. Sorry for the long delay.

**Comment by carlosefr** [comment]
Congratulations @deniswsrosa, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
