### PR TITLE
Quantum Supremacy

### PR DESCRIPTION
**Pull request by msramalho**
Quantum Supremacy
=========================

* Speaker   : Miguel Sozinho Ramalho
* Available : first and second days
* Length    : workshop, 90min
* Language  : English

Description
-----------

In this workshop, participants will gain basic knowledge of what Quantum Computing is all about and how it has the potential to become the most disruptive breakthrough of the 21st century. Afterwards, we will have a hands-on experience by programming quantum circuits in Python (using IBM's Qiskit framework). Finally, we will try to run some of our circuits on real quantum computers (provided by IBM Q Experience, a cloud service for quantum computing). Participants will leave with some useful materials for continuing their quantum education.

Speaker Bio
-----------

MSc Student of [Computer|Software][Engineering|Science] @FEUP and research assistant @INESCTEC.  On a crusade to prove imagination is the only limitation - learning, teaching and programming help with that. I enjoy my personal projects, hackathons of all sorts, programming competitions and to have more to do than I have time for. My areas of focus range from Machine Learning to Quantum Computing, Infosec, Algorithms and Proper Software.

Links
-----

* Blog: https://msramalho.github.io
* GitHub: https://github.com/msramalho

Extra Information
-----------------

You can check [this course](https://github.com/msramalho/Teach-Me-Quantum) I developed on the topic of Quantum Computing 😉

### CODE REVIEW

**Comment by msramalho** [comment]
Duration for the workshop should be about 90min or 120min (later if it fits better in the schedule)

**Comment by carlosefr** [comment]
Can you update the proposal with the amout of time you prefer?

**Comment by msramalho** [comment]
is it ok, @carlosefr?

**Comment by carlosefr** [comment]
This talk has been pre-approved, which makes your other proposal in PR #267 unlikely (but not impossible) to be approved.

**Comment by msramalho** [comment]
Additional motivation? [course award](https://www.ibm.com/blogs/research/2019/01/ibmq-teach-quantum-winners/)

**Comment by msramalho** [comment]
Hey guys, it seems the workshop is only allocated a 1h slot on the website and if I had to choose between 1h and 2h (since I asked for 90min) I would go for 2h. What do you guys think? @carlosefr

**Pull request merged**
