### PR TITLE
Architecture and Organization

### PR DESCRIPTION
**Pull request by kevingoldsmith**
Architecture and Organization
=================================================

* Speaker   : Kevin Goldsmith
* Available : first day, second day
* Length    : 45
* Language  : English

Description
-----------

Over 50 years ago, Melvin Conway wrote an article identifying a correspondence between the structure of our organizations and the structure of the software we produce. We still talk about Conway's Law today because of the fundamental truth of that observation. This talk goes beyond that article to examine why this happens, and how you can take advantage of it to make better software and better teams.

Speaker Bio
-----------

Kevin Goldsmith has been a developer, software architect, technology manager, and senior technology executive for over 27 years. He is currently the Chief Technology Officer at Onfido in London, a machine learning and computer vision company helping users own their identities on the internet.
kevingoldsmith.com

Links
-----

* Blog: https://kevingoldsmith.com/writing.html
* Company: https://onfido.com
* GitHub: https://github.com/kevingoldsmith
* Photo: https://www.kevingoldsmith.com/talks/KevinGoldsmithSpeakerPhoto.jpg

Extra Information
-----------------

See https://www.kevingoldsmith.com/talks/ for other talks, talk recordings and slides from all my talks.

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, thanks for your talk proposal.

Can you abbreviate the talk description? As it is, it's very long and dense. It should ideally be just a brief summary of what the talk is going to be about.

If you wish to keep the remaining information for the review process, you can move it to the extra information section.

**Comment by carlosefr** [comment]
One more thing: there are two `.md` proposals in this PR. Please remove the one that's already part of PR #343.

**Comment by kevingoldsmith** [comment]
updated description and removed the other talk, forgot to branch...

**Comment by carlosefr** [comment]
Would you consider extending your talk to 45 minutes + QA to avoid stage downtime? (All slots are 1 hour long).

**Comment by kevingoldsmith** [comment]
Absolutely! This talk was originally 45 minutes long.

**Comment by carlosefr** [comment]
Great. Can you update the PR description above, as well as the `.md` file please?

**Comment by carlosefr** [comment]
We usually avoid approving multiple submissions from the same person to allow others to get their chance to go on stage. Due to your talk proposal in PR #343 having been accepted, this proposal has a very low (but not zero) chance of getting accepted.

**Comment by kevingoldsmith** [comment]
That is fine, I submitted both because I wanted to give multiple choices.

**Pull request closed without merging**
