### PR TITLE
How to build your own greenfield?

### PR DESCRIPTION
**Pull request by mariomc**
How to build your own greenfield?
=========================

* Speaker   : **Mário Gonçalves**
* Available : **any day, any time**
* Length    : **~45 minutes + QA**
* Language  : **English**

Description
-----------

How to deliver significant change without breaking changes? How to refactor while still delivering? How to create and not complicate? How to convince business to tackle technical debt? In sum, how to justify, implement and sustain change and innovation?

This talk will, through a real case-study analysis, draw upon the teachings of Change and Innovation Management and apply those concepts and frameworks to the blooming and creative reality of Software Development.

Speaker Bio
-----------

Hello! I'm Mário: A geek since 1985, a developer since 2007, a Software Engineer at Sky, an Open Source student, a Frontend teacher, an MTG player, a language nerd and an human being who likes to learn, think, help and create.

Links
-----

* LinkedIn: https://linkedin.com/in/mariomcgoncalves
* Twitter: https://twitter.com/mariomc
* Github: https://github.com/mariomc
* Company: https://sky.com

Extra Information
-----------------

This is not a technical talk but will pose a few poignant questions I've had to find out ways to answer throughout my technical career. Hopefully by sheding some light on those subjects, they'll be easier to tackle once anyone has to face them.

Previous talks given:
* https://twitter.com/requirelx/status/864162863081979905
* https://github.com/PixelsCamp/talks/blob/master/2017/javascript-the-new-english_mario-goncalves.md
* https://lisbon.landingfestival.com/talks/79

### CODE REVIEW

**Comment by carlosefr** [comment]
You marked this as 30 minutes long. Do you care to lengthen the talk to 45m+QA or prefer to stick with 30 minutes?

**Comment by mariomc** [comment]
I see no problem stretching it for an extra 5~10 minutes and/or using that time for extra QA. I'll submit accordingly

**Comment by carlosefr** [comment]
Can you please remove the formatting (italic) from the title?

**Comment by mariomc** [comment]
Sure thing!

**Pull request merged**
