### PR TITLE
AST Transformations For Fun & Profit

### PR DESCRIPTION
**Pull request by noamt**
AST Transformations For Fun & Profit
=================================================

* Speaker   : Noam Tenne
* Available : Every day, prefer the first day
* Length    : 60 minutes.
* Language  : English

Description
-----------

Let’s get intimate with Go and have fun with the Abstract Syntax Tree (AST, for short) package.
AST transformation is not a pie-in-the-sky technique, and familiarizing yourself with Go’s AST will 
add a very powerful tool to your figurative developer tool-belt.
In this session I will talk about what are AST transformations and what they can do for you.
We’ll review AST in theory, the important parts of the core ast package and see how we can use it to solve real world problems.

Speaker Bio
-----------

A hacker-hearted software engineer and DevOps cowboy. 
Noam has spent the past decade working on both cloud based and on-premise platforms,
gaining much experience in building scalable, mission critical systems ranging from software delivery, to medical devices and IoT.
You may have also heard him speak at conferences such as DevOps Days, PyCon, Jenkins User Conference and Gr8conf.
His love of creation isn't limited to programming, so he has co-created and co-founded podcasts, meetups, unconferences and music.
Noam is now wreaking havoc at VanMoof Bicycles.

Links
-----

* Blog: https://medium.com/@noamt/
* Company: https://vanmoof.com
* GitHub: https://github.com/noamt
* Photo: https://secure.gravatar.com/avatar/aba9dac582a7e4346b1895366200e2f2

Extra Information
-----------------

I’m very fond of messing around with AST.
I’ve preached it during my Groovy development days, I’ve built a whole python framework based on it and used it to solve real world problems with Go.
Quite a number of developers that I’ve met were wary about the subject, feeling that it’s a “hacky” way of getting things done. I couldn’t disagree more. I’d really like to help developers feel comfortable with the topic, as one can achieve many great things with it.

### CODE REVIEW

**Comment by carlosefr** [comment]
Will you consider extending your talk to 45 minutes + QA? Slots are always 1 hour long ans we'd rather minimize stage downtime.

If so, please update your `.md` file and the PR description above.

**Comment by noamt** [comment]
Done and done

**Comment by carlosefr** [comment]
Congratulations @noamt, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
Can you add an `.md` extension to your proposal file, please?

**Comment by noamt** [comment]
Ja, missed that. Sorry

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
