### PR TITLE
A brief and personal history of the software development process

### PR DESCRIPTION
**Pull request by malcata**
A brief and personal history of the software development process
 ========================
 
 * Speaker: Joao Malcata
 * Available: Thursday or Friday
 * Length: 30 mins
 * Language: English (or Portuguese)
 
 Description
 -----------
 Over almost 20 years, I have been involved in a multitude of software development endeavors. Out of sheer luck or just time passing, together they seem to show an “evolution“ worth sharing. Even if not systematic and according to a scientific process, experience does provide insight and I hope lessons to be learned.
 
 By the end of the session, you will be able to give some meaning to:
 1. where do you stand, as far as, the development process is concerned 
 2. what you feel would be the optimal scenario to unlock your potential
 
**Relevance**
Scrum has more than 20 years, the Agile Manifesto is 16 years old, DevOps has been around for 8 and we are living in the post-Agile era. Most tech key players are going public with their takes on how they do stuff, lessons learned turned into best practices.
In spite of all this, every time I talk to people I always get sentences like: "...and then it went into the test phase and stayed there for months...", "The ops team is always chasing after some fire when I need them.", "The dev guys take us for janitors to keep cleaning this shit in production...", "That Agile/DevOPS/Automation thing would not work here we are too big/small/complex...". The same problems over and over again.

**Novelty**
The subject itself is old and has been discussed a lot.
The insight I expect to bring is that, it is not about what you do, the sequence of steps you take to do something. But a lot more about how you do it, the attitude you put into it. Organizations must change to become more customer responsive, just adopting agile processes is makeup. The process you use to deliver something is a consequence of who you are and not the opposite.
My professional experience will be driving the talk on how circumstances, business nature and context influences the development process and not the other way around.

[further details](https://medium.com/@malcata/a-brief-history-of-the-software-development-process-according-to-my-experience-15a6349bb77a)

 ---------------
 
 Speaker Bio
 -----------
 
 Dad, software engineer, telco, cybersecurity, web, and OSS.
 15+ using tech to build products, teams, and processes.
 Divided by the knowledge that any simple thing can be made complex by adding people and that the secret ingredient for virtuosity and fun is people.
 
 Links
 -----
 
 * Blog: https://medium.com/@malcata
 * Company: http://intersection.ventures
* Github: https://github.com/malcata

### CODE REVIEW

**Comment by carlosefr** [comment]
"When you're ready, submit a pull request and comment using your markdown file contents."

Can you please add the proposal markdown to the first comment? Thanks.

**Comment by carlosefr** [comment]
Can you shorten the title a bit?

**Comment by malcata** [comment]
@carlosefr sorry for not answering before... is the "needs info" solved?

**Comment by carlosefr** [comment]
Actually, no. 😄

The first comment (the one where you have "Relevance ... ") must be edited to contain the contents of you proposal. We need this so that it shows in our backoffice.

**Comment by malcata** [comment]
@carlosefr hope we don't need a third time. I was under the illusion the comment was free text and the markup file was the reference, my bad. Thanks.

**Pull request merged**
