### PR TITLE
Create a brand for your project that doesn't suck

### PR DESCRIPTION
**Pull request by caneco**
Create a brand for your project that doesn't suck
===================================

* Speaker   : Caneco
* Available : Second day
* Length    : 45 minutes
* Language  : English

Description
-----------

Your project could have the best idea, and the most elegant code, but when you need to promote and share it on social networks where the 3-second rule speaks best, and you only have is a README file, it can be hard to grab your audience attention – it needs to "POP"!

So, instead of bothering again your cousin (that has a degree in design) for another logo and some artwork, what if you can make yourself?

Join me and discover easy ways for you to:

- [ ] find a great name
- [ ] design a custom Logo
- [ ] create a brand around the idea
- [ ] design some marketing swag (everybody loves swag)
- [ ] design appealing artworks to share on social networks
- [ ] think a bit outside of the box

Speaker Bio
-----------

**Caneco**

Caneco

> _Web Contortionist. Short for Developer being Designer and vice-versa @ MEDICARE_

I'm currently the Full-Stack Developer at MEDICARE, where I build web applications and tailored lead generation platforms.

Links
-----

* Company : [https://www.medicare.pt](https://www.medicare.pt)
* Github : [https://github.com/caneco](https://github.com/caneco)
* LinkedIn : [https://www.linkedin.com/in/caneco](https://www.linkedin.com/in/caneco)
* Twitter : [@caneco](https://twitter.com/caneco)

Extra Information
-----------------

#### Why me?

Despite having a degree on programming, and actually being paid to code, I've always have a special taste and care for design – specially smart design, a.k.a. Design Thinking.

And during this year I've started to help a friend of mine to brand some popular PHP projects, such as: Laravel Zero, PHP Insights, PHP-Plus, etc… And from a crazy idea during this month I opened up a *Call-For-Logos* ([twitter.com/Caneco/status/1179463831170486273](https://twitter.com/Caneco/status/1179463831170486273)) during the Hacktoberfest, and by the end of the marathon I had done **30 logos**, for open-source projects 🎉

Read more about it here: [https://dev.to/caneco/the-30-logos-i-did-for-hacktoberfest-38l7](dev.to/caneco/the-30-logos-i-did-for-hacktoberfest)

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, thanks for the talk proposal.

Can you please remove the blockquote formatting from the description? (Both from the `.md` and the PR description above.)

**Comment by carlosefr** [comment]
Also, if you revise your availability please let us know. It's pretty hard to schedule talks when the speaker isn't available for at least a full day (this won't exclude your proposal, but may mean we'll defer its eventual approval to closer to the event, when we know if we can accomodate your restrictions).

**Comment by caneco** [comment]
👋@carlosefr

> Can you please remove the blockquote formatting from the description? (Both from the .md and the PR description above.)

**Fixed**

> Also, if you revise your availability please let us know

**Just revised for the full second day…**
(don't `blame` me for trying 😅… you don't know unless you ask)

See you soon!

**Comment by carlosefr** [comment]
Thanks. One more thing: please remove the link from the "Speaker" field. Our backoffice doesn't like it.

**Comment by caneco** [comment]
> from the "Speaker" field

Wut?! 👀 

The links from the Extra information?

**Comment by carlosefr** [comment]
In your `.md` file:
```
* Speaker   : [Caneco](https://pixels.camp/caneco)
```
This can't be more than just plain text.

**Comment by caneco** [comment]
@carlosefr done 😄

**Comment by caneco** [comment]
World of Frontcraft
===================

Never mind… 😅

**Comment by carlosefr** [comment]
@caneco If you wish to submit a second talk proposal, please open a separate PR please.

Also, please also consider extending the duration of your talk(s) to 45 minutes + QA. It's not mandatory, but we'd rather not have stage downtime between talks.

**Comment by carlosefr** [comment]
Please note that as it is (with two proposals in the same PR) we cannot consider it for approval.

**Comment by caneco** [comment]
@carlosefr resolved (?)

**Comment by carlosefr** [comment]
Yes, but I still need to know if you're sticking with 30 minutes, or can extend to 45 minutes + QA. ;)

**Comment by caneco** [comment]
@carlosefr let's do this! 💪

**Comment by carlosefr** [comment]
Congratulations @caneco, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by caneco** [comment]
@carlosefr as discussed I've tweaked the talk a bit.

I've changed the talk's focus from "**logos**" to "**brand**" – I believe it adds more value and resources to the audience.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
