### PR TITLE
Changing mindset with lean and test automation

### PR DESCRIPTION
**Pull request by thiagomarquessp**
Changing Mindset with Lean and Test Automation
========================

* Speaker   : [*Thiago Marques Pereira*]
* Available : [*September 28, 29 or 30, 9am-12pm*]
* Length    : [*45 mins*]
* Language  : [*Portuguese*]

Description
-----------

**Today the companies are more attentive with costs of a technology team and the lean process and test automation are ways of reduce the costs because the product can reach the zero bug with techiniques of problems antecipation and avoid waste on the new features.
The objective of talk is presented techiniques about Lean Process and how to achieve excellence with problems antecipates and delivery value and how to use automation with cucumber for to have this with the purpose of achieving zero bug in new features.
I will realize live code for demonstration and how to conect in a CI tool for achieve the feedback for quickly every deploy.**

Speaker Bio
-----------
My name is Thiago, or Biro Biro. I am brazilian guy and right now I lived on Lisbon and I worked in OLX. The best place to work. 

12 years as QA dedicated in promote QA Culture in every development team with Lean methods and test automation.

12 articles about QA, Automation, Lean, etc and I have dedicated my life in teach new testers to think about agile testing techiniques and concepts. 

I promote the First and Second edition of QA Ninja Conference in Brazil, the first conference 100% free and Online for all regions of Brazil and the World. 

I was a speaker at the biggest technology event on Brazil called The Developers Conference (TDC - 2016) about Automation in Mobile Devices and speaker at DevOps & Tests Hack Nights of .NET community about automation tests on service layer with cucumber and ruby.

I am a enthusiast in Cucumber and BDD and Lean Process.

I have four repositories for teach new QAs for automated tests on service layer and functional layer and mobile devices called "CapybaraForAll, CalabashForAll, HTTPartyForAll" and I have a repository about Lean and automated tests techiniques called "Lean em projetos de automação" in my personal github.

Links
-----

* [Github:](http://github.com/thiagomarquessp)
* [Lean and Automation:](https://github.com/thiagomarquessp/lean-em-projetos-automacao)
* [Linkedin:](https://www.linkedin.com/in/thiago-m-pereira-3a315133/)

### CODE REVIEW

**Comment by celso** [comment]
Hi @thiagomarquessp something is wrong with your PR, it's not in the right place.

Also, please read https://github.com/PixelsCamp/talks/blob/master/README.md and improve you proposal when you can. There's not much info in it. Tks.

**Comment by carlosefr** [comment]
Can you please edit your first comment in this PR and paste the contents of the markdown file into it? Also, please edit the PR title to match the talk title.

The talk description also needs to be spruced up. It's too short and doesn't really describe what the talk will be about.

**Comment by celso** [comment]
@thiagomarquessp can you please answer our questions? Thanks.

**Comment by thiagomarquessp** [comment]
@celso  and @carlosefr sorry for my late: 

I fixed the md: 

[Changing Mindset with Leand and Test Automation]
========================

* Speaker   : [*Thiago Marques Pereira*]
* Available : [*September 28, 29 or 30, 9am-12pm*]
* Length    : [*45 mins*]
* Language  : [*Portuguese*]

Description
-----------

**Today the companies are more attentive with costs of a technology team and the lean process and test automation are ways of reduce the costs because the product can reach the zero bug with techiniques of problems antecipation and avoid waste on the new features.**

Speaker Bio
-----------
My name is Thiago, or Biro Biro. I am brazilian guy and right now I lived on Lisbon and I worked in OLX. The best place to work. 

12 years as QA dedicated in promote QA Culture in every development team with Lean methods and test automation.

12 articles about QA, Automation, Lean, etc and I have dedicated my life in teach new testers to think about agile testing techiniques and concepts. 

I promote the First and Second edition of QA Ninja Conference in Brazil, the first conference 100% free and Online for all regions of Brazil and the World. 

I was a speaker at the biggest technology event on Brazil called The Developers Conference (TDC - 2016) about Automation in Mobile Devices and speaker at DevOps & Tests Hack Nights of .NET community about automation tests on service layer with cucumber and ruby.

I am a enthusiast in Cucumber and BDD and Lean Process.

I have four repositories for teach new QAs for automated tests on service layer and functional layer and mobile devices called "CapybaraForAll, CalabashForAll, HTTPartyForAll" and I have a repository about Lean and automated tests techiniques called "Lean em projetos de automação" in my personal github.

Links
-----

* [Github:](http://github.com/thiagomarquessp)
* [Lean and Automation:](https://github.com/thiagomarquessp/lean-em-projetos-automacao)
* [Linkedin:](https://www.linkedin.com/in/thiago-m-pereira-3a315133/)

Thanks a lot.

**Comment by thiagomarquessp** [comment]
@celso some feedback about the talk? Thank you.

**Comment by celso** [comment]
@thiagomarquessp check your email please. we need an answer.

2017-09-24T23:59:29.093: sent talk_accepted email to user at thiago.pereira@olx.com
2017-09-21T01:07:43.188: sent talk_accepted email to user at thiago.pereira@olx.com

**Pull request merged**
