### PR TITLE
Saving the bees with IoT and Elixir 

### PR DESCRIPTION
**Pull request by ZePedroResende**
Saving the bees with IoT and Elixir 
=================================================

* Speaker   :  Jose Resende 
* Available :  first day, second day, third day 
* Length    :  60 minute 
* Language  :  English 

Description
-----------

Bees are dying at an incredible speed and if we don't find a solution we are going to die with them. 

This talk documents the design and creation of a plataform to help beekeepers get funding, metrics, health warnings and tips for their hives.

This will include the techonology behind it, Elixir, and how it helped us build an mvp with minimal fuss. 

Long live the bees 🐝

Speaker Bio
-----------

Finishing a Distributed systems and High performance computing master's degree, obsessed with rust and Elixir.

Hobbist musician and audiophile, Star Wars enthusiast. 

I spend my days building stuff at [Finiam](https://www.finiam.com/) or hacking away in my thesis.

Links
-----

* Company: https://www.finiam.com/ 
* GitHub: https://github.com/ZePedroResende 
* Photo: https://raw.githubusercontent.com/cesium/codeweek18/master/assets/img/speakers/resende.jpg

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, thanks for the proposal.
I have one nitpick and a question:

Shouldn't "IoT" and "Elixir" be capitalized in the title?
Would you consider extending your talk to 45 minutes + QA to minimize stage downtime? (Slots ate 1 hour long.)

**Comment by ZePedroResende** [comment]
Hey @carlosefr thanks for the catch :smile: ! 

I have material for 45 minutes no problem :+1: .

**Comment by carlosefr** [comment]
Congratulations @ZePedroResende , your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
