### PR TITLE
Ethical Software Development

### PR DESCRIPTION
**Pull request by antonioalmeida**
Ethical Software Development
=================================================

* Speaker   : António Almeida
* Available : (first day, second day, third day)
* Length    : 45 minutes
* Language  : English, Portuguese

Description
-----------

The late 2010s featured numerous privacy and ethical scandals involving tech giants such as Facebook and Google. A wave of technical activists have risen to fight this and related issues, such as climate emergency, sustainable startup funding, and big tech lobbying.

In other words, Software is now political.

What is the role of the average Software Engineer in these fights? This talk will show what choices of the software development cycle have an impact and how we're unwillingly part of the problem, specially in cloud based software. 

I'll provide guidelines and concrete technical solutions towards fully ethical software while maintaining professional standards. 

Speaker Bio
-----------

Last year student of BSc + MSc of Computer Engineering @FEUP, Portugal. Semi-professional handball player.

Links
-----

* Website: https://antonioalmeida.github.io
* GitHub: https://github.com/antonioalmeida
* Photo: [here](https://drive.google.com/open?id=1KB3I5jB3tq_dh0rA5OPzw4bnPcFrCD3n)

Extra Information
-----------------

The talk follows the anti Big Tech, privacy first, no data-hauling stance fiercely defended by "Software Activists". One of faces of this movement is [@dhh](https://twitter.com/dhh), creator of Ruby on Rails (honorable mention to [@aral](https://twitter.com/aral)).
The talk will cover industry wide research on how to comply with the ethical requests and apply them on one's Software.

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi,

Would you consider extending your talk to 45 minutes + QA to minimize stage downtime (all slots are 1 hour long)?

**Comment by antonioalmeida** [comment]
Sure.

**Comment by carlosefr** [comment]
Can you update the PR description *and* the `.md` file with that information, please?

**Comment by antonioalmeida** [comment]
Done

**Comment by carlosefr** [comment]
Congratulations @antonioalmeida, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
