### PR TITLE
Distributed Monoliths

### PR DESCRIPTION
**Pull request by JoaoVasques**
Distributed Monoliths
=================================================

* Speaker   : Joao Vasques
* Available : All days
* Length    : 45 minutes
* Language  : English

Description
-----------

If you don't treat Data as a first class citizen, almost all microservices architectures are nothing more than a Distributed Monolith. One aspect of microservices that is often neglected is the way Data is managed, shared and consumed accross the entire system. The purpose of the talk is to answer the following questions.

+ What is a Distributed Monolith?
+ What are the consequences of a Distributed Monolith?
+ How do we make sure our system is exposing the right Data in a standard format?
+ How to handle different different levels of consistency?
+ How can we avoid the centralized traditional ETL platform that needs to understand every piece of business logic in each microservice?
+ How is Unbabel avoiding the Distributed Monolith trap?

Speaker Bio
-----------

+ Engineering Manager for Data at Unbabel
+ 7 years of experience in Data systems
+ Interested in distributed systems (e.g. consensus, stream processing, distributed databases, consistency), SRE, Big Data Technologies and Machine Learning
+ Functional Programming advocate (Clojure evangelist)
+ Taekwondo Black Belt
	+  _2nd Place at the 2012 World Championship_

Links
-----

* Blog: https://medium.com/@joaovasques
* Company: http://unbabel.com
* GitHub: https://github.com/JoaoVasques
* Photo: https://avatars2.githubusercontent.com/u/1440120?v=4&s=460

Extra Information
-----------------

I gave a talk about Clojure on PixelsCamp V2

- https://pixels.camp/JoaoVasques
- https://www.slideshare.net/JooVazoVasques/purpose-of-programming-and-the-clojure-nirvana-80316123

### CODE REVIEW

**Comment by carlosefr** [comment]
Minor suggestion: adding a comma after "If you treat Data as a first class citizen". 😉

**Comment by JoaoVasques** [comment]
Done @carlosefr 😉

**Comment by JoaoVasques** [comment]
Fixed some typos

**Comment by carlosefr** [comment]
Congratulations @JoaoVasques , your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by JoaoVasques** [comment]
Great news @carlosefr ! Looking forward to it!

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
