### PR TITLE
one weird trick to be a better it professional

### PR DESCRIPTION
**Pull request by antonsarov**
# One weird trick to be a better IT professional
- Speaker   : _Anton Sarov_
- Available : _October 6th - October 8th_ 
- Length    : _30 mins / 45 mins_
- Language  : _English_
## Description

Making perfect software is vital. The one part that stays in the background is your personal development - now we will be talking about just one trick that YOU can do to bring your career forward and become a better IT professional.

---
## Speaker Bio

A Java/Scala coder. Anton is able to pay his rent thanks to a position as a Java Software Engineer in a Berlin-based company, working with rich client technologies. He can be found on the streets of Berlin riding his Honda (and thinking about Java/Scala). Oh, and he loves the Play Framework.
## Links
- Twitter: [https://twitter.com/duxanton](https://twitter.com/duxanton)
- Github: [https://github.com/antonsarov](https://github.com/antonsarov)

### CODE REVIEW

**Comment by LuRsT** [comment]
Thanks @antonsarov, but can you please copy paste the markdown file contents into the PR description?

**Comment by antonsarov** [comment]
@LuRsT no problem, look at the updated description

**Comment by LuRsT** [comment]
Looks great @antonsarov, thanks!

**Comment by celso** [comment]
Hi @antonsarov We need you to register and apply at https://pixels.camp/apply asap so we can proceed with your talk review. Thanks

**Comment by antonsarov** [comment]
Hi @celso I just submitted a short application, can provide a longer version when I am back from vacation next week

**Comment by celso** [comment]
@antonsarov thanks for your submission, but we're out of slots in the calendar now and we need to take tough decisions. We'll reopen your PR if a new slot emerges.

**Pull request closed without merging**
