### PR TITLE
Microinteractions: Little Things That Matter

### PR DESCRIPTION
**Pull request by JonathanDn**
Microinteractions: Little Things That Matter
=================================================

* Speaker   : Yonatan Doron
* Available : all days
* Length    : 45 minutes
* Language  : English

Description
-----------

Microinteractions are those little moments where design and code work together at their best. When used with care, they can even become signature moments, the way clapping for an article on Medium expresses the brand’s identity in a way that goes beyond any language or culture. In this talk, I’ll introduce the microinteraction at the abstract level, reveal its building blocks and show some concrete ways to understand and use them to create memorable, compelling interfaces.

Speaker Bio
-----------

Yonatan Doron is a Frontend Tech Lead at CyberX with a passion for user-centric frontend development and modular client architecture. Yonatan contributes content to various technology-focused outlets, writing thought leadership articles on software, frontend, and product design. In his spare time, he leads Hodash dev, one of the biggest developers Meetup communities in Israel and creates open-source projects.

Links
-----

* Blog: https://medium.com/@yonatandoron
* Company: https://cyberx-labs.com/
* GitHub: https://github.com/JonathanDn
* Photo: https://bit.ly/2ZQP905

Extra Information
-----------------

Microinteractions are my hobby. As a Frontend tech lead I love finding interesting microineractions, reverse-engineer them. Read and research the field as well as write and talk about them and their importance to create outstanding user experiences. I further aspire to empower Frontend developers to become more aware of microinteractions and help them step up to implement and sometimes even design microinteractions in the products they build from day to day.

References:

I recently gave this talk at Code.Talks 2019 in Hamburg :
[https://www.youtube.com/watch?v=NJk-2nz8u1Q](https://www.youtube.com/watch?v=NJk-2nz8u1Q)

I also gave a short lightning talk version of this talk at ConfrontJS 2019 in Warsaw:
[https://2019.confrontjs.com/speakers](https://2019.confrontjs.com/speakers)

I further write on this topic:
[https://uxdesign.cc/microinteractions-101-essential-tips-for-powerful-microinteractions-f1f52089a801](https://uxdesign.cc/microinteractions-101-essential-tips-for-powerful-microinteractions-f1f52089a801)

### CODE REVIEW

**Comment by carlosefr** [comment]
Would you consider extending your talk to 45 minutes + QA to avoid stage downtime? (All slots are 1 hour long).

**Comment by JonathanDn** [comment]
Hey Carlos, sure thing I can make the talk 45 minutes + QA

**Comment by carlosefr** [comment]
Great. Can you update the PR description above, as well as the `.md` file please?

**Comment by JonathanDn** [comment]
Sure thing. done

**Comment by carlosefr** [comment]
Congratulations @JonathanDn, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request closed without merging**
