### PR TITLE
Penalty-free multiplatform programming with Kotlin

### PR DESCRIPTION
**Pull request by goncalossilva**
Penalty-free multiplatform programming with Kotlin
===

* Speaker   : **Gonçalo Silva**
* Available : **Any day, preferably afternoon**
* Length    : **60 minutes**
* Language  : **English**

Description
---

In a time where native platform support can be a significant advantage, having a toolchain that enables free or practically free abstractions is groundbreaking. It allows individuals and small teams to effectively compete with large corporations.

LLVM opened a door, and Rust, Swift & Co came in. Kotlin, adding seamless JVM / JS support and interop on top of this, is the ultimate contender in true, penalty-free multiplatform programming.

In this talk, we'll go over the core ideas behind Kotlin Multiplatform, how it works, how it integrates with different platforms, its strenghts, weaknesses, and how it looks like in a real-world scenario.

Speaker Bio
---

Gonçalo is CTO at Doist, makers of Todoist and Twist. Obsessed with code, product design and strategy, he's built and contributed to multiple open source projects.

Links
---

* Twitter: https://twitter.com/goncalossilva
* Company: https://doist.com (https://todoist.com & https://twist.com)
* GitHub: https://github.com/goncalossilva

Extra Information
---

It's daunting to even consider launching a native app for Web, Android, iOS, Windows, macOS, and providing a backend for all that. But what if you could share most of the code? This could be revolutionary, specially for indie developers.

Rust, Swift and other LLVM-based languages can arguably provide this, but not without downsides. For one, using native libraries on Android is a little cumbersome and incurs in call site penalties. On the other hand, WebAssembly support has come a long way, but still sits at roughly 78%. Good, but not best.

Ultimately, Kotlin Multiplatform is the most interesting and ambitious thing about Kotlin. It raises the bar on penalty-free, multi-platform development. It allows small teams to compete with large enterprises (that will undoubtedly take a long time to adopt this) on all fronts that matter.

Lastly, it is backed by JetBrains, and consequently surrounded by incredible tooling.

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, can you remove the markdown formatting from the talk title? Thanks.

**Comment by goncalossilva** [comment]
Done. :+1:

**Comment by carlosefr** [comment]
The title now says you're going to talk about "Kotli". ;)

**Comment by goncalossilva** [comment]
Huh, sorry :man_facepalming: Quick turnaround turned into messy turnaround.

Pushed, reviewed, should be good to go.

**Pull request merged**
