### PR TITLE
PiHeadquarters or How to Take Control of your House with Raspberry Pi and Docker

### PR DESCRIPTION
**Pull request by jpdias**
PiHeadquarters or How to Take Control of your House with Raspberry Pi and Docker
========================

* Speaker   : [João Pedro Dias](https://pixels.camp/jpdias)
* Available : Always
* Length    : 45 minutes
* Language  : Portuguese

Description
-----------

We're living on the verge of ubiquitous computing, where _computing is made to appear everywhere and anywhere_. As such, we're dealing with this now, by the means of the Internet of Things. Empowered by the ever-cheaper devices with internet connectivity such as the ESP8266 (that costs under 4$) we're able to build our very _own_ smart homes. However, some questions arise on how to deal with all the sensing and actuating capabilities of such devices as well as all the privacy and security issues that are on the table. 

A very common approach that has been applied is the use of gateways for control the data flow between _things_ and the Internet as is. As worth mentioning and novel example of such is the [Things Gateway](https://iot.mozilla.org/gateway/) by Mozilla. In this talk, I will share how I build my _smart home_ headquarters (gateway and server) on top of a Raspberry Pi 2, using Docker and all the _buzzwords_ such as [MQTT](http://mqtt.org/), [Mosquitto](https://mosquitto.org/), [InfluxDB](https://www.influxdata.com/time-series-platform/influxdb/), [Grafana](https://grafana.com/) and [Node-RED](https://nodered.org/). With this approach anyone is capable of continuosly monitor the current state of the home by its metrics, configure alarms (such as a moving sensor for intruder alert), turn on the AC system before leaving work or even make dinner by turning on the microwave, all empowered by easily-configured flow-control diagrams.

---------------

Speaker Bio
-----------

I'm João Pedro Dias and I'm currently working as a researcher at INESC TEC. Finished my MSc degree in Informatics and Computing Engineering last year (2016) and I'm now enrolled in a PhD on Informatics Engineering. Passionate about technology in general, with a special focus on security and privacy, web development, data mining & Internet of Things. Furthermore, an amateur photographer, football player, book lover and science addict.

Links
-----

* Blog: [https://jpdias.me/](http://jpdias.me/)
* Company: [https://inesctec.pt/](http://inesctec.pt/)
* Github: [https://github.com/jpdias/](https://github.com/jpdias/)

### CODE REVIEW

**Comment by jpdias** [comment]
Update: The talk will be in English.

**Comment by carlosefr** [comment]
Can you shorten the talk title a bit? Thanks.

**Comment by jpdias** [comment]
@carlosefr Of course I can, are 30 min is ok?

**Comment by carlosefr** [comment]
The talk's *title*, not its duration. :)

**Comment by jpdias** [comment]
@carlosefr Oh sorry, a little distracted. Something like "Taking Control of your House _Things_ with Raspberry Pi and Docker" works? :)

**Comment by carlosefr** [comment]
It does.

**Pull request merged**
