### PR TITLE
Do you even (Kotlin) Flow? The new API for reactive programming

### PR DESCRIPTION
**Pull request by rcosteira79**
Do you even (Kotlin) Flow? The new API for reactive programming
=========================

* Speaker : **Ricardo Costeira**
* Available : **every day**
* Length : **45 minutes**
* Language : **English**

Description
-----------

Reactive programming is here to stay.
Most Android devs nowadays are used to sprinkle RxJava throughout their apps, even if they don't actually have use for reactive streams and just want to simplify thread scheduling. However, it's also true that more and more devs are becoming aware that Rx is an overkill for their use case, and long for better options.
Kotlin Flow is one of the new additions to the Kotlin coroutines library, and is meant to bring reactive streams to the coroutine world. But is it as powerful as RxJava?
In this talk, I'll explore what Kotlin Flow is, how can it be used, and how can it imbue our apps with the power of reactive programming.

Speaker Bio
-----------

Ricardo is an Android dev at Mindera. He has a crush on clean code and software architecture. He's an organizer at GDG Coimbra, and a co-founder of Kotlin Knights.

Links
-----

* Blog: https://ricardocosteira.com
* Company: https://mindera.com
* GitHub: https://github.com/rcosteira79
* Photo: https://github.com/rcosteira79/rcosteira79.github.io/blob/master/assets/images/me.jpg

Extra Information
-----------------

You can check the slides of the talk's latest version at https://speakerdeck.com/rcosteira79/do-you-even-kotlin-flow-the-new-api-for-reactive-programming

### CODE REVIEW

**Comment by carlosefr** [comment]
Would you consider extending your talk to 45 minutes + QA to minimize stage downtime (all slots are 1 hour long)?

Please update both the PR description above and the `.md` file if you do.

Also, can you fix the `.md` file markup to match the one used in the template?

**Comment by rcosteira79** [comment]
Sure! The talk is originally 45 minutes long, the "30 minutes increments" bit is what made me reduce the time 😛

**Comment by carlosefr** [comment]
Ok, just missing the markup fix in the `.md` file.

**Comment by rcosteira79** [comment]
What are you referring to? Can't seem to find any differences.

**Comment by rcosteira79** [comment]
Nevermind, vscode was automatically changing everything.

**Comment by rcosteira79** [comment]
Should be OK now.

**Comment by meddulla** [comment]
Congratulations @rcosteira79, your talk proposal has been pre-accepted.
This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).
In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by meddulla** [comment]
Please take into account that speakers must apply and be accepted as Pixels Camp attendees as well (to enter the venue).

I've not been able to find the your handle in the Pixels Camp attendee database.

**Comment by rcosteira79** [comment]
HI! Thanks for pre-accepting the talk!

Yeah, I didn't know about the attendee acceptance bit. Sorry about that! Just made my acceptance pitch a few minutes ago :)

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
