### PR TITLE
Doing Open Source as a contributor and a maintainer

### PR DESCRIPTION
**Pull request by isabelcosta**
Doing Open Source as a contributor and a maintainer
=================================================

* Speaker   : Isabel Costa
* Available : second and third day (27 and 28th March)
* Length    : 40 min
* Language  : English

Description
-----------

When I was accepted into Google Summer of Code program, I was a total beginner at Open Source. 
I did some very small contributions but was still very intimidated by Open Source. 
I started the program as a student working on the project I proposed with the help of my mentors and community and after it ended I became a maintainer. 
As a contributor, I had to work on projects I didn’t know much as a maintainer I had to make sure the project was ready and friendly to outside contributors. 
In this talk, I want to share my learnings and perspective from working in Open Source being on both sides, 
while sharing some tips on how to start contributing to a new project and keeping a project beginner friendly.

Speaker Bio
-----------

Isabel is a Software Engineer at GeoPhy.
She got into Open Source through Google Summer of Code (GSoC) program in 2018.
During her time as a GSoC student, she started a project with Systers Open Source community, 
using python for the backend and Kotlin for the Android application. She started as a student and now is one of the maintainers of the project, using it to help beginners at Open Source do their first contributions.

Links
-----

* Blog: https://medium.com/@isabelcmdcosta
* GitHub: https://github.com/isabelcosta
* Photo: https://avatars0.githubusercontent.com/u/11148726?s=400&v=4

Extra Information
-----------------

List of previous talks I've given: https://isabelcosta.github.io/talks/

### CODE REVIEW

**Comment by carlosefr** [comment]
Congratulations @isabelcosta, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by isabelcosta** [comment]
@carlosefr thank you so much for letting me know 🎉

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Comment by isabelcosta** [comment]
Completely understand! Looking forward to a future edition of Pixel Camp once conditions allow doing so :)

**Pull request merged**
