### PR TITLE
The Search for Sensey McSenseface

### PR DESCRIPTION
**Pull request by websy85**
The Search for Sensey McSenseface
=========================

* Speaker   : Nick Webster
* Available : First day, all
* Length    : 60 minutes
* Language  : English

Description
-----------

Wouldn't it be cool if you could use natural language to ask questions about your data and get visualisations, built on-the-fly, in response? What if you could have a conversation with the tool to resolve ambiguities and improve the quality of the results. What if it was created using technologies that were either open source or free to use, or could be put into a smart device like the Amazon Echo or even a magic mirror.  Well, you can and, for the most part, thanks to the wonder of JavaScript!

Speaker Bio
-----------

Nick has 10+ years experience in application and web development and 6+ years working for Qlik. During his time at Qlik he helped architect both Qlik Branch and Qlik Playground and played a significant part in the design and development of the search capabilities that exist in Qlik Sense today. He now runs Websy, sharing his expertise in web technologies, data visualisation and Qlik, teaching others and talking at events. Follow Nick on twitter - @websy85 

Links
-----

* Blog: http://websy.io/blog
* Company: https://websy.academy
* GitHub: https://github.com/websy85

Extra Information
-----------------

In this talk, I focus on how the challenges with NLP can be simplified if you focus on specific problems or data sets. There are no 3rd party NLP libraries being used, just a series of logical steps to determine the users intent. To date, the solution has been deployed on the web (https://twitter.com/websy85/status/745992316394016768), via an Alexa skill (https://twitter.com/WebsyIO/status/946788758904561665) and in a magic mirror (https://twitter.com/websy85/status/986678887332622336).

### CODE REVIEW

**Comment by edevil** [comment]
Hello @websy85.

You need to alter the PR description to add the contents, it's easier to review.

> Use your talk's title as the PRs title and use the contents of your proposal as its description. This will help with the revision process as well as allow the public to comment/vote on proposals.

Thank you.

**Comment by carlosefr** [comment]
Would you consider extending the talk to 45/50 minutes + QA or do you prefer to stick with 30 minutes?

**Comment by websy85** [comment]
@carlosefr I'd be happy to extend the talk to 45/50 minutes with questions. Due to a currently hectic schedule I've had to update my availability, so should you decide to accept the talk, Thursday (day one) would be the only day that would work.

**Comment by carlosefr** [comment]
Can you update the proposal with the new length? Thanks.

**Comment by carlosefr** [comment]
I'm sorry but our calendar is now full, which means your talk didn't make the cut this year.

**Pull request closed without merging**
