### PR TITLE
Processing 100 million euros per second with Spark to detect credit card data breaches

### PR DESCRIPTION
**Pull request by jaimerferreira**
# Processing 100 million euros per second with Spark to detect credit card data breaches 
- Speaker   : Jaime Ferreira and Mariana Lourenço
- Available : 6-7 October, any time 
- Length    : 20-30 Mins
- Language  : English
## Description

In recent years fraudsters have stolen hundreds of millions of credit cards which they then resell and use, resulting in losses of billions of euros for banks, merchants and consumers. In this talk we describe BreachRadar, a new approach to data breach detection using a distributed, graph-based algorithm implemented in Spark. BreachRadar has already proven its scalability by processing about 4000 million transactions per hour, or about 100 million euros per second, and has discovered types of breaches as precise as a single compromised ATM or as wide as a nationwide merchant network.
## Speaker Bio

Jaime and Mariana are part of Feedzai's Research team. The primary goal of the team is to develop new algorithms and adapt existing ones to the domain of fraud detection, keeping Feedzai the state-of-the-art leader in fraud detection.
## Links
- Company: http://feedzai.com

---

This is a proposal for a talk regarding automatic detection of data breaches using Scala+Spark to process large datasets with billions of transactions. 

The novelty factor is that, to our knowledge, there is currently no other approach to automatic detection of data breaches.

We also believe the talk is suitable to Pixels Camp target audience as it talks about how we can design a system able to scale in a big data environment.

### CODE REVIEW

**Comment by celso** [comment]
Hi Jaime and Mariana, we need you to apply here so we can get your email etc to give you feedback on the talk review process: https://pixels.camp/apply/

Thanks!

**Comment by jaimerferreira** [comment]
Thank you for your response.

Can you tell us what is the deadline for this application process?

Best regards,
Jaime Ferreira

**Comment by celso** [comment]
As soon as you apply, we will get in touch with you with a response. Please go to https://pixels.camp/apply/ and fill up the form. Thanks.

**Comment by celso** [comment]
Pretty please!

**Comment by jaimerferreira** [comment]
Sorry about the delay, both me and Mariana were on vacation, so things
moved a lot slower.

It's submitted now.

**Pull request merged**
