### PR TITLE
FONK - A Serverless Stack for Kubernetes

### PR DESCRIPTION
**Pull request by juliogomez**
FONK - A Serverless Stack for Kubernetes
=========================

* Speaker   : Julio Gomez
* Available : Thu since 12pm to Friday 2pm
* Length    : 45/50 minutes + QA
* Language  : English (or Spanish)

Description
-----------

For many years you have used LAMP stacks for your web projects. Now serverless offers multiple benefits around optimization and cost, but maybe you are not sure how to use it. Probably you are even concerned about the lock-in when using public cloud managed offerings.

FONK is an evolution of the LAMP idea, but focused on open-source serverless application architectures, with the goal of avoiding lock-in. This session will discuss FONK (F=FaaS, O=Object store, N=NoSQL, K=Kubernetes) concepts and demonstrate how they apply to example web applications. 

Demos will be held. Also awkward silences.

Speaker Bio
-----------

Julio Gomez is a Cisco veteran spending most of his life working on the technical side of Service Provider, Data Center and Cloud spaces. He is specially interested in Cloud native technologies and how they are shaping the future of our industry. 

CCIE and AWS Architect, he is deeply involved and really passionate about DevOps, Cloud native application development, microservices, Docker, Kubernetes, Istio, and CI/CD. His experience spans across on-premises and public Cloud providers as well, including Google Cloud Platform and Amazon Web Services.

He plays old guitars. Like, very old ones.

Links
-----

* Blog: https://blogs.cisco.com/author/juliogomez
* Company: https://www.cisco.com/
* GitHub: https://github.com/juliogomez/

Extra Information
-----------------

Link to the FONK project website: http://fonk-apps.io/
GitHub for the FONK project: https://github.com/fonk-apps

### CODE REVIEW

**Comment by carlosefr** [comment]
Would you consider extending the talk to 45/50 minutes + QA or do you prefer to stick with 30 minutes?

**Comment by juliogomez** [comment]
Sure! In fact my previous deliveries were 45 minutes, so I can adapt it. Just let me know your preference.

**Comment by carlosefr** [comment]
Can you please update the proposal with the new length? Thanks.

**Comment by juliogomez** [comment]
Done, cheers!

**Pull request merged**
