### PR TITLE
Personality Hacking with Node, NLP and Houdini

### PR DESCRIPTION
**Pull request by mcconville**
Personality Hacking with Node, NLP and Houdini
=================================================

* Speaker   : Anton McConville
* Available : Any day
* Length    : 60 minutes
* Language  : English

Description
-----------

In this session we use JavaScript on the server, and in the browser to beautifully visualize personality changes of musical artists during their career, through their lyrics.

On the server we use Node to interface with Natural Language Processing APIs. On the client we use WebAudio to explore the dimensions of sound, and experiment with emerging CSS Houdini APIs to play with visualizations.

The session steps through the open source project code, analyzes the outcomes, and considers real world applications for the concepts. We'll dig deeper into CSS Houdini ... taking more time to walk through the creation of a new custom CSS class as a demo.

Speaker Bio
-----------

**Anton McConville**

Anton McConville

Anton is a digital designer and developer with a passion for building thoughtful, data inspired mobile apps made with iOS or HTML.

He is a graduate engineer, with art school training in illustration, and experience leading both UX design, and development teams for projects in telecoms, finance and retail.

In his current role at IBM, Anton leads a digital creative team, producing case study apps and projects on IBM's cloud platform and the services it offers - for sharing with corporate clients, analysts and the tech community.

Anton is also a regular speaker at international software design and development conferences.

Links
-----

* Website: https://mcconville.github.io
* Blog: https://mcconville.github.io/blog/
* GitHub: https://github.com/mcconville
* Twitter: https://twitter.com/antonmc
* Instagram: https://www.instagram.com/antonmc/
* LinkedIn: https://www.linkedin.com/in/antonmc/
* Dribbble: https://dribbble.com/antonmc
* Employer: https://developer.ibm.com/

Extra Information
-----------------

My session is based on a continuing interest that I have in using Natural Language Processing technology for analyzing the changes of personality/psychology of an artist's music over time.

I like to draw simple storybook images of the artists to create a website to accompany the psychology data that NLP reveals. I first talked about it at GitHub CodeConf in 2016 ... you can see that talk here ...

https://www.youtube.com/watch?v=56ftygaP68I

and an example of my work here:

http://ziggy.mybluemix.net/

My interest evolved with Houdini CSS to see how that technology might enhance some of the ideas, and I presented my first session looking at Coldplay's lyrics with NLP and Houdini CSS at JSConf Colombia late in 2019 ...

https://jsconf.co/schedule/

They haven't posted the videos from that conference yet.

I'm currently working on a new analysis of the Beatles lyrics with NLP and exploring more with Houdini.

My session shows how to build with Houdini and looks at the power of NLP using IBM Watson APIs ( which can be used for free in limited ways ). My session also considers web and data literacy as a medium for self expression and understanding. It is a thought provoking and relatable session.

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi. Thanks for the talk proposal.

Can you move your `.md` file from the `2019` folder and into the root of the repository?

**Comment by mcconville** [comment]
> Hi. Thanks for the talk proposal.
> 
> Can you move your `.md` file from the `2019` folder and into the root of the repository?

Hi, I moved it ... I think ... please can you let me know if I moved it to where you expect? I also added minor improvements to the description. Thanks for reviewing.

**Comment by mcconville** [comment]
Just to note that I can easily extend my talk from 30 minutes to 45 and dig deeper into CSS Houdini ... taking more time to walk through the creation of a new custom CSS class as a demo.

**Comment by carlosefr** [comment]
That's great. Can you update both the `.md` file and the PR description above with that information, please?

**Comment by mcconville** [comment]
> That's great. Can you update both the `.md` file and the PR description above with that information, please?

Made changes ... please let me know if they are enough :) Thanks.

**Comment by carlosefr** [comment]
Congratulations @mcconville, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by meddulla** [comment]
Canceled by speaker.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request closed without merging**
