### PR TITLE
More Tests, Less Work

### PR DESCRIPTION
**Pull request by goblindegook**
More Tests, Less Work
=====================

* Speaker   : Miguel Duarte, Luís Rodrigues
* Available : any day
* Length    : 45 minutes
* Language  : English

Description
-----------

Writing tests can be tricky. How do you ensure appropriate coverage yet keep things straightforward and maintainable? Generative testing exists to reinforce your tests with hundreds of randomised checks, but it requires changing your test design mentality. This talk introduces `fast-check` and its underpinnings, and will help you think less about expected results and more about general behaviour that you can test.

Speaker Bio
-----------

Miguel Duarte and Luís Rodrigues are software engineers at Equal Experts Portugal.

Links
-----

* Company: https://equalexperts.com
* GitHub: https://github.com/malduarte
* Twitter: https://twitter.com/malduarte
* Blog: https://goblindegook.com
* GitHub: https://github.com/goblindegook
* Twitter: https://twitter.com/goblindegook

Extra Information
-----------------

Talk slides: https://github.com/goblindegook/talks/blob/master/property-based-testing.md

### CODE REVIEW

**Comment by carlosefr** [comment]
Would you consider extending the talk to 45/50 minutes + QA or do you prefer to stick with 30 minutes?

**Comment by goblindegook** [comment]
@carlosefr Can run a bit longer, with some additional practical examples. From past experience, there's usually a few questions about property based tests too.

**Comment by carlosefr** [comment]
Can you update the proposal with the new length? Thanks.

**Comment by celso** [comment]
Miguel Duarte has to register for Pixels Camp, we don't see him in the backoffice: https://pixels.camp/apply/

@malduarte

**Pull request merged**
