### PR TITLE
Utility-First CSS: Build a clean Component based system

### PR DESCRIPTION
**Pull request by caneco**
Utility-First CSS: Build a clean Component based system
=========================

* Speaker   : **Vitor Caneco**
* Available : **21 and 22 March, 10am--6pm**
* Length    : **30~45 minutes**
* Language  : **English**

Description
-----------

You may be familiar with the time when the CSS of your application reaches the point when you start adding some weird classes like:

`.title--24px`, `.section__big--diff-2`, `button-primary--important`, etc, …

This often happens when you receive that request from the Stakeholders to have the same panel element, but with some slight differences? Or maybe that express request for an individual primary button to have more space on the top?

So, instead of creating some `later.css`, or just add `!important` here and there, join us and hear how and why an utility-first approach could save you a lot of time… but most of all, some big headaches.

Speaker Bio
-----------

Speaker Image

**Vitor Caneco**

> _Web Contortionist. Short for Developer being Designer and vice-versa @ Kwanko_

I'm currently the IT Project Manager / Web Developer at Kwanko – where I build tailored platforms for some of the top Portuguese brands and advertising agencies so they can reach the best performance in the market.

Links
-----

* Company : [https://www.kwanko.com](https://www.kwanko.com)
* Github : [https://github.com/caneco](https://github.com/caneco)
* LinkedIn : [https://www.linkedin.com/in/caneco](https://www.linkedin.com/in/caneco)
* Twitter : [@caneco](https://twitter.com/caneco)

Extra Information
-----------------

The value prop of this talk is to help any Front-end developer that can relate to the same struggles. And with my own experience, and some 🔥 tips, I will show some real-case examples that either give you the _"Aha! moment"_, or just learn something new.

To wrap it up… the key point can be presented in under 30 minutes. But I prefer to extend to 45 minutes, so I can show some examples.

### CODE REVIEW

**Comment by carlosefr** [comment]
Can you please review the description a little bit? (i.e. typos)

**Comment by caneco** [comment]
@carlosefr sorry about that… Just made a full revision on the talk.

**Comment by carlosefr** [comment]
I'm kind of a grammar nazi, sorry about that, so I still have some suggestions... ;)

> You may be familiar with the time when the CSS of your application reaches the point when you start adding some weird classes like:
> 
> .title--24px, .section__big--diff-2, button-primary--important, etc, …
> 
> This often happens when you receive that request from the Stakeholders to have the same panel element, but with some slight differences? Or maybe that express request for an individual primary button to have more space on the top?
> 
> So, instead of creating some later.css, or just adding !important here and there, join us and hear how and why an utility-first approach could save you a lot of time… but most of all, some big headaches.

**Comment by caneco** [comment]
@carlosefr I don't mind any suggestions, particular when they are entirely correct. 💯 
Just finished the edition. Thanks a lot!

**Pull request merged**
