### PR TITLE
Ballmer Peak or Drunk Trying

### PR DESCRIPTION
**Pull request by msramalho**
Ballmer Peak or Drunk Trying
=========================

* Speaker   : Miguel Sozinho Ramalho
* Available : first and second days
* Length    : workshop, 60min
* Language  : English

Description
-----------
Ballmer Peak is the theory that computer programmers obtain quasi-magical, superhuman coding ability when they have a very specific blood alcohol concentration percentage.

I propose a group experiment in which participants will be performing programming tasks while their blood alcohol concentration is scientifically increased with beer.
The goal is to help each participant reach their Ballmer peak, both for validating the theory and for personal gain of each one. 
This is not too scientific as there won't be a control group, but neither is that the endgame here!
The amount of alcohol ingested will be small and only enough to trigger the effect, 2 to 4 beers should suffice.

The discovery of this effect is attributed to Steve Ballmer, CEO of Microsoft (2000-2014).

Speaker Bio
-----------

MSc Student of [Computer|Software][Engineering|Science] @FEUP and research assistant @INESCTEC. 
On a crusade to prove imagination is the only limitation - learning, teaching and programming help with that.
I enjoy my personal projects, hackathons of all sorts, programming competitions and to have more to do than I have time for.
My areas of focus range from Machine Learning to Quantum Computing, Infosec, Algorithms and Proper Software.

Links
-----

* Blog: https://msramalho.github.io
* GitHub: https://github.com/msramalho

Extra Information
-----------------
<p align="center"></p>

 * [Steve Ballmer](https://en.wikipedia.org/wiki/Steve_Ballmer)
 * [A study says...](https://observer.com/2012/04/bottoms-up-the-ballmer-peak-is-real-study-says/)

### CODE REVIEW

**Comment by msramalho** [comment]
I had to undo some commits because I did not branch before... ignore all but the 23d8a39 commit

**Comment by msramalho** [comment]
Additionally, this workshop/experiment can only be possible if there is enough beer: an average of 3 (std 1) should be enough. Would that be possible from the organisation?

**Comment by carlosefr** [comment]
Sounds fun, but you know the absence of alcoholic beverages inside Pixels Camp is a rule that's been in place since forever, right?

**Comment by msramalho** [comment]
I knew not. I'll leave it up to you guys, then.

**Pull request closed without merging**
