### PR TITLE
Murphy's Law in the IoT Age

### PR DESCRIPTION
**Pull request by jpdias**
Murphy's Law in the IoT Age
=================================================

* Speaker   : João Pedro Dias
* Available : Any day
* Length    : 60 minutes
* Language  : English

Description
-----------

With the promise of improving our well-being, ~smart~ devices permeated our lives on an unforeseen scale and became a significant influence on our daily tasks. In this talk, I will discuss the IoT landscape from Murphy's law perspective --- *whatever can go wrong, will go wrong* --- and why these systems are mostly unreliable, insecure and privacy-threatening. From the *naive* Mirai botnet incident to laser-powered attacks on smart assistants, giving some Portuguese examples, I expect to show you why we are still in the *dark ages* of IoT and to raise awareness on the compromises that we are making when we bring these devices home, even if they are fun to play with.

From Google Home assistant to Amazon Ring doorbells, most IoT devices suffer from some *bad* design decisions in terms of security, safety, interoperability, or intolerance to network failures. Even if most of these systems are not *mission critical*, and their malfunctions, most of the times, do not provoke severe damage or are life-threatening, they push back IoT from an enhancement to a burden on our daily lives.

Speaker Bio
-----------

I'm João Pedro Dias, a researcher at INESC TEC, an Invited Assistant Lecturer and PhD student at Faculty of Engineering, University of Porto. I'm currently researching on the thin line between hardware and software from a software engineering perspective, delving into thematics such as fault-tolerance, IoT system development, monitoring and maintenace. I'm passionate about technology in general, with a special focus on security and privacy, web development, embedded systems & Internet-of-Things.

Links
-----

* Blog: [https://jpdias.me](https://jpdias.me)
* Company: [FEUP](https://www.fe.up.pt/) and [INESC TEC](https://inesctec.pt/)
* GitHub: [https://github.com/jpdias](https://github.com/jpdias)
* Photo: [https://jpdias.me/images/profile.jpg](https://jpdias.me/images/profile.jpg)

Extra Information
-----------------

Parts of these talk are inspired in a previous talk given at the [ØxＯＰＯＳɆＣ Mɇɇtuᵽ](https://www.meetup.com/0xOPOSEC/): [Internet-of-b̶r̶o̶k̶e̶n̶ -Things: A highly-opinionated overview](https://speakerdeck.com/jpdias/internet-of-broken-things). Other parts are based on my PhD on-going research.

Past Workshops @ PixelsCamp
- [Unravelling the Web of Things: Exploring Mozilla Things Framework /2019](https://github.com/PixelsCamp/talks/blob/master/2019/unravelling-the-web-of-things_joao-pedro-dias.md)
- [PiHeadquarters or How to Take Control of your House with Raspberry Pi and Docker /2017](https://github.com/PixelsCamp/talks/blob/master/2017/take_control_of_your_house_with_rpi_and_docker-joao_pedro_dias.md)

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, thanks for the talk proposal.

If you agree, I'd suggest shortening the first paragraph of the description. The second paragraph is what actually describes the talk and it would be better if it was at or near the beginning. In the calendar the description will be severely truncated, so it should trigger the audience's interest in the first few words.

This title could also be shortened to something like "Murphy's Law in the age of IoT" for the same reason, but it should be OK as is. 

Also, a nitpick: isn't it usually "Murphy's Law" (with an 's)? :)

If you happen to change something, please update both the `.md` file and the PR description above. Thanks.

**Comment by jpdias** [comment]
Hi @carlosefr. 

Just followed your recommendations, everything should be fixed now!

> Also, a nitpick: isn't it usually "Murphy's Law" (with an 's)? :)

 Yes it is. Fixed!  

Thanks.

**Comment by carlosefr** [comment]
Just one more small thing that our backoffice is complaining about... Your `.md` file isn't named according to the template (it's missing your name).

**Comment by jpdias** [comment]
> Your `.md` file isn't named according to the template

Damn it, should be fixed now.

**Comment by carlosefr** [comment]
Congratulations @jpdias, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
