### PR TITLE
A Tour of ActivityPub

### PR DESCRIPTION
**Pull request by diogogithub**
A Tour of ActivityPub
=================================================

* Speaker   : Diogo Cordeiro
* Available : Any
* Length    : 1 hour
* Language  : Portuguese

Description
-----------

The ActivityPub protocol is a decentralized social networking protocol based upon the ActivityStreams 2.0 data format. It provides a client to server API for creating, updating and deleting content, as well as a federated server to server API for delivering notifications and content.

In this talk, we will go for a small tour through the history of the Fediverse, the context in which ActivityPub was introduced, the internals of its implementation among other challenges we find on the software and networks engineering of a federated social network.

Speaker Bio
-----------

I'm Diogo and I am a Computer Science student from University of Porto. I've a keen interest in scalable and federated software engineering and I'm the current lead developer of GNU social, a free software social networking platform. In it, I've implemented support for ActivityPub and ActivityStreams 2.0 - state-of-the-art W3C recommendations of 2018 and 2017, respectively) for federated social networks.

Links
-----

* Blog: https://blog.diogo.site/
* GitHub: https://github.com/diogogithub
* Photo: https://cv.diogo.site/face_cv.png

Extra Information
-----------------

This talk would be an adapted version of a seminar I gave at DCC-FCUP (Computer Science Department of the University of Porto) targeted at Network and Information Systems Engineering master students. The seminar resources were made available at https://www.diogo.site/projects/ActivityPub_seminar/ .

Major topics to be covered during the talk:

- The IndieWeb
- Briefing of OStatus
- WebFinger
- ActivityStreams
- Overview of the Actor model
- ActivityPub

At the end of this journey, we should be able to better understand some of the advantages of this kind of social platforms as well as some of the technical complications in their maintenance and conception.

### CODE REVIEW

**Comment by carlosefr** [comment]
You placed a "WIP" in the title. If we're not supposed to review this proposal as of right now, please remove the pull request and add it again later when you feel it's ready for review.

Or is it an actual proposal as of now?

**Comment by diogogithub** [comment]
It's an actual proposal, the WIP in the title was to indicate that it's a bit too soon to be sure that I'll be available anytime and that the "ToC" will be exactly the one in the proposal as I have to better adapt the original seminar and think of what will work best and which aspects are the most important. I think this is an important subject to have a talk about, given the increased interest and importance of federated systems and, in particular, the ActivityPub protocol.

As a sidenote: Unless a big chunk of the public in pixelscamp doesn't know portuguese, I believe the talk will be much better if I use portuguese, my fluency is higher and my accent is much more natural.

**Comment by carlosefr** [comment]
Thanks. Delivering the talk in portuguese is no problem, as long as it is mentioned beforehand.

We have one request though: you have line breaks in the middle of paragraphs in your proposal. Some markdown processors interpret that as a new paragraph and the text ends eu misformatted. Can you please fix this? (I've fixed it in the PR description above myself, but it needs changing in the `.md` file as well.)

**Comment by carlosefr** [comment]
Also, if you can shorten the title a bit, it would be welcomed.

Truncation in signage and other places won't do much damage as you wrote it, so you can keep it as is if you prefer.

**Comment by diogogithub** [comment]
@carlosefr Let me know if any other change is needed :)

**Comment by carlosefr** [comment]
When you change something in the `.md`, please remember to change it as well in the PR title/description (that's what our backoffice uses during the review process).

**Comment by carlosefr** [comment]
Would you consider extending your talk to 45 minutes + QA to avoid stage downtime? (All slots are 1 hour long).

**Comment by diogogithub** [comment]
Yes, that would be fine, I had the impression, based on the guidelines, that for it to be larger, I would have to make it a workshop. But that length actually makes it better :)

Do you want me to update the length to 1h?

**Comment by carlosefr** [comment]
If you please, yes.

**Comment by diogogithub** [comment]
@carlosefr Done! :smiley:

**Comment by carlosefr** [comment]
You proposal is still under review but, due to logistics constraints, we cannot guarantee any more stage slots at this moment. Until the **beginning of March** more slots are likely to become available and we will approve a few more proposals as we can, so this isn't a rejection notification.

We understand that delaying a decision reduces the time you have to prepare, shall your proposal turn out to be approved. So, if you need a decision from us until a particular date, please tell us by commenting here in this PR thread.

**Comment by carlosefr** [comment]
Congratulations @diogogithub, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
