### PR TITLE
Hey ho, let's GO!

### PR DESCRIPTION
**Pull request by renatosuero**
Hey ho, let's GO!
========================

* Speaker   : *Renato Suero*
* Available : *Any*
* Length    : *30 minutes*
* Language  : *Portuguese* 

Description
-----------

An introduction to GO, a language created by google. We’ll start by looking at the basic structure of code in GO, its packages. After that we’ll go through conditional structures and repetitions, collections, structs, functions, methods and interfaces. Finally we’ll check concurrency, tests and the gometalinter package, which helps producing high quality code.  
This talk is mainly intended for programmers who have only basic or even no knowledge of the language at all. The goal is to get people know the language and to help figure out where and when they can use GO.

-----------

Speaker Bio
-----------

The speaker has been a developer for over a decade, and has gone through projects on desktop, server, web, games and mobile. He’s very passionate about technology loves to watch tv shows.

Links
-----

* Twitter: https://twitter.com/@renatosuero
* Github: http://github.com/renatosuero

### CODE REVIEW

**Comment by carlosefr** [comment]
Even though it's OK for the talk to be in portuguese, the talk description should be in english, to match the communication language of the event and be universally readable in the event's schedule.

**Comment by celso** [comment]
Hi @renatosuero  , thanks for your proposal. Love the topic but we're going to need slightly better description for your talk (and in english please, read @carlosefr comment). Can you read "Make makes a good proposal?" and reevaluate your pitch?

https://github.com/PixelsCamp/talks

**Comment by renatosuero** [comment]
Hi @celso and @carlosefr thanks. I was very busy last week, I'll change that.

**Comment by renatosuero** [comment]
I updated my talk and I slightly change the focus. what do you think?

**Pull request merged**
