### PR TITLE
Javascript Will Kill You

### PR DESCRIPTION
**Pull request by Joao-Henrique**
Javascript Will Kill You
=================================================

* Speaker   : João Henrique
* Available : first day, second day and third day
* Length    : 45 minutes
* Language  : English

Description
-----------

A simple syntax, a large ecosystem, and a great community make Javascript one of the top programming languages of 2020. But don't be fooled by its ease of use! This is a tricky language and it has some nuances that if you are not careful, it can put you in serious trouble. In this talk, I will identify and explain some of the pitfalls of this amazing language and give you some precious knowledge that one day might probably save your life.

Speaker Bio
-----------

Developer Ambassador @TurbineKreuzberg (a German software agency for e-commerce and IoT). I was previously a Senior Lab Technician for an Environmental Analysis Laboratory for 12 years and in 2017 I quit my job to pursue a career in tech. Oh yeah and I'm also the Coding Portugal organizer, freeCodeCamp evangelist, and Toastmasters regular attendee.

Links
-----

* Blog: https://medium.com/@jrshenrique
* Company: https://turbinekreuzberg.com/
* GitHub: https://github.com/Joao-Henrique
* Photo: https://avatars1.githubusercontent.com/u/24846288?s=460&v=4

Extra Information
-----------------

In this talk, I will use humor to pinpoint some particularities of the language that are prone to mistakes and I will unveil (with some theory) what's going on "behind the hood". I have no recordings of my previous talks. I've been giving talks in meetups with less than 50 people and for 2020 I will be submitting talks for bigger events. I hope to have an opportunity at Pixels Camp and I will be available if you need any additional information.

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, thanks for the talk proposal. The only thing to point out is perhaps "fulled" should be "fooled" ;)

**Comment by Joao-Henrique** [comment]
Thanks for the heads up @carlosefr 😄

**Comment by carlosefr** [comment]
Hi, would you consider extending your talk to 45 minutes + QA or do you prefer to stick with 30 minutes? Slots are 1h long and we prefer to minimize downtime, if possible.

You can choose either way, this is not mandatory.

**Comment by Joao-Henrique** [comment]
Hi Carlos, yes I suppose I can easily add some addicional 15 minutes of content.

**Comment by carlosefr** [comment]
Congratulations @Joao-Henrique, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling worflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
