### PR TITLE
Leveling Up Your Team - Detect and Manage the Impostor Syndrome and the Dunning-Kruger Effect

### PR DESCRIPTION
**Pull request by RicCastelhano**
Leveling Up Your Team - Detect and Manage the Impostor Syndrome and the Dunning-Kruger Effect
=================================================

* Speaker   : Ricardo Castelhano
* Available : first day, second day, third day
* Length    : 45 minutes + QA
* Language  : Portuguese (might be in English if by attendees request

Description
-----------

Every software engineer lives between the range of Dunning-Kruger effect and Impostor Syndrome. Know what to look for and how to help your people to overcome it is key to leveling up your engineering team. I will illustrate this reality with my own personal story growing as a software engineer and a human.

Speaker Bio
-----------

I consider myself a creative and curious mind. I made my journey from Mathematics into Creative Computing, then into Web Development and lately to Management. I consider myself a people person, a good communicator, and a good listener. I prefer to play as a team, with a special taste for motivating and helping those around me to achieve better results. 

Links
-----

* Blog: http://ricardocastelhano.net
* Company: RUPEAL (InvoiceXpress, ClanHR, KWAN)
* GitHub: https://github.com/RicCastelhano
* Photo: http://ricardocastelhano.net/wp-content/uploads/2019/11/EU.jpg

Extra Information
-----------------

A shortlist of some past presentations I did.
http://ricardocastelhano.net/talks/
Some have links for the slidedeck or the session recordings.

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, thanks for the talk proposal.

Can you please shorten the title? If you can't make it at most half as short, it should at least be understandable after truncation (which will certainly happen in the schedule, signage and other places).

_Review note: This talk covers the same subject as PR #317._

**Comment by carlosefr** [comment]
Would you consider extending your talk to 45 minutes + QA to avoid stage downtime? (All slots are 1 hour long).

**Comment by RicCastelhano** [comment]
@carlosefr  sure, there is no problem with that.

**Comment by carlosefr** [comment]
You proposal is still under review but, due to logistics constraints, we cannot guarantee any more stage slots at this moment. Until the **beginning of March** more slots are likely to become available and we will approve a few more proposals as we can, so this isn't a rejection notification.

We understand that delaying a decision reduces the time you have to prepare, shall your proposal turn out to be approved. So, if you need a decision from us until a particular date, please tell us by commenting here in this PR thread.

**Pull request closed without merging**
