### PR TITLE
Quickly prototype Web apps with MEAN.js

### PR DESCRIPTION
**Pull request by ghost**
# Prototype Web apps with MEAN.js
- Speaker   : _David Ferreira_
- Available : _Any day_
- Length    : _30 minutes_
- Language  : _English_ or _Portuguese_
## Description

On a world where creating startups is getting high popularity, web developers find a certain difficulty to quick prototype a web app from the database, server and frontend. In this session will be shown how to do it quickly using the full-stack framework MEAN js. MEAN stands for Mongo + Express + Angular + Node.
## Speaker Bio

Programming enthusiast since 2004, when I build my first Javascript application to prompt the user’s name and to show: “Hello “+name, and since then I turned such hobby as my main professional area. I am passionate about working with server-side Javascript apps, with Node.JS. However at the moment I am looking for an Angular.JS role. I want to become an Angular expert, also get more knowledge about E2E and Unit testing. Recently I have been working on hybrid mobile applications using Javascript and HTML 5 for the biggest bank in the Netherlands.
## Links
- Twitter: https://www.twitter.com/daminufe
- Company: http://www.nondutch.nl
- Github: http://github.com/daminufe

### CODE REVIEW

**Comment by cdeath** [comment]
hey @daminufe!

the template file should not have been deleted.
can you fix it?

thanks!

**Comment by ghost** [comment]
Oops @nmpereira,
Sorry, I renamed the file instead of duplicating it.
Done now ;)

**Comment by celso** [comment]
Hi David, we need you to apply here so we can get your email etc to give you feedback on the talk review process: https://pixels.camp/apply/

Thanks!

**Comment by ghost** [comment]
Hi @celso 
Done.

**Pull request merged**
