### PR TITLE
Docker Compose for fearless developers

### PR DESCRIPTION
**Pull request by jbolila**
Docker Compose for fearless developers
========================

* Speaker   : João Bolila
* Available : 29th - no time restrictions
* Length    : 30min
* Language  : Portuguese (or English if has to be!)

Description
-----------

In this talk I'll guide the build of a development environment for an application with separate
containers, connected towards a reproducible end trusted environment from development to production.

For this I'll be using a web application with three containers, a frontend running Nginx,
a Swagger API on NodeJS and a database (PostgreSQL or ElasticSearch).

Let's improve our relation with devOps team for good!

---------------

Speaker Bio
-----------

Well I'm here! .. and [there](https://www.linkedin.com/in/jo%C3%A3o-bolila-b406262a/)

Links
-----

* Company: http://idirect.net
* Github: http://github.com/jbolila

### CODE REVIEW

**Comment by carlosefr** [comment]
> When you're ready, submit a pull request and **comment using your markdown file contents**.

Can you please add the proposal markdown to the first comment? Thanks.

**Comment by jbolila** [comment]
Sorry, I'm a bit lost here, what it means comment in this context?

**Comment by carlosefr** [comment]
Where you wrote "for a small space, please" should be the full contents of the talk proposal.

The purpose of this is for people not to have to read the diff. 😄

**Comment by jbolila** [comment]
That is in the markdown file on this PR.

**Comment by carlosefr** [comment]
It is, but should be duplicated in the first comment of the PR. We use the markdown file for handling the proposal acceptance process, but other people should be able to come to this PR and see what the talk is about without having to look at the PR's diff.

**Comment by jbolila** [comment]
Docker Compose for fearless developers
========================

* Speaker   : João Bolila
* Available : 29th - no time restrictions
* Length    : 30min
* Language  : Portuguese (or English if has to be!)

Description
-----------

In this talk I'll guide the build of a development environment for an application with separate
containers, connected towards a reproducible end trusted environment from development to production.

For this I'll be using a web application with three containers, a frontend running Nginx,
a Swagger API on NodeJS and a database (PostgreSQL or ElasticSearch).

Let's improve our relation with devOps team for good!

---------------


Speaker Bio
-----------

Well I'm here! .. and [there](https://www.linkedin.com/in/jo%C3%A3o-bolila-b406262a/)

Links
-----


* Company: http://idirect.net
* Github: http://github.com/jbolila

**Comment by carlosefr** [comment]
Took the liberty to edit your last comment into the first comment.

**Comment by celso** [comment]
Hi @jbolila , thanks for your proposal. We're going to need slightly better description for your talk. Can you read "Make makes a good proposal?" and reevaluate your pitch?

https://github.com/PixelsCamp/talks

**Pull request merged**
