### PR TITLE
Beyond REST: GraphQL vs gRPC Web

### PR DESCRIPTION
**Pull request by urakozz**
Beyond REST: GraphQL vs gRPC Web
=================================================

* Speaker   : **Yury Kozyrev**
* Available : **all days**
* Length    : **45min + 15min QA**
* Language  : **English**

Description
-----------

Over a decade REST was the main communication protocol between Frontend and Backend. But things are changing and in 2020 we have enough options that are mature to use in production in a company or fun enough to try out in a startup.

Over the past year, I've got involved in multiple projects with different needs and different development stages (and different amounts of the legacy code) and had a chance to gain experience in designing communication schemes between frontend and backend apps and gained the hands-on experience leading the implementation.

In this talk, I'd like to cover the pros and cons in a short- and long-run of:
- Old good REST JSON-based communication
- Modern GraphQL
- gRPC coming to WEB after it became nearly a gold standard of backend microservices communication
- **Bonus**: Backendless options like self-hosted CouchBase or fancy cloud Firebase (offering auth, realtime data synchronization, and other perks)

I will then discuss the hidden and known pitfalls of these technologies that you might encounter and ways to avoid them.

Speaker Bio
-----------

I'm leading a cross-functional engineering team at Travel Audience, working mainly with Go and React.
I worked at e-commerce, AdTech and FinTech companies including Russian tech giant Yandex where contributed to high-load business-critical solutions and designed multi-layered service architecture.

I'm passionate about developing well-crafted end-to-end software while trying to make work more fun for developers and delivering direct business value.

Links
-----

* Company: https://travelaudience.com
* GitHub: https://github.com/urakozz
* Photo: https://avatars0.githubusercontent.com/u/5797393?s=460&v=4

Extra Information
-----------------

The Pixels Camp 2019 gave me a big boost and a lot of inspiration, and this year I would like to contribute to better decisions in development by giving a talk, although I'm jumping on the last day.

I'm passionate about building beautiful and efficient architectures and services and would be happy to share my experience!

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, thanks for the proposal.

Can you please edit your PR description and `.md` file? There are some typos in there and the title cannot have the italic markup.

Also, if you don't mind extending your talk to 45 minutes, we'd prefer if you removed the 30 minutes option as well.

**Comment by urakozz** [comment]
@carlosefr Thank you for the feedback, I updated the text

**Comment by carlosefr** [comment]
Thanks.

I have one more suggestion though: the title could be made a little more appealing. Something like "Beyond REST". This is completely up to you, of course, it's OK as it is.

**Comment by urakozz** [comment]
You right, I will try to improve it

**Comment by urakozz** [comment]
@carlosefr After a brainstorming session we've got this name inspired by your suggestion, thank you for the feedback!

**Comment by carlosefr** [comment]
Congratulations @urakozz, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by urakozz** [comment]
@carlosefr 
image

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
