### PR TITLE
Terraforming cloud cubed worlds - with one-liners and whimsy

### PR DESCRIPTION
**Pull request by joaoanes**
Terraforming cloud cubed worlds - with one-liners and whimsy
=================================================

* Speaker   : João Anes
* Available : Any, special preference for second or third day
* Length    : 1 hour
* Language  : English

Description
-----------
Hello friend! Are you frustrated with the state of cloud providers dashboard interfaces, ever changing in their designs but always stuck in their ways? Or do you feel like a monkey pressing buttons when you should be Bob the Builder with a god complex? Behold, the gospel of Terraform.

In this talk, I'll demonstrate the ease, comfort and sheer futurism that is managing cloud architecture with Terraform, and I'll do so by pulling an entire managed Minecraft server out of my magic hat, filled with endless goodies like pre-set regular backups to AWS S3 Glacier, provisioning via bash scripts (with a dash of Docker), DNS management via Route53, even a static site in S3. All this, with a simple flick of the wrist... after writing down and executing, step by step (so that everybody follows along!), what we want our final result to look like.

Come along on our ride, and learn the sci-fi ways of cloud management today - so that you can `terraform apply` your own future tomorrow!

Speaker Bio
-----------

Hi, thanks for reading this! I've been developing software since I graduated from FEUP in '14, with a knack and passion for development, system analysis, automation but mostly quirky retorts. I've dabbled in AR/VR, mobile, devops and product development, and you'll find me either drifting through the tubes online, poking around and looking for leaks, staring in awe at my AWS billing report or just passed out on the nearest couch!

Links
-----

* Company: https://company.fractal.id
* GitHub: https://github.com/joaoanes
* Photo: https://avatars0.githubusercontent.com/u/240720

Extra Information
-----------------

Given all that above, what _is_ this magic wand I keep waving around really? It's Hashicorp Terraform! It's the tool that powers this entire endeavour - it allows you to write down what you want your infrastructure to look like in text files (infrastructure source control for free!), then with a simple wave of the wand, it goes out and presses all the buttons on the cloud interfaces for you - no more sprained fingers and no more frustration!

We'll also scout ahead when necessary what alternative paths we could take (like provisioning with Docker and AWS ECR Fargate instead of using EC2 instances with finnicky bash scripts, or using different terraform providers instead of shilling AWS, or simply cheating and pulling from `awesome-terraform` modules we'd like) in our adventure, so you can imagine what you'd like to do different!

Now, since everybody likes automation but nobody likes waiting for automatons (plus I'm not running terraform on the pixels camp wifi 😅), I'll be pulling some stage magic and cooking-show-quality timeskips in-between steps, but the idea is for everyone to be able to follow along as we write the server of our dreams and see the effects "immediately" in action.

All artifacts from this talk will also be on Github, so that you can pull them into your computer and create something equally magical - again with a flick of the wrist, but this time, your own.

Handy links!
1. [Hashicorp Terraform](https://www.terraform.io)
1. [Terraform Providers docs reference](https://www.terraform.io/docs/providers/index.html)
1. [Terraform AWS Provider (we'll be using this)](https://www.terraform.io/docs/providers/aws/index.html)
1. [AWS - Amazon Web Services. I promise I'm not a paid shill](https://aws.amazon.com/)
1. [Here's what Minecraft is, in case you just left the rock you've slept for 12 years under](https://www.minecraft.net/)

### CODE REVIEW

**Comment by joaoanes** [comment]
My forked repository is still called `pixels_camp_2016_talks` 🙈

**Comment by carlosefr** [comment]
Congratulations @joaoanes, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Comment by joaoanes** [comment]
I saw, thanks to you and the team for trying to keep it alive and beating, it was quite an effort. I'm sure the sponsor cancellation talks were awkward as all hell.

Best of luck, hope to be resubmitting this soon 😄

**Pull request merged**
