### PR TITLE
Odoo - The Open Source Business Apps Platform

### PR DESCRIPTION
**Pull request by dreispt**
# Odoo - The Open Source Business Apps Platform For The 21st Century
- Speaker   : Daniel Reis
- Available : October 8th, any hour
- Length    : 30 mins should be fine
## Description

Business processes are tricky.

Robust apps are hard to build.

Web frameworks are great to build the perfect front end,
but not very helpful at _tying all the pieces together in the backend_.

Get that out of the way: _let the Odoo framework do the heavy lifting_ for you,
and _focus at excelling on your business idea_.

Odoo, formerly known as OpenERP, is a rapid application development framework,
a the business apps platform, and a CRM/ERP/eCommerce product.

It is an open source project, created and driven the the Belgian company
with the same name, with the key distinctive feature that it is
_built to be extended_: at the view, model and business logic
layers.

The net effect of this was the growth of a _vibrant community_ around it,
with _thousand of extension modules already available, both free and
paid_. The community leaders joined together to found the Odoo Community Association,
a non-profit organization to organize collaboration and actively promote _quality
open source modules_.

Odoo is a modern and rich platform that can provide a huge headstart
to build a software application solutions, either by _leveraging the RAD
features on a prototype phase_, or it's _robustness and scalability at the business operation phase_.

As an interesting reference, the largest Odoo/OpenERP installation in the world is at the Portuguese
Education Ministry, with 500k users and the deployment of more than 200 apps.

The goal for this talk is to provide an introduction and overview to Odoo,
to _help enterpreneurs to consider and evaluate Odoo as a
possible component to implementation of their business idea_.

<del>And of course, sell a few more books.</del>

## Speaker Bio

Daniel is an open source enthusiast, actively engaged in the Odoo
Community. Is a member of the Odoo Community Association (OCA),
and the representative for the Project & Service Steering Commitee and
for the Portuguese Localization project.

Has been regular speaker at the Odoo Days/Odoo Experience annual conference, and
at other events suchs as the portuguese Linux Event.

Authored the "Odoo Development Essentials" book and is co-author of
the "Odoo Development Cookbook" book.

Is currently responsible for IT Applications at Securitas Portugal,
and partner at ThinkOpen Solutions, the portuguese reference Odoo
integrator.

Daniel has an Applied Math degree from ISEG/UTL, and a Master in
Business Administration from the ISCTE/IUL Business School.
## Links
- Blog: http://essentials.odoo.com
- Company: http://thinkopen.solutions
- Twitter: https://twitter.com/reis_pt
- Github: http://github.com/dreispt
- email: dgreis at sapo dot pt

Some previous talks:
- ["Desafios para um ERP em Código
  Aberto"](https://www.youtube.com/watch?v=SUC8kYURRdk), Evento Linux
  2015
- ["Bending the Odoo Learning
  Curve"](http://www.slideshare.net/dreispt/bending-the-odoo-learning-curve-odoo-experience-2015), Odoo Experience 2015
- ["Service Management with
  Odoo/OpenERP"](http://www.slideshare.net/dreispt/service-management-with-odooopenerpopendays2014danielreis),
  Odoo Days 2014
- ["Using the `pip` package manager for
  Odoo"](http://www.slideshare.net/dreispt/pip-installation-opendays2014danielreis),
  Odoo Days 2014

### CODE REVIEW

**Comment by celso** [comment]
Odoo - The Open Source Business Apps Platform For The 21st Century
==================================================================

* Speaker   : Daniel Reis
* Available : October 8th, any hour
* Length    : 30 mins should be fine


Description
-----------

Business processes are tricky.

Robust apps are hard to build.

Web frameworks are great to build the perfect front end,
but not very helpful at *tying all the pieces together in the backend*.

Get that out of the way: *let the Odoo framework do the heavy lifting* for you,
and *focus at excelling on your business idea*.

Odoo, formerly known as OpenERP, is a rapid application development framework,
a the business apps platform, and a CRM/ERP/eCommerce product.

It is an open source project, created and driven the the Belgian company
with the same name, with the key distinctive feature that it is
*built to be extended*: at the view, model and business logic
layers.

The net effect of this was the growth of a *vibrant community* around it,
with *thousand of extension modules already available, both free and
paid*. The community leaders joined together to found the Odoo Community Association,
a non-profit organization to organize collaboration and actively promote *quality
open source modules*.

Odoo is a modern and rich platform that can provide a huge headstart
to build a software application solutions, either by *leveraging the RAD
features on a prototype phase*, or it's *robustness and scalability at the business operation phase*.

As an interesting reference, the largest Odoo/OpenERP installation in the world is at the Portuguese
Education Ministry, with 500k users and the deployment of more than 200 apps.

The goal for this talk is to provide an introduction and overview to Odoo,
to *help enterpreneurs to consider and evaluate Odoo as a
possible component to implementation of their business idea*.

<del>And of course, sell a few more books.</del>


Speaker Bio
-----------

Daniel is an open source enthusiast, actively engaged in the Odoo
Community. Is a member of the Odoo Community Association (OCA),
and the representative for the Project & Service Steering Commitee and
for the Portuguese Localization project.

Has been regular speaker at the Odoo Days/Odoo Experience annual conference, and
at other events suchs as the portuguese Linux Event.

Authored the "Odoo Development Essentials" book and is co-author of
the "Odoo Development Cookbook" book.

Is currently responsible for IT Applications at Securitas Portugal,
and partner at ThinkOpen Solutions, the portuguese reference Odoo
integrator.

Daniel has an Applied Math degree from ISEG/UTL, and a Master in
Business Administration from the ISCTE/IUL Business School.


Links
-----

* Blog: http://essentials.odoo.com
* Company: http://thinkopen.solutions
* Twitter: https://twitter.com/reis_pt
* Github: http://github.com/dreispt
* email: dgreis at sapo dot pt


Some previous talks:

* ["Desafios para um ERP em Código
  Aberto"](https://www.youtube.com/watch?v=SUC8kYURRdk), Evento Linux
  2015
* ["Bending the Odoo Learning
  Curve"](http://www.slideshare.net/dreispt/bending-the-odoo-learning-curve-odoo-experience-2015), Odoo Experience 2015
* ["Service Management with
  Odoo/OpenERP"](http://www.slideshare.net/dreispt/service-management-with-odooopenerpopendays2014danielreis),
  Odoo Days 2014
* ["Using the `pip` package manager for
  Odoo"](http://www.slideshare.net/dreispt/pip-installation-opendays2014danielreis),
  Odoo Days 2014

**Comment by celso** [comment]
Hi Daniel, we need you to apply here so we can get your email etc to give you feedback on the talk review process: https://pixels.camp/apply/

Thanks!

**Comment by dreispt** [comment]
@celso OK, I just did that.

**Comment by celso** [comment]
@dreispt Yes you did, and now you have another email you need to reply, check you inbox :)

**Pull request merged**
