### PR TITLE
Beyond Code: thinking "right" to become a better Engineer

### PR DESCRIPTION
**Pull request by pragmapilot**
Beyond Code: thinking "right" to become a better Engineer
==========================================

* Speaker   : Rodrigo Gonçalves
* Available : 21/Mar 14:00 - 20:00 or 22/Mar 14:00 - 20:00
* Length    : 45m
* Language  : English 

Description
-----------

Being a solid SW Engineer is much more than just writing good code, knowing the latest languages or be aware of the hottest trends. Your career goals and the companies you work for also shape your future as they define much of the path you'll thread. There's always something to be learned with everyone that crosses your path with or in your current role. Sometimes these lessons aren't easy on us or the ones we'd like to learn but there's certainly virtue in accepting with grace and gratitude.

Speaker Bio
-----------

12y of experience Software Engineer turned into Engineering Manager. Past lifes in iOS, Android, Web, APIs and desktop systems. INFJ, people lover, perpetual learner and true believer in the human ability of growing and improving.

Links
-----

* Company: https://www.talkdesk.com/
* GitHub: https://github.com/pragmapilot

Extra Information
-----------------

In this talk I intend to cover other aspects that make a solid Engineer beside the ability to write to code. These include how you communicate, how you empathise, how you understand business decisions, how you ask the right questions and your attitude. I believe in a holistic view of the Software Engineer that is able to face the challenges of career and workability by using his/her entire potential of being a Human Being. Throughout the talk I'll discuss some hard challenges I was faced with during my working experience, tell about how sometimes I thought I had "screwed up big time" only to be able to "connect the dots" some years later. I'll also be sharing some approaches I took to improve myself as an Engineer and how all my tenures in "sometimes-not-so-glamorous" companies help me strengthening my wholeness as an Engineer. Disclaimer: no Human Beings or Companies will be harmed during my presentation.

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi Rodrigo,

Your proposal arrived past the deadline. This doesn't mean it's rejected, just that (when in doubt) other talks will get priority. It also means its approval (if it indeed happens) may happen much closer to the event.

The exception to this rule are talks that were already known to us by means other than GitHub.

Also, your talk title is kind on the long side. Can you shorten it?

**Comment by pragmapilot** [comment]
Hi @carlosefr 

Thanks for getting back to me. 

I've shortened the title as requested.

**Comment by carlosefr** [comment]
Please update the PR description/title as well, it's what our backoffice uses during the reviewing process.

**Comment by pragmapilot** [comment]
Thanks for clarifying @carlosefr. It seems to be compliant now.

**Pull request merged**
