### PR TITLE
Crystal

### PR DESCRIPTION
**Pull request by zamith**
Crystal is a typed, `LLVM` compiled language that reads (mostly) as Ruby.

If you've ever faced a problem in which you would like to use Ruby (because it
is awesome), but it is just not performant enough, maybe Crystal is the solution
you've been looking for.

Crystal's standard lib comes bundled with support for `WebSockets`, `OAuth`, `MySQL`,
and other nice utilities. It has a very simple testing framework, dependency
management system, and even the beginnings of a web framework.

This is a very exciting time to come aboard the Crystal train, especially coming
from a Ruby background.

### CODE REVIEW

**Comment by celso** [comment]
Hi Zamith, can you use the provided template for talks please? https://github.com/PixelsCamp/pixels_camp_2016_talks/blob/master/my-awesome-talk_my-name.md

**Comment by zamith** [comment]
I did. If you look at the file on the commit it is in that format. I just didn't do it in the PR message.

**Comment by celso** [comment]
Ok, you need to use the same markup in the pr message.

**Comment by celso** [comment]
Hi @zamith Unfortunately, we're out of slots in the calendar now and we need to take some tough decisions. Thank for you submission. We'll reopen your PR if a new slot emerges.

**Pull request closed without merging**
