### PR TITLE
Demystifying the Tribe Model

### PR DESCRIPTION
**Pull request by cristianocorreia**
Demystifying the Tribe Model
=========================

* Speaker   : Cristiano Correia
* Available : Both days, any time
* Length    : 45 minutes + QA
* Language  : English

Description
-----------
**Demystifying the Tribe Model**

The Spotify Tribe Model is THE buzz-word of the Agile world and a lot of organizations consider using it.

Having experienced a form of it on first-hand on one of the largest organizations in the world, gave me a sense on how this can help or hurt an organization.

Although Scrum is the most common framework, it might not be the best solution for big scalable teams and the Spotify Tribe Model comes as answer to that.

What it is, where it started, who should use it, why and when should you consider it: The 5Ws of the Tribe Model.

Speaker Bio
-----------

**Cristiano Correia**

Cristiano Correia

With a background in engineering and design, my focus has always been building great products and great experiences.

I've been working continuously as a Frontend Engineer and UX Designer since 2012 across Portugal, Belgium, The Netherlands and Germany on a multitude of roles ranging from design, development and management. Currently I'm a Scrum Master at Critical TechWorks (a BMW Group & Critical Software company) and a tutor at EDIT.

Having contributed to and used multiple Design Systems, that's my favorite way of mixing both of my backgrounds on a project. I also have a soft spot for Accessibility and I'm always focused on trying to deliver in the most Agile way.

Links
-----

* Company: [Critical TechWorks (a BMW Group & Critical Software company)](https://www.criticaltechworks.com/)
* GitHub: [github.com/cristianocorreia](https://github.com/cristianocorreia)

Extra Information
-----------------

Previous organizing, speaking and training appearances:
* Tutor: [Digital Project Management](https://edit.com.pt/formacao/curso-intensivo-digital-project-management-projetos-digitais-lisboa/) (Dec 2019 - Jan 2020 - EDIT. Disruptive Digital Education)
* Organizer: [Agile Connect Lisbon](https://www.meetup.com/pt-BR/Agile-Connect-Lisbon/) (Aug 2019 - present)
* Speaker: [Demystifying the Tribe Model](http://meetu.ps/e/GWZFR/w6zSF/d) (Jul 2019 - Agile Connect Lisbon)
* Speaker: [a11y, who?](https://techinporto.com/) (Jun 2019 - Tech In Porto)
* Tutor: [Digital Project Management](https://edit.com.pt/formacao/curso-intensivo-digital-project-management-projetos-digitais-lisboa/) (May 2019 - EDIT. Disruptive Digital Education)
* Tutor: [JavaScript Crash Course](https://edit.com.pt/formacao/workshop-javascript-crash-course-lisboa/) (Apr 2019 - EDIT. Disruptive Digital Education)
* Speaker: [a11y, who?](https://pixels.camp/cristianocorreia) (Mar 2019 - Pixels Camp)
* Teacher Assistant: [WE/CODE Women Edition Lisbon 2019](https://www.startuplisboa.com/upcoming-events-1/wecodeironhack) (Feb 2019 - Ironhack)
* Speaker: [All Paths Lead to UX](https://www.meetup.com/ironhack-lisbon/events/258125917/) (Jan 2019 - Ironhack)
* Speaker: [Styling Accessibility: A Web Components Approach](https://www.meetup.com/landing_jobs/events/256720438/) (Dec 2018 - Landing.jobs Meetup)
* Trainer: [Principles of User Experience](http://academy.findmore.pt/learning-areas/development/principles-of-user-experience-ux) (Jul 2017 - Findmore Academy)
* Trainer: [Introduction to AngularJs](http://academy.findmore.pt/learning-areas/development/introduction-to-angularjs) (May 2017 - Findmore Academy)
* Speaker: [E2E Testing](https://www.meetup.com/de-DE/Angular-Belgium/events/235752358/) (Nov 2016 - Angular Belgium Meetup)
* Trainer: [Thinking In AngularJS With A JQuery Background](http://academy.findmore.pt/learning-areas/development/thinking-in-angularjs-with-a-jquery-background) (Apr 2016 - Findmore Academy)
* Trainer: [HTML5 Overview](http://academy.findmore.pt/learning-areas/development/html5-overview
) (May 2015 - Findmore Academy)
* Trainer: [AngularJS Fundamentals](http://academy.findmore.pt/learning-areas/development/angularjs-fundamentals-new-session) (Apr 2015 - Findmore Academy)
* Trainer: [AngularJS Fundamentals](http://academy.findmore.pt/learning-areas/development/angularjs-fundamentals
) (Mar 2015 - Findmore Academy)

Published articles:

* [A Day in the Life of a Frontend Engineer at Zalando](https://jobs.zalando.com/tech/blog/frontend-engineer-zalando/) (Jan 2019 - [Zalando Tech Blog](https://jobs.zalando.com/tech/blog/))
* [How to Style Accessibility: a Web Components Approach](https://medium.freecodecamp.org/styling-accessibility-a-web-components-approach-dc2aa8123eb2) (Dec 2018 - [freeCodeCamp]())

### CODE REVIEW

**Comment by carlosefr** [comment]
Can you please remove the link from the speaker attribute (you can move it to the links section if you wish).

**Comment by cristianocorreia** [comment]
@carlosefr issue addressed.

**Comment by carlosefr** [comment]
Congratulations @cristianocorreia, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

We're considering this talk as sponsored by the **Agile Connect** meetup.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
