### PR TITLE
Processing Text with Machine Learning

### PR DESCRIPTION
**Pull request by FabianReich**
Processing Text with Machine Learning.
=================================================

* Speaker   : Fabian Reich
* Available : first & second day
* Length    : 45min + QnA
* Language  : English

Description
-----------

Lately, it seems like everyone is talking about Artificial Intelligence, Machine Learning (ML), Deep Learning…
When this hype started, I got a little stressed by all these new terms. What does it all mean for me as a developer?

In this talk we will end the confusion and look at some of the ML fundamentals.
We will be learning the fundamentals by building a simple sentiment classifier.
A sentiment classifier can determine whether a written review was positive or negative.
The goal is not to make you a data scientist, but to teach you some of the ML fundamentals.
You will get a better idea of which of your problems might be solved by using ML.

Speaker Bio
-----------

Computer Scientist turned Data Scientist (Hoppfully not the dark side).

During my career I had the big chance to work in the research center of SAP in the Sillicon Vally.
Hence my specialization in the Natural Language Processing/Machine Learning area.

Because I am convinced that AI can solve new kinds of problems, I  co-founded a German Startup called AI-Coaching(www.coach-bot.de).
Which focuses on how we can coach people to help them learn social skills using Coach-Bots(Chatbots focusing on Coaching).

Links
-----

* Blog: www.fabian-reich.de
* Company: AI Coaching (www.coach-bot.de)
* LinkedIn: https://www.linkedin.com/in/fabianreich/
* GitHub: https://github.com/FabianReich
* Photo: http://fabian-reich.de/img/Fabian_Reich_Headshot.png

Extra Information
-----------------

I gave the same talk on DEV DAY 2019 in Faro and it was well received (accroding to the hosts).

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi Fabian,

Can you please rename your `.md` proposal to match the template? Also, I'd suggest reducing the talk title to something more resilient to truncation (which will happen in signage and the calendar), like "Processing Text with Machine Learning" or "Machine Learning in Text Processing".

**Comment by FabianReich** [comment]
@carlosefr Thanks for the input, I changed the title and file-name.

**Comment by carlosefr** [comment]
Almost... Can you please add an `.md`extension to the file name? :)

**Comment by FabianReich** [comment]
Your right the title is too long, I didn't see that the .md is missing :D
Is fixed now.

**Comment by meddulla** [comment]
Congratulations @FabianReich, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
