### PR TITLE
OWASP Juice Shop - First you :-D:-D then you :,-(

### PR DESCRIPTION
**Pull request by bkimminich**
OWASP Juice Shop - First you :-D:-D then you :,-(
=============================================

* Speaker : [Bjoern Kimminich](https://pixels.camp/bkimminich)
* Available: Thursday 3pm or later, Friday all day
* Length : 60 min (incl. demo and Q&A)
* Language : English

Description
-----------

OWASP Juice Shop is an intentionally insecure webapp for security
trainings written entirely in Javascript which encompasses the entire
OWASP Top Ten and many more severe and complex security flaws.

In this talk, you'll learn about this open-source project and its
capabilities first-hand from its creator. You are invited on a happy
shopper round trip and will have the chance to see some hacking demos of
several of the built-in challenges. You'll also witness how to apply
custom themes to the Juice Shop to make it your company's next security
awareness super-weapon. Last but not least, you will experience how to
set up a capture-the-flag (CTF) event with the Juice Shop in less than 5
minutes!

Speaker Bio
-----------

**Bjoern Kimminich**

Speaker Image

Björn Kimminich is responsible for global IT architecture and
application security at [Kuehne + Nagel](https://kuehne-nagel.com). On
the side, he gives IT security lectures at the non-profit private
university [Nordakademie](https://www.nordakademie.de/). Björn also is
the project leader of the [OWASP Juice Shop](http://owasp-juice.shop)
and a board member for the
[German OWASP chapter](https://www.owasp.org/index.php/Germany).

Links
-----

* Company: [OWASP](https://www.owasp.org)
* GitHub: https://github.com/bkimminich
* Twitter: https://twitter.com/bkimminich

Click [here][1] to see the full calendar and pick your favorite talks

[1]: https://pixels.camp/schedule

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi Björn,

Can you please update the proposal (and the PR description) with your availability? This is necessary for our backoffice.

Also, can you remove emojis from the talk title? It's not a problem to have them in the description, but not the title due to signage and calendar restrictions.

**Comment by bkimminich** [comment]
My availability is Thursday afternoon or Friday all day.

**Comment by carlosefr** [comment]
Yes, I undestand that, but the proposal template has an "availability" filed that must be filled so that we can track that information in the event's backoffice (we use GitHub for the proposals, but they are managed via our backoffice once accepted).

**Comment by bkimminich** [comment]
Aaah, I copied an existing proposal, that probably didn't have this field any more. Will fix this later today!

**Comment by bkimminich** [comment]
I can find no template file named like mentioned in the README in this repository. Can you send me an example where this information is present so I can copy it? Thanks!

**Comment by carlosefr** [comment]
Ah, it went missing, sorry. It's here: https://github.com/PixelsCamp/talks/blob/master/talk-title_presenter_name.md

**Comment by bkimminich** [comment]
Okay @carlosefr, all should be fixed now!

**Comment by carlosefr** [comment]
It is, thanks.

**Pull request merged**
