### PR TITLE
An open source Bitcoin ATM

### PR DESCRIPTION
**Pull request by 21isenough**
An open source Bitcoin ATM
=================================================

* Speaker   : @21isenough
* Available : all days
* Length    : 45 minutes
* Language  : English

Description
-----------

I built an open source Bitcoin ATM. Throw 2 cents (or any other denomination) into the ATM and receive Bitcoin straight to your mobile Bitcoin wallet. It leverages the power of the Lightning Network - a second layer solution to bitcoins strong and secure base protocol.

Forget about the clunky and heavy machines in every other street - this is the new generation of ATMs. Not only will I talk about all the technical details and what hardware is being used for this ATM but I will also elaborate on the possibilities such a project can have on a global scale for the adoption of bitcoin.

Speaker Bio
-----------

I'm a bitcoin enthusiast and I breathe bitcoin. The fascination reaches from its technical underpinnings to the history of money to economic theories. Never in my life have I been so fascinated and bedazzled by one topic and all its implications.

We need a uncorrupted form of money, free from government intervention. Bitcoin makes this possible and is the most promising solution to this problem.

Links
-----

* GitHub: https://github.com/21isenough
* Photo: https://avatars0.githubusercontent.com/u/39227503?s=460&v=4

Extra Information
-----------------

The responses I got from the Bitcoin community after publishing my open source Bitcoin ATM, were quite overwhelming. There is clearly a need for this! Would be great to spread the word about it farther and wider. 

https://twitter.com/21isenough/status/1170808396955738114?s=20
https://www.reddit.com/r/Bitcoin/comments/d1hx12/i_built_a_lightning_atm_build_your_own/

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, Thanks for the talk proposal.

Since you're not using your real identity (and I couldn't find it in the extra information you provided), will you consider using it later on in the process or prefer to use only your online handle and avatar?

We have had speakers in the past using avatars instead of real photos but, IIRC, talks have always been under the speaker's real name.

**Comment by 21isenough** [comment]
Hi @carlosefr 

Thank you for your response. 

Yes, I would prefer to only use my online handle and avatar since that is how people know me and how I connect with others :-) My name doesn't add any benefit in this regard and I'm quite happy with my pseudonym.

**Comment by carlosefr** [comment]
Ok, thank you for the clarification.

I understand your choice but, as I mentioned above, we haven't had a speaker give a talk under a pseudonym before and that is something we will have to take under consideration for the selection process.

**Comment by 21isenough** [comment]
That is absolutely fair :+1:  I will respect your decision however you choose to handle this.

**Comment by carlosefr** [comment]
Although we prefer real names, we respect your choice to use a pseudonym and it won't weight negatively on whether your talk proposal gets approved.

However, applying as an attendee is a requirement for having a talk accepted and in that process we do require identity disclosure. You can add it to your private pitch, which is used only by the core organizers and isn't shared with any outside entity (eg. sponsors).

Are you OK with this?

**Comment by 21isenough** [comment]
Hi @carlosefr 

I'm very pleased and delighted about these news - thank you. Yes, sharing my information with the core organizers would be fine with me :+1:

**Comment by carlosefr** [comment]
Congratulations @21isenough, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling worflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by 21isenough** [comment]
On the new date, I could present. Would be pleased to do so :-)

**Comment by 21isenough** [comment]
Hello Pixels Team!

Quick heads up: My talk proposal that was "pre-approved" was later set to "cant-present" due to a collision in my schedule. The new date, however, works very well for me. In march I've been informed that "at this point it's most likely that we will also consider cancelled-after-accepted talks".

Is this confirmed yet? Would love to be part of this :-D

**Comment by carlosefr** [comment]
We will handle `cant-present` talks as if they haven't been canceled, as long as we can fit them in the schedule, yes.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request closed without merging**
