### PR TITLE
Right to Repair (fix your broken device!)

### PR DESCRIPTION
**Pull request by luisfcorreia**
Right to Repair (fix your broken device!)
=========================

* Speaker   : Luis Correia
* Available : whenever you need it to be
* Length    : 45(ish) minutes
* Language  : English (probably)

Description
-----------

Ever had a device fail on you? Like, a tablet, smartphone, dishwasher, hair dryer, you name it!

The thing is, it is most likely you just threw it away, thinking it was beyond repair.

Phear not, in most cases, it *is* repairable (with notable exceptions) and you can give it an extra life.

Unfortunately, most gadget makers don't want you to repair but rather buy a new one. And they even lock the device down so hard you basicly can't do much with it. 

Come hear me talk about it to know more

Speaker Bio
-----------

Speaker Image

Legendary bicopter/tricopter builder, member of the fine One Over Zero community, mostly known as the "lobster crew"
Co-creator of OOZLabs, a closed maker group that essentially makes things and stuff.

Links
-----

* Blog: http://blog.loide.net
* Company: http://labs.oneoverzero.org
* Github: https://github.com/oozlabs / https://github.com/luisfcorreia
* Contact: buga@loide.net

Extra Information
-----------------

I usually prepare talks about things I've make (or tried to make it work), this time this is about fixing stuff.

Past talks @ PixelsCamp https://github.com/PixelsCamp/talks/blob/master/2016/ooz2mars-rover_luis-correia.md

### CODE REVIEW

**Comment by edevil** [comment]
Hello Luís. Thank you for the talk proposal.

Could you please add a little more info to the talk description? Maybe a list of topics that will be covered... We believe that the attendees would benefit from this.

Thank you.

**Comment by luisfcorreia** [comment]
Added a topic list
Will clarify further if needed

**Comment by carlosefr** [comment]
Can you try to shorten the title a bit, so that it doesn't get truncated in the calendar?

**Comment by luisfcorreia** [comment]
title shortened as suggested

**Comment by luisfcorreia** [comment]
added image link

**Pull request merged**
