### PR TITLE
Aiming for delight in Customer Experience

### PR DESCRIPTION
**Pull request by bscruzpt**
Aiming for delight in Customer Experience
=========================================

* Speaker   : Bruno Cruz
* Length    : 60 minutes
* Language  : English
 
Description
-----------

Each and every day, the delight we create when successfully helping clients reach their goals contributes to a great Customer Experience. This, in turn, becomes a driver towards retention and promotion, with clients referring you to others.

In this talk, I'll go over what Customer Experience is and how each team helps improve it. During it, I'll also share my views on how Support becomes a major factor, from the way your engineers attend to client requests, resolution times and SLA upkeep.

Speaker Bio
-----------

**Bruno Cruz**

Bruno Cruz

Started out as a Java backend engineer developing white-label telecom products. Eventually became responsible for their delivery to a major telecom company, ensuring they reliably served millions of users. With daily contact with clients, I decided to explore Customer Support, which brought upon new challenges and obstacles. These days, I'm a team lead on Feedzai's awesome Support team! 

Links
-----

* Company: [Feedzai](https://feedzai.com/)
* LinkedIn: [bscruzpt](https://www.linkedin.com/in/bscruzpt/)
* GitHub: [bscruzpt](https://github.com/bscruzpt/)
* Pixels Camp: [bscruzpt](https://pixels.camp/bscruzpt)

Click [here][1] to see the full calendar and pick your favorite talks

[1]: https://pixels.camp/schedule/

### CODE REVIEW

**Comment by bscruzpt** [comment]
Hello!

Sorry for the bother, but it's my first time doing this. I've noticed my proposed talk is still under review, just wondering whether there's anything I can help with or what would be the next steps.

I'll be available to help in any way possible, thank you for your help!

**Comment by carlosefr** [comment]
The deadline is January 20 and usually the bulk of the talks only gets approved after it. The `reviewing` label means we looked at it and, if there are no other labels, there is nothing in need of change. It is the expected state unless there is something wrong. 🙂

Having said this, we're going to start pre-approving talks real soon. Once pre-approved, it's guaranteed to be formally approved later on (when it's actually scheduled).

**Comment by carlosefr** [comment]
Hi. Can you please move your `.md` file out of the `2019/` directory into the root (next to `talk-title_presenter_name.md`)?

Also, can you also remove the link from the "speaker" field? It should contain your (bare) name only.

**Comment by bscruzpt** [comment]
@carlosefr , thanks for reaching out, just updated it as requested. Do let me know if there's anything else I can help with.

**Comment by carlosefr** [comment]
@bscruzpt The only thing missing is moving the file out of the 2019 folder.

**Comment by bscruzpt** [comment]
@carlosefr , I believe I already did so yesterday, with commit [781a97e](https://github.com/PixelsCamp/talks/pull/320/commits/781a97e289e6853a03a22b2c94ac155d5067e951). I might be doing something wrong though, although I do see it on the root folder, as requested. Can you help me out?

**Comment by carlosefr** [comment]
Hmm, it looks OK now. 👍

**Comment by bscruzpt** [comment]
Thanks for the confirmation!

**Comment by carlosefr** [comment]
Congratulations @bscruzpt, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling worflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by bscruzpt** [comment]
Yay, thank you for the wonderful news @carlosefr ! Hoping people will enjoy it.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
