### PR TITLE
Web Animations

### PR DESCRIPTION
**Pull request by rafaelramalho19**
Web Animations
=================================================

* Speaker   : Rafael Ramalho
* Available : Any Day
* Length    : 45 minutes + 15 minutes QA
* Language  : English

Description
-----------

Animations are a complex and big eco-system inside the web. This talk shares my 3 year knowledge of working with optimized and silky-smooth animations on the web and when to use certain techniques.

The agenda consists of:

* Performance 101
* CSS
* Canvas
* WebGL
* Web animations API
* External animations libraries

There will be demos and live previews of every technique I talk about.

Speaker Bio
-----------

Rafael spent his early career days developing full-stack applications that focused on solving client problems. He’s a declared swiss army knife, which helped him quickly evolve to try and find fast and scalable solutions in every code he produces.
Thanks to the opportunity to create optimised, as well as good-looking, animations in Pixelmatters, Rafael started to have a taste for finding smart and intuitive ways to animate the web. While working at Blip, Rafael had to carefully plan and deliver high-performing animations for millions of users.
Currently working at MOXY, Rafael is feeling the urge to share all the knowledge he gained throughout the years thanks to his involvement with the open-source community. His passion about animations has led him to give talks targeted to Designers, Product Owners and Developers in order to help them achieve and deliver smooth web-animations.

Links
-----

* Blog: https://rafaelramalho.dev
* Company: https://moxy.studio
* GitHub: https://github.com/rafaelramalho19/
* Photo: https://drive.google.com/file/d/1uxkeUkWQmDVOMfpKCgpEhWbTYiUHSF-m/view?usp=sharing

Extra Information
-----------------

The talk is available at https://www.rafaelramalho.dev/animations-presentation/#/
And the source code at: https://github.com/rafaelramalho19/animations-presentation

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, I noticed you added the `.md` file with your proposal to the `2019/` directory. Can you please move it to the root (next to `talk-title_presenter_name.md`)?

**Comment by rafaelramalho19** [comment]
> Hi, I noticed you added the `.md` file with your proposal to the `2019/` directory. Can you please move it to the root (next to `talk-title_presenter_name.md`)?

Uuuups, I was probably thinking about the wonderful time I had in pixelscamp 2019 😅

**Comment by carlosefr** [comment]
Hi, would you consider extending your talk to 45 minutes + QA or do you prefer to stick with 30 minutes? Slots are 1h long and we prefer to minimize downtime, if possible.

You can choose either way, this is not mandatory.

**Comment by rafaelramalho19** [comment]
@carlosefr Last time I did my talk I took 30 minutes without QA. So I can always add some more content or extend some explanations and do 45+QA with no problem :)

**Comment by carlosefr** [comment]
Ok, can you update both the `.md` file and the PR description to reflect that, please?

**Comment by rafaelramalho19** [comment]
Yes, done.

**Comment by carlosefr** [comment]
Congratulations @rafaelramalho19, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling worflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
