### PR TITLE
Kotlin My Way In

### PR DESCRIPTION
**Pull request by cmota**
Kotlin My Way In
=========================

* Speaker   : Carlos Mota
* Available : All times (although hopefully after 10h00 and with a cup of coffee ☕️)
* Length    : 45m + QA
* Language  : English

Description
-----------

Developers, developers, developers. 

I’ve always thought that it is amazing what we do - we never settle, we always try to figure out new things, test new things and improve the ones on which we work daily; whether it’s a newly found library, a new architecture pattern that suddenly started to be trending or in this particular case a new language called Kotlin - rejoice! 

However those things have different impacts on our projects - using a new library has a different risk than adopting a new language and this is where things get… or as you will hear got really complicated.

For the past years I’ve been trying to evangelise - wololooo - [read this with Age Of Empires priests voice] the people at my company and community into taking the step of gradually start using Kotlin on our applications. 

And it hasn’t been an easy task. First, not everyone shares the same enthusiasm in learning something new and secondly making the shift of leaving a language which they know and are familiar with to a new one requires time (both for companies and for people).

Fast forward to the present and currently we have Kotlin code in production, a team thrilled with learning new things and managers glad that all deadlines have been successfully accomplished.

I’m going to share all the steps made (the good and… not so good ones) since I first started to push Kotlin until we have an application in production powered by it. Hopefully, without making you fall asleep.

Speaker Bio
-----------

Hello human,

At night I'm fighting crime... oh wait; wrong bio here. Here it goes the uncensensored version: for several years now, I've been developing mobile applications. First on the energy consumption field, then Telco and, in the middle, of it I've found the time to create a game with some friends - Word Dare - it was fun! I'm currently working at WIT Software on the company RCSe applications - first for iOS and now on Android.

From time to time, I like to make long monologues and wait for the entire audience to fall asleep - lets call them "talks". I've been giving a few for University of Coimbra, WIT Software, DevFest, Pixels Camp, mdevcon, etc.

Links
-----

* Medium: https://medium.com/@cafonsomota
* Twitter: https://twitter.com/@cafonsomota
* GitHub: https://github.com/cmota

Extra Information
-----------------

I've had the chance to present before at Pixels Camp with my talk - Perception of Speed:
> https://www.youtube.com/watch?v=Rc_rXl4C_A0&list=PLTlIsr2wnuwWTG27Ifw9XW7ql41mayA7i

### CODE REVIEW

**Comment by edevil** [comment]
Hello, thanks for the talk proposal. Would you consider extending the talk to 45m + QA?

**Comment by cmota** [comment]
Sure, no problem @edevil. Should I update the talk time 45m + QA then?

**Comment by edevil** [comment]
Yes, please.

**Comment by carlosefr** [comment]
This talk has been pre-approved, which makes your other proposal in PR #268 unlikely (but not impossible) to be approved.

**Pull request merged**
