### PR TITLE
Are we paying attention to what we building?

### PR DESCRIPTION
**Pull request by mstrlaw**
Are we paying attention to what we building?
=================================================

* Speaker   : Lawrence Braun
* Available : Any
* Length    : 60 minutes
* Language  : English

Description
-----------
When we conceptualize and build products, we make decisions on a daily basis that affect our users more than we may think. We want to delight them with our products but also need to drive their behavior in hopes of achieving our goals. This talk is about exploring how seemingly small things can have ethical/moral implications and how technology can be a double-edged sword.

Speaker Bio
-----------
Senior Frontend Developer @unbabel. Interested on how technology affects people and society at large. Always looking forward to build something meaningful.

Links
-----
* Blog: https://medium.com/@mstrlaw
* Company: https://unbabel.com/
* GitHub: https://github.com/mstrlaw
* Photo: https://miro.medium.com/fit/c/256/256/1*cOCuZpj7YgGGF6DPTDhoJA.png

Extra Information
-----------------
This is less of a technical talk and more of an invitation to reflect on how, as technologists, we have the capacity to affect the world and how this capacity can be put to use (good and bad).

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, thanks for the proposal.

Would you consider extending your talk to 45 minutes + QA to avoid stage downtime? (All slots are 1 hour long).

**Comment by mstrlaw** [comment]
Hey @carlosefr ,

Sure no problem.

**Comment by carlosefr** [comment]
Cool. Can you please update the PR description above, as well as the `.md` file?

**Comment by mstrlaw** [comment]
Done ✔️

**Comment by carlosefr** [comment]
Congratulations @mstrlaw , your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by mstrlaw** [comment]
Great! Thanks!

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
