### PR TITLE
Machine that goes Ping: Low Power Sensor nodes with Python

### PR DESCRIPTION
**Pull request by jmarcelino**
Machine that goes Ping: Low Power Sensor nodes with Python
=================================================

* Speaker   : Jose Marcelino
* Available : All days
* Length    : 90 minutes (ideally)
* Language  : English

Description
-----------

"Hardware is Hard" is a common saying and often true as developing hardware traditionally requires a great number of skills, years of experience and many physical tools.

In this hands-on, practical workshop, we will challenge this notion through the recent development of Python on low cost microcontrollers,  MicroPython - now spreading in a similar trend to how BASIC drove the microcomputer revolution of the late 1970s.

We will introduce low power wide area (LPWAN) wireless networks made for IoT such as Sigfox, LoRa and NB-IoT and demonstrate how to connect your MicroPython device to them in an efficient way.

Finally we will take the next step - and make the "Ping" part of the title true - by introducing SCHC (pronounced Chic), the new IETF protocol which enables IPv6 over those LPWANs.

Note: Bring your computer for the hands-on part - you will get your a device to program and play with (usually restricted to 20 devices, may be possible to share devices between attendees)

Speaker Bio
-----------

Originally from Setubal, Portugal Jose is the IoT Solutions Architect at Omnium Sensing, part of a large Engineering group in the North East of UK.

Previous workplaces have included Pycom - makers of popular ESP32 based MicroPython boards with ample connectivity options - and his company Metavurt.

He has experience in applying various sensor and connectivity options - Bluetooth, LoRa, Sigfox, and LTE/NB-IoT - to 'mine' new information from existing systems. When not wiring up something new he's a regular speaker at various Meetups and events such as Things Conference.

Links
-----

* Twitter: https://twitter.com/jmarcelino
* Company: https://omniumsensing.com
* GitHub: https://github.com/jmarcelino
* Photo: https://avatars0.githubusercontent.com/u/3199956?v=4

Extra Information
-----------------

Previous workshop at Pixels Camp 2017: Low Power Radio WAN: LoRa and Sigfox

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, your proposal was submitted after the deadline. This doesn't mean it won't be considered, but means it will be considered only after the ones that were submitted before/on January 20.

**Comment by jmarcelino** [comment]
Oh that is too bad, I guess my defence that it was still January 20 in Ponta Delgada is of no help? :-)

**Comment by carlosefr** [comment]
Since we didn't specify timezones in the README, it would be fair to consider any Portuguese timezone, but only if you actually lived in Ponta Delgada (and I've checked your LinkedIn).  ;)

**Comment by carlosefr** [comment]
Hmmm, hadn't noticed you marked this as an workshop. That changes things since it looks like we can still acomodate workshops.

**Comment by carlosefr** [comment]
Congratulations @jmarcelino , your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
