### PR TITLE
KDD: Kubernetes Driven Development

### PR DESCRIPTION
**Pull request by mccricardo**
KDD: Kubernetes Driven Development
=========================

* Speaker   : Ricardo Castro
* Available : All days
* Length    : 45min + QA
* Language  : English

Description
-----------

Kubernetes is becoming the standard in container orchestration but tooling is still lagging behind more mature environments. While that’s true, the community has rallied behind this technology and has started to develop tools to help develop, manage and deploy Kubernetes ready applications. This talk aims to introduce tools like Telepresence to improve development by allowing easy interfacing with Kubernetes deployed services, Skaffold to automate builds and deploys and Helm to manage deploys. This talk will also live demo the development of an application and demonstrate all those tools at work.

Speaker Bio
-----------

DevOps and Site Reliability Engineer at Uphold building highly performance, reliable and scalable systems. Strong believer in culture and teamwork. Open source passionate, taekwondo amateur and metal lover.

Links
-----

* Blog: http://mccricardo.github.io/
* Company: https://uphold.com/

Extra Information
-----------------

Previous Talks:
* [DevOpsDays Warsaw](https://devopsdays.pl/bio.html#id=35706)
* [TugaIT](https://techinporto.com/archive/2018/speakers/ricardo-castro/)
* [TechInPorto](https://tugait.pt/speakers/ricardo-castro/)

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, would you mind extending the talk to 45 minutes + QA, or do you prefer to stick with 30 minutes?

**Comment by mccricardo** [comment]
Not at all. There's enough content to extend to 45min + QA.

**Comment by carlosefr** [comment]
Can you update update the proposal and the PR description accordingly? Thanks.

**Comment by mccricardo** [comment]
Done.

**Comment by carlosefr** [comment]
The proposal still says 30 minutes. ;)

**Comment by mccricardo** [comment]
You're absolutely right. Fixed now.

**Pull request merged**
