### PR TITLE
Vue your next frontend framework

### PR DESCRIPTION
**Pull request by caneco**
# Vue your next frontend framework
- Speaker   : Vitor Caneco
- Available : October 6th or 7th (all-day)
- Length    : 30-45 mins
- Language  : English or Portuguese
### TL;DR

Learn how to grab your JSON data and build an instant single-page application under 45 minutes.
## 

_Vue.js_ it's the next "angle", the next "reaction", the faster "ember"... (ok enough with the puns).
Well _Vue.js_ it's not a full-blown framework, it focus on the view layer only. This makes a faster framework and opens the compatibility with other libraries and extensions.

In this talk I will walktrough on how you can build your next single-page application from your API under 45 minutes.
## Speaker Bio

Web Contortionist. Short for Developer being Designer and vice-versa @KwankoGroup // Father, Ideist, Full Stacker, Laravelist
## Links
- Twitter: http://twitter.com/Caneco
- Github: http://github.com/caneco
- Company: http://www.kwanko.com

### CODE REVIEW

**Comment by LuRsT** [comment]
@caneco Can you copy paste your talk proposal to the PR description so we can read it easily? Thanks!

**Comment by caneco** [comment]
@LuRsT thanks for the heads up :)

**Comment by LuRsT** [comment]
You're welcome @caneco, just make sure to save some stickers for me if you make some with the pixels camp logo :D

**Comment by caneco** [comment]
@LuRsT already thinking about the design of them 💃

**Comment by celso** [comment]
@caneco you need to read this https://github.com/PixelsCamp/pixels_camp_2016_talks/blob/master/README.md

**Comment by caneco** [comment]
@celso 

> Deadline for submitting talks is July 31st. After than we won't be accepting more pull requests.

…Now where is that perfect _facepalm_ GIF?

## 

Still I leave my talk proposal as a backup if you need or if you're opening any _unconference_ area :)

**Comment by pjanuario** [comment]
@celso I also submitted mine recently, because Pixel camps newsletter still mention it! :)

> You can also apply to give a talk if you feel like it.

**Comment by celso** [comment]
Again, you can still submit talks but you need to follow the guide. This pull request has no content, we can't do nothing with it. @pjanuario @caneco

**Comment by LuRsT** [comment]
> …Now where is that perfect facepalm GIF?

@caneco, Celso was just talking about what I told earlier (putting the contents of the file in the PR description) since you just replaced the title, the PR still doesn't conform to the rules. The deadline was extended.

**Comment by caneco** [comment]
@celso so that was the thing… Done! /cc @LuRsT @pjanuario

---

Cross your pixels!

**Pull request closed without merging**
