### PR TITLE
Going Remote - Everyday challenges

### PR DESCRIPTION
**Pull request by andrezzoid**
Going Remote - Everyday challenges
=========================

* Speaker   : André Jonas
* Available : second or third day
* Length    : 20 minutes
* Language  : English

Description
-----------

Remote Work. Is it all cookies and rainbows as all those articles in the Internet talk about? Does it mean I can stay in my jammies all day or work through the night? Successfully managing your remote software development career is the embodiment of work-life balance. It comes with a very specific set of difficulties but can also be achieved through a very simple set of principles that I'm going to present in this talk.

Speaker Bio
-----------

André has been giving amazing talks for 10 years... nope, he hasn't! He has been spending the last 4 years working remotely though, help building great teams, remote culture, mentoring engineers and being a part of the amazing tech community in Algarve. Oh and coding!.. he also codes... kind of.

Links
-----

* Company: https://www.yld.io/
* GitHub: https://github.com/andrezzoid/
* Twitter: https://twitter.com/andrezzoid/

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi. Do you care to extend the length of your talk to 45 minutes + QA?

If not, it needs to be at least 30 minutes + QA to be considered.

**Comment by andrezzoid** [comment]
Hey @carlosefr, thanks for reviewing it.
Sorry it's a short talk, don't think I can do 30 minutes + QA. Maybe 30 minutes with QA included if I added a few extra slides or memes 😄

**Comment by carlosefr** [comment]
The slots are 1h long. With extra scheduling effort we can fit slightly shorter talks. But 20 minutes just leaves a big 40 minute hole and we cannot accommodate it.

Perhaps you can resubmit as a lightning talk later on (it's not confirmed yet if we'll have lightning talk slots).

**Comment by andrezzoid** [comment]
Alright, thanks for taking the time 🙂 I'll keep looking to see if you're doing these lightening talks

**Pull request closed without merging**
