### PR TITLE
Innovating in Enterprise Software: Tales from the Trenches

### PR DESCRIPTION
**Pull request by diogoeag**
Innovating in Enterprise Software: Tales from the Trenches
========================

* Speaker   : *Diogo Guerra*
* Available : *September 28th, 29th, 30th*
* Length    : *30 mins*
* Language  : *English*

Description
-----------

How can enterprise software be exciting, challenging and fast? Enterprise grade systems are most of times linked to boring, heavy and slow software development, however that's not true!

What is an enterprise grade system? Is it really different from others? Is there space for innovation? How fast can you move? What are the myths and the realities of building such systems?

In this talk I will speak about my journey on building an enterprise grade system that has the strongest requirements of performance, security and availability at the same time that innovation was and still is essential for our survival. How we have introduced new technology into the product, the strong partnerships with top technology companies like Datastax or Azul Systems that build high performance platforms like Cassandra and Zing JVM, and the state of the art processes to deliver quality software for Fortune 500 corporations.

A brief walk-through on building a real time distributed system that can't fail or slow down and that raises the bar to any Machine Learning pipeline.  

I will also share how fun and rewarding this journey has been, the rush and the fun of building and operating top level, mission critical systems.

---------------

Speaker Bio
-----------

Engineer at heart, my technical passions are software architecture and performance. I've been working on real-time systems in the digital payments area for 8 years. My ecosystem is Linux and Java platforms and extracting the last millisecond of performance of any system is what keeps me up at night. 

Employee #1 at Feedzai, currently as VP of Engineering I'm mostly working on making sure software teams deliver the top level enterprise software.

I also love cars (and motorized vehicles in general) and cooking when I'm not building software systems.    

Links
-----

* Company: http://www.feedzai.com
* Github: http://github.com/diogoeag

### CODE REVIEW

**Comment by celso** [comment]
@diogoeag we're not getting an answer from you if you're going to give the talk. Are you?

**Comment by diogoeag** [comment]
@celso yes. I confirm.

**Comment by celso** [comment]
No answer from the speaker. E-mail sent on the 28th August and no reply. Closing PR :(

**Comment by diogoeag** [comment]
@celso I've reached out to you in Slack. I've answered here 18 days ago.

**Comment by celso** [comment]
@diogoeag I don't have the bandwidth to attend everyone on different channels and keep up with it, sorry. All we ask if for everyone to read the emails. You should have one asking you to confirm the talk. Can you answer the email? We can re-open this PR if you're willing to give the talk and confirm (via e-mail). Thanks.

**Pull request merged**
