### PR TITLE
From Monolith to Serverless Cloud Applications

### PR DESCRIPTION
**Pull request by vpaulino**
From Monolith to Serverless Cloud Applications
=================================================

* Speaker   : Vitor Paulino
* Available : any day any time
* Length    : 50 minutes
* Language  : English or Portuguese

Description
-----------
How do you plan and architect your monolith application migrations to the cloud? What changes to the application design and architecture should we consider if the goal is to go as fully native as possible?

In this presentation we will walk through the main drivers that can help us understand the effort involved in migrating to a cloud native solution, as well as the path from a monolith to a microservices (or perhaps serverless) deployment.

Speaker Bio
-----------

I’m a Software engineer with +10 years of experience designing, developing, testing and deploying backend distributed applications mainly on .NET and javascript technologies stacks to support a variety of different communication patterns and repository characteristics customized to the needs of the clients requirements and recently migrating monolith and On-Premises solutions to the cloud. The mindset that I put in place every time I face a new challenge always consider software development best practices such as SOLID principles, GoF design patterns and methodologies that enable good software quality. Always available to learn, adapt, help, coach and support the team, sharing knowledge an discuss solutions.

Links
-----

* Company: https://new.siemens.com/pt/en/company/jobs/jobs/lisbontechhub.html
* GitHub: https://github.com/vpaulino
* Photo: https://avatars3.githubusercontent.com/u/859157?s=460&v=4

Extra Information
-----------------

The contents of this presentation will be very similiar to the one I have presented here: 
https://www.meetup.com/en-AU/Azure-Wednesdays-Portugal/events/266033123/

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, thanks for the proposal.

Can you please make the description a bit clearer, it's a bit cloudy (pun intended) as it is. Maybe make it shorter? There are also a couple of typos as well, nothing serious.

You PR is also deleting the template file. Please correct this so that your proposal can be considered.

We are marking your proposal as "restricted availability" because being available in the afternoons only may cause additional scheduling difficulties, if approved.

**Comment by vpaulino** [comment]
also changed the availability.

**Comment by carlosefr** [comment]
Can you revise the talk description, please? If approved, that's the text that will go into the event calendar and the english is kind of wonky (also, there are a few typos in there as well).

**Comment by vpaulino** [comment]
revisiting .... can you give me a timeline to when it would be great to have this done?

**Comment by carlosefr** [comment]
We do not consider proposals with pending issues when reviewing them for a decision, so I'd say as soon as you can.

**Comment by vpaulino** [comment]
I have made changes to be more explicit about the goal of the presentation, and a description what viewers can expect to be presented. Depending on the time that this could be until is approved, the presentation could be only code, or if this is approved very close to the event, then it will be more ppt oriented.  @carlosefr, if something is not ok, could you be more specific regarding the missing information ?

**Comment by carlosefr** [comment]
May I suggest the following changes to the talk description?

> How do you plan and architect your monolith application migrations to the cloud? What changes to the application design and architecture should we consider if the goal is to go as fully native as possible?
>
> In this presentation we will walk through the main drivers that can help us understand the effort involved in migrating to a cloud native solution, as well as the path from a monolith to a microservices (or perhaps serverless) deployment.

Also, due to logistics constraints, we cannot guarantee any more stage slots at this moment. In the **beginning of March** more slots are likely to become available and we will approve a few more proposals as we can, so this isn't a rejection notification.

We understand that delaying a decision reduces the time you have to prepare, shall your proposal turn out to be approved. So, if you need a decision from us until a particular date, please tell us.

**Comment by vpaulino** [comment]
I have updated the description as sugested. @carlosefr . I will be waiting then for updates

**Comment by carlosefr** [comment]
Please update the `.md` file as well. Thanks.

**Comment by vpaulino** [comment]
Hi there, 

I have read the rules and I did not understand what other md file a need to update, and btw with what ?

Best regards

**Comment by carlosefr** [comment]
You have updated the PR description above, but haven't updated the `.md` file contained in the PR itself.

**Pull request closed without merging**
