### PR TITLE
Liberating Structures: Transform how people interact and work together!

### PR DESCRIPTION
**Pull request by nunoaspereira**
Liberating Structures: Transform how people interact and work together!
===========================================================================

* Speaker   : Nuno Silva Pereira and Marco Zbinden
* Available : first and second day
* Length    : Hands-on Workshop - 2 hours
* Language  : English

## Description

Change the way you interact with your friends, colleagues and co-workers!

With Liberating Structures, you will be able to _achieve better results than what is possible with conventional methods_ (presentations, reports, etc.). This informal and simple approach allows people to work at the top of their intelligence and creativity, while enjoying their work.

In this **2h workshop you will experience hands-on how to apply Liberating Structures into your touchpoints** (meetings, retrospectives, brainstorms, stand-ups, workshops, inceptions,…).

Together, we will see how to structure one of those touchpoints using different Liberating Structures, in order to:
 - Accomodate groups of any size
 - Make your touchpoints engaging and simple
 - Give everyone equal opportunity to contribute
 - Maximize active participation while reducing bias

## Speaker Bio

Nuno Silva Pereira (https://www.linkedin.com/in/nunosilvapereira/)
Nuno Silva Pereira is a Delivery Lead @ Equal Experts working across different geographies and industries. He has worked for more than 14 years within IT and Telcos (Sapo, Portugal Telecom, NOS). He is a member of Agile Connect and co-organizer of the Agile Connect Lisbon Meetup and Agile Coach Camp Portugal. Speaker in several conferences (several times @ Pixels Camp) and Meetups.
I have been using Liberating Structures for the last 2 years and i would like to share those techniques with you.

Marco Zbinden (https://www.linkedin.com/in/marco-zbinden-7848409/)
Marco Zbinden works as a communication coach and facilitator. He and his partner are the Future Now Consultants. They are specialised in interactive workshop formats to engage people emotionally and help organisations adressing the elephant in the room. One main tool they work with since about 4 years is Liberating Structures. Having an acting background they also often use performative elements to support this objective. Marco is Swiss and lives in Portugal since 1,5 years. In Lisbon he has co-founded the local Liberating Structures user group.

## Links

* Blog: https://medium.com/@nunosilvapereira
* Company: https://www.equalexperts.com
* GitHub: https://github.com/nunoaspereira
* Photo: https://drive.google.com/file/d/0B6oNQPPVwhzEWHNLRDNia0JWZjQ/view?usp=sharing

## Extra Information

I have been a speaker at all Pixels Camp, giving 5 talks and organising one Agile Connect Meetup. Would like to continue to share more with all of the campers. Thanks!

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, thanks for the proposal.

There are a few typos in the description; Can you correct them, please?

Also, can you describe a bit why this is a workshop and not a talk? Is it just because it requires more than 1 hour?

**Comment by nunoaspereira** [comment]
@carlosefr Hi, sorry for the delay. Got lost in all the mails from the repo.

Description updated. Hope this makes it easy to understand that it is a completely a hands-on workshop.

Thanks.

**Comment by carlosefr** [comment]
Congratulations @nunoaspereira, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

We're considering this talk as sponsored by the **Agile Connect** meetup.

**Comment by carlosefr** [comment]
I'd suggest changing the title to be "Liberating Structures: Transform how people interact and work together!" so that it looks better when truncated in the calendar.

If you agree, please change both the `.md` file and the PR description and title above. If you don't, it's OK as it is. :)

**Comment by nunoaspereira** [comment]
@carlosefr Thanks for the suggestions. Updates done on the PR description and title, as well as, on the .md.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
