### PR TITLE
Can you trust your dependencies?

### PR DESCRIPTION
**Pull request by ricardofbarros**
# Can you trust your dependencies?
- Speaker   : Ricardo Barros
- Available : Anytime during the conference
- Length    : 20mins talking, including questions.
- Language  : English
## Description

The Node.js culture is very active in creating and publishing modules for almost every imaginable need. On average, a Node.js project has a lot more dependencies than projects with other technologies like .NET or Java. Managing those dependencies can become overwhelming if the project has hard requirements in terms of reliability or legal.

There is to many modules to approve, npm has almost three hundred thousand modules and it's still growing. So it makes total sense to have a tool that gives you an overview of your dependencies and tell what are you exposed to.

---

[_All things below are optional_]
## Speaker Bio

Ricardo Barros is a Javascript aficionado working at YLD. He is devoted to open source and the JS community, always eager to learn, and a great team player. This being said, he also enjoys a good debate once in a while. To unwind, Ricardo enjoys cinema and hanging out with great friends with a couple of beers.
## Links
- Company: https://yld.io
- Github: http://github.com/ricardofbarros
- Twitter: https://twitter.com/ricardofbarros

### CODE REVIEW

**Comment by celso** [comment]
@ricardofbarros check your emails please

**Comment by ricardofbarros** [comment]
Hey @celso I've checked and double checked but didn't find any email related with pixelcamp. Could you resend it to ricardofbarros@hotmail.com ? Thanks

**Comment by celso** [comment]
You need to apply at https://pixels.camp/apply

**Comment by celso** [comment]
Our logs say we've sent you 3 emails already:

2016-09-01T00:32:13.583: celso sent needtoapply email to user at r..@hotmail.com
2016-08-24T09:59:33.233: celso sent needtoapply email to user at r..@hotmail.com
2016-08-22T15:20:24.260: celso sent needtoapply email to user at r..@hotmail.com

**Comment by celso** [comment]
@ricardofbarros thanks for your submission, but we're out of slots in the calendar now and we need to take tough decisions. We'll reopen your PR if a new slot emerges.

**Pull request closed without merging**
