### PR TITLE
Egoless Programming

### PR DESCRIPTION
**Pull request by andrezzoid**
Egoless Programming
=================================================

* Speaker   : André Jonas
* Available : second day, third day
* Length    : 30 minutes
* Language  : English

Description
-----------

There is no "i" in team, we've all heard that. Yet everyday we let our inflated egos get in the way of our work, our team, our projects, our company. This is a wake up call. No more! In this talk we will explore together the very nature of ego and take away practical advice on how to deal with it in our everyday jobs.

Speaker Bio
-----------

A geek, a problem solver, a communicator and forever a student - André is seasoned software engineer and a former teacher working remotely from the Algarve on a mission to support fellow engineers to do their best work.

Links
-----

* Blog: https://andrejonas.com/
* GitHub: https://github.com/andrezzoid/
* Photo: https://pbs.twimg.com/profile_images/1069707114161954816/DuLbABq6_400x400.jpg

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, thanks for the talk proposal.

However, the `.md` file is not in the proper format for consumption by our backoffice. Can you please modify it to follow the provided template?

Also, titles cannot have formatting in them (such as italic, bold, etc.)

**Comment by andrezzoid** [comment]
Hey Carlos, thanks for getting back at me. I'll remove the italic from the title. Can you tell what else is not following the format? I've used the  provided template.

**Comment by carlosefr** [comment]
If you compare:

https://raw.githubusercontent.com/PixelsCamp/talks/master/talk-title_presenter_name.md

**Comment by carlosefr** [comment]
If you compare both files, you'll see what I mean (look at how titles are defined):

- https://raw.githubusercontent.com/PixelsCamp/talks/master/talk-title_presenter_name.md
- https://raw.githubusercontent.com/PixelsCamp/talks/9720a9549c98004534ba14409d6b1c3a3b81c45b/egoless-programming_andre_jonas.md

Both are valid markdown, and should be equivalent, but for consistency we prefer that all proposals follow the same format. Also, we have some ad-hoc scripts further down the workflow that may or may not like deviations from the template format.

**Comment by andrezzoid** [comment]
My text editor was fooling me, formatting the markdown to what it thought it should be 😅 think it's consistent with the format now. Thank you so much Carlos!

**Comment by carlosefr** [comment]
Would you consider extending your talk to 45 minutes + QA to avoid stage downtime? (All slots are 1 hour long).

**Comment by andrezzoid** [comment]
Hey @carlosefr 👋 to be honest I don't have more content to add (nor brain to memorize so many lines 😅), 30 minutes + QA is be the best I can do.

**Comment by carlosefr** [comment]
Congratulations @andrezzoid, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by andrezzoid** [comment]
That's amazing, thanks @carlosefr!

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
