### PR TITLE
a skynet office framework or something

### PR DESCRIPTION
**Pull request by frm**
a skynet office framework or smth
===============================

* Speaker   : Fernando Mendes
* Available : September 29-30 - no time restrictions
* Length    : 45 min
* Language  : English

Description
-----------

... or how I over-engineered a bunch of sensors.

I spent the last year working on a smart office. But this wasn't going to be
just _any_ smart office. It had to be capable of doing _everything._ And also
_anything_ . And it had to be _distributed_ . And handle _big data_ . And work
_offline_ . And support _DIY stuff_ . And _buzzwords_. Also, it had to be _cool_
and _hip_ and run on _Elixir_ .

The adventure begins when I wanted to optimise the productivity of our office at
Subvisual by managing environmental values: temperature, humidity, sound levels
and lighting. My first goal was to constantly display those readings and warn us
if any of them was sub-optimal. I somehow got sidetracked and ended up with a
P2P network in a distributed architecture or smth.

In this talk, I'll go through the implementation of a distributed architecture
for a smart office. We will figure out how to connect Raspberries, Beaglebones
and what not. Then go through distributed systems stuff like figure out if we
want a server or P2P protocols and how to use eventual consistency.  We'll get
to know how to ~over-engineer~ modify the P2P network to add *any* custom DIY
node, but we'll mostly end up by collectively shaming myself for tapping into my
developer's heart and pulling out what's at its core: a bunch of
not-so-brilliant, over-engineered ideas.

---------------

Speaker Bio
-----------

I'm a nice lad from Braga, fresh out of university and eagerly awaiting for the world to slap me in the face with constant disappointment.

Although I'm doing web development, IoT and distributed systems, deep down I'm just happy I was born late enough to not be working with Visual Basic and soon enough to not be replaced with self-writing JavaScript.

I'm also very good at talking with people about the following topic:

- Last night's game
- The weather today
- How much I dislike Java
- How awesome cats are
- The weather next week

Links
-----

* Company: [https://subvisual.co](https://subvisual.co)
* Github: [https://github.com/fribmendes](https://github.com/fribmendes)
* Twitter: [https://twitter.com/fribmendes](https://twitter.com/fribmendes)

### CODE REVIEW

**Comment by carlosefr** [comment]
That description won't fit in the calendar... 😉

**Comment by frm** [comment]
@carlosefr what's the character limit?

**Comment by carlosefr** [comment]
You should instead ask what's the attention limit of participants trying to figure out what your talk is about. 😄

**Comment by frm** [comment]
@carlosefr thanks for the feedback!

Can I question the `maker` label? I updated the description to be more clear on this, but I won't be talking much about SBCs and stuff like that. I intend on leaving that aside and focusing on the actual distributed system and connecting everything through a wireless network. It's more of a talk on hipster P2P protocols, eventual consistency and distributed systems.

**Pull request merged**
