### PR TITLE
Interact Research by Artica Creative Computing

### PR DESCRIPTION
**Pull request by guibot**
* Speaker   : Guilherme Martins and André Almeida
* Available : first day, second day, third, day
* Length    : 60 minutes
* Language  : English or Portuguese

Description
-----------

Artica has been in the Creative Industries market since 2011, embracing many different customized projects involving robotics, VR, AR, multi-user interactive installations, museums, exhibitions and even elevators.

In this talk, Artica is going to share with you a Research Project entitled Interact:
Interactive New Technologies Regarding Augmentation in a Computerized Taxonomy.
 
This research project aims to explore paradigms that involve:
- Multiple-users interactive installations
- Mixed realities, when physical and virtual worlds are blended
- Multi-User Capture the Flag, with AR and GPS  
- And more..

Speaker Bio
-----------

Guilherme Martins is self-taught inventor, visual artist, maker, tinkerer. Passionate by all sorts of art, design and technology. His compulsive research habits took him to dive deep in educational robotics kits, visuals for interactive video installations, modular physical interfaces and exotic mandalas.

André Almeida has extensive knowledge in interaction design, Computer Vision, VR and AR technologies. André has a curious mind and is a researcher by nature. Passionate by robotics, mechatronics, computer vision, AR, VR, and multi-user interactive installations.

Links
-----

* Blog: https://medium.com/artica
* Company: https://artica.cc/
* GitHub: https://github.com/artica/
* Photo: https://drive.google.com/file/d/11qeP6HJbwrp_OGNlxQIdLpt8wOYZGjUc/view?usp=sharing

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, your proposal was submitted after the deadline. This doesn't mean it won't be considered, but means it will be considered only after the ones that were submitted before/on January 20.

**Comment by carlosefr** [comment]
Hi,

Can you please remove the extra bits at the top of the `.md` file?

Also, perhaps you should revise the talk title. For the attendees that don't know beforehand what/who Artica is, the title sounds a little commercial.

Something like "Interact: _something short that describes it_" would be better.

**Comment by carlosefr** [comment]
Besides the comments above, I see that you're submitting the talk in the name of another person. Submissions should be made by the speakers themselves or, at least, contain an indication of the speaker's GitHub username.

Speakers should apply and be accepted as Pixels Camp attendees as well (to enter the venue), and the username information is required to be able to check this.

I've not been able to find the referred speaker in the Pixels Camp attendee database.

**Comment by meddulla** [comment]
We can't find André Almeida in the list of attendees. Has he already applied? We also need his github handle.

**Comment by carlosefr** [comment]
@guibot We still can't find André's application in the Pixels Camp attendee database. This is necessary for us to be able to consider this proposal for approval.

**Comment by carlosefr** [comment]
This is a reminder that we need to know André Almeida's GitHub username (and he needs to apply as an attendee) before considering this talk for approval.

**Comment by carlosefr** [comment]
@guibot Any news? This information is **required** for this talk to be approved.

**Comment by arspda** [comment]
Just did apply in the list of attendies, arspda@gmail.com.
Do I need to do anything else

**Comment by carlosefr** [comment]
Congratulations @guibot and @arspda, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
