### PR TITLE
Everyone is naked: attacking the DHT

### PR DESCRIPTION
**Pull request by gpestana**
Everyone is naked: attacking the DHT
=========================

* Speaker   : Goncalo Pestana
* Available : Any time
* Length    : 45m + QA
* Language  : English

Description
-----------

Distributed Hash Table (DHT) is an important primitive which allows network peers to collaboratively store and retrieve data in a decentralized network. Nowadays, millions of users are using services which rely on DHTs: Bittorrent, IPFS, Freenet, Ethereum are some examples of networks which use DHTs. As the Web 3.0 ecosystem becomes mainstream, the number of systems relying on DHTs are expected to increase.

However, naive implementations of DHTs leak critical information about user behavior and user metadata (e.g. who is storing and retrieving specific files in the network). In a DHT network, it is trivial for adversaries to collect network information that can be correlated to understand what the users are up to. The data leaked can be used for mass surveillance, censorship and privacy attacks on DHT users and services.

As P2P networks and decentralized systems (re)gain popularity among researchers and industry alike, it is important to design and implement decentralized systems that preserve users’ privacy. Failing to deliver on this will render decentralized systems unusable and unattractive for mass adoption or as a viable alternative to centralized systems.

In this talk, our goals are to learn what DHTs are, how they are used and how to improve privacy of existent designs. We first dive into what are DHTs, how they work and its privacy vulnerabilities. After motivating the reasons for why privacy preserving networks are important for the future of the internet and society, we'll perform a live privacy attack on a public DHT. We will see how easy it is to collect and correlate public activity in DHTs and try to understand its consequences from a user perspective. We wrap up by going through some mechanisms and protocols used to harden privacy in DHTs based on the latest research, such as onion routing, friend-to-friend routing, and others.

Speaker Bio
-----------

engineer and researcher at hashmatter, focusing primarily on metadata resistance systems, networking and decentralization

Links
-----

* Blog: https://gpestana.com
* Company: https://hashmatter.com
* GitHub: https://github.com/gpestana

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi, can you please review the talk description a bit? There are some typos in there.

Also, I edited your comment as per the talk submission rules.

**Comment by gpestana** [comment]
@carlosefr thanks for the heads up. I've reviewed the talk description, let me know what you think about it.

**Comment by carlosefr** [comment]
Hi. Your talk has been tagged for acceptance. Congratulations!

I still see some typos in there, if you care to clean up a bit for future inclusion in the calendar, it would be welcome.

**Comment by gpestana** [comment]
Great, awesome to hear! Could you point out where the typos are in here https://github.com/PixelsCamp/talks/pull/202/files with comments or something? I can't find them :) thanks!

**Comment by carlosefr** [comment]
I can be somewhat of a grammar nazi, but I've tried to control myself and edited directly in the first comment. :)

_PS:_ But the proposal contained in the PR still needs to be edited by the author, you.

**Comment by carlosefr** [comment]
You added a thumbs up but didn't update the proposal in the PR. ;)

**Comment by gpestana** [comment]
Updated. If you find some typo or any other problem, please be more concrete at pointing out where to change. thanks!

**Comment by carlosefr** [comment]
Hi. Thanks for the updates.

As I mentioned, I had edited the PR description. Its history shows exactly what was changed.
screen shot 2019-01-18 at 11 40 16

**Comment by gpestana** [comment]
Got it! 👍 I checked the latest fixes and updated the PR. Can you please double check if I didn't miss anything? thanks!

**Pull request merged**
