### PR TITLE
Edge Computing of Today

### PR DESCRIPTION
**Pull request by adaptive**
Edge Computing of Today
=================================================

* Speaker   : Hugo Romano
* Available : All days, Anytime
* Length    : 45 minutes + QA
* Language  : English

Description
-----------

Feature analysis and benchmarking of the Edge Computing solutions in the market (e.g. Cloudflare, Fastly, AWS, Google Cloud) today, and what is coming tomorrow, perhaps "Fight Climate Change"...

Speaker Bio
-----------

Software developer since 1999, working for travel, health and defence industries. MVP of Cloudflare Community and Local Meetup co-organizer. Also, the revenue manager of companies in travel and lodging, leveraged by machine learning and edge computing. 

Links
-----

* Twitter: [@adaptive](https://twitter.com/adaptive)
* GitHub: https://github.com/adaptive
* Photo: https://avatars2.githubusercontent.com/u/17833?s=460&v=4

Extra Information
-----------------

It is more a "State of Edge Computing" today and is being released soon. Presenting developers what path should they choose for their projects. Vendors Benchmarking: Feature analysis, lock-in risk, Geo-agnostic scope, Global coverage, and rough Economics.

Finishing with an opportunity to fight Climate Change.

### CODE REVIEW

**Comment by carlosefr** [comment]
Hi. Thanks for the proposal.

Would you consider extending it to 45 minutes + QA to minimize stage downtime? (All talk slots are 1 hour long).

**Comment by carlosefr** [comment]
Hi, can you please also remove the link from the speaker field?

**Comment by adaptive** [comment]
@carlosefr updated in accordance

**Comment by carlosefr** [comment]
Congratulations @adaptive, your talk proposal has been pre-accepted.

This means it's actually approved for Pixels Camp just not yet in our scheduling workflow (that will happen at a later date, and you should get an email about it when it happens).

In the meantime, if you have any questions, you can contact us at org@pixels.camp.

**Comment by carlosefr** [comment]
We're considering this talk as sponsored by the **Madeira Tech** meetup.

**Comment by carlosefr** [comment]
We're sad to inform you that Pixels Camp v4.0 has been canceled due to the still ongoing pandemic. Please refer to this blog post for more details:

https://blog.pixels.camp/about-pixels-camp-v4-0-6fd8b91cc8f2

On behalf of the organization, thank you for having proposed a talk. We would have been delighted to have had you with us in Lisbon in November to deliver it and hope you'll consider submitting again for a future Pixels Camp edition.

**Pull request merged**
